### ISSUE TITLE
Why there are some many errors in hadoop?

### ISSUE THREAD

**Issue by lifubang** [Microsoft/pai#1020]
I set up a openpai cluster with quick-start.
When I visit the hadoop ui, I find some errors:
![image](https://user-images.githubusercontent.com/783424/43440598-80c1cb9e-94ca-11e8-8855-d0aacafe30e4.png)
While the error task have no logs. and the success task's log is:
```
Log Type: AllDebug.log

Log Upload Time: Tue Jul 31 05:23:45 +0000 2018

Log Length: 379522

Showing 4096 bytes of 379522 total. Click here for the full log.

ad-1] com.microsoft.frameworklauncher.common.service.AbstractService: Succeeded
2018-07-31 05:23:43,982 INFO [pool-1-thread-1] com.microsoft.frameworklauncher.common.service.AbstractService: [ExitType]: SUCCEEDED
2018-07-31 05:23:43,982 INFO [pool-1-thread-1] com.microsoft.frameworklauncher.common.service.AbstractService: ________________________________________________________________________________________________________________________________________________________________________________________________________
2018-07-31 05:23:43,982 INFO [pool-1-thread-1] com.microsoft.frameworklauncher.common.service.AbstractService: [ExitCustomizedDiagnostics]:
2018-07-31 05:23:43,982 INFO [pool-1-thread-1] com.microsoft.frameworklauncher.common.service.AbstractService: [ApplicationCompletionReason]: All Tasks completed and no ApplicationCompletionPolicy has ever been triggered: TotalTaskCount: 10, FailedTaskCount: 0.
2018-07-31 05:23:43,982 INFO [pool-1-thread-1] com.microsoft.frameworklauncher.common.service.AbstractService: ], Exception = [null]
2018-07-31 05:23:43,982 INFO [pool-1-thread-1] com.microsoft.frameworklauncher.common.service.AbstractService: ________________________________________________________________________________________________________________________________________________________________________________________________________
2018-07-31 05:23:43,982 INFO [pool-1-thread-1] com.microsoft.frameworklauncher.applicationmaster.ApplicationMaster: Unregistering com.microsoft.frameworklauncher.applicationmaster.ApplicationMaster to RM
2018-07-31 05:23:44,117 INFO [pool-1-thread-1] org.apache.hadoop.yarn.client.api.impl.AMRMClientImpl: Waiting for application to be successfully unregistered.
2018-07-31 05:23:44,219 DEBUG [pool-1-thread-1] org.apache.hadoop.service.AbstractService: Service: org.apache.hadoop.yarn.client.api.async.AMRMClientAsync entered state STOPPED
2018-07-31 05:23:44,220 DEBUG [AMRM Heartbeater thread] org.apache.hadoop.yarn.client.api.async.impl.AMRMClientAsyncImpl: Heartbeater interrupted
java.lang.InterruptedException: sleep interrupted
	at java.lang.Thread.sleep(Native Method)
	at org.apache.hadoop.yarn.client.api.async.impl.AMRMClientAsyncImpl$HeartbeatThread.run(AMRMClientAsyncImpl.java:262)
2018-07-31 05:23:44,222 DEBUG [pool-1-thread-1] org.apache.hadoop.service.AbstractService: Service: org.apache.hadoop.yarn.client.api.impl.AMRMClientImpl entered state STOPPED
2018-07-31 05:23:44,222 INFO [AMRM Callback Handler Thread] org.apache.hadoop.yarn.client.api.async.impl.AMRMClientAsyncImpl: Interrupted while waiting for queue
java.lang.InterruptedException
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.reportInterruptAfterWait(AbstractQueuedSynchronizer.java:2014)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2048)
	at java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:442)
	at org.apache.hadoop.yarn.client.api.async.impl.AMRMClientAsyncImpl$CallbackHandlerThread.run(AMRMClientAsyncImpl.java:288)
2018-07-31 05:23:44,224 DEBUG [pool-1-thread-1] org.apache.curator.framework.imps.CuratorFrameworkImpl: Closing
2018-07-31 05:23:44,224 INFO [Curator-Framework-0] org.apache.curator.framework.imps.CuratorFrameworkImpl: backgroundOperationsLoop exiting
2018-07-31 05:23:44,225 DEBUG [pool-1-thread-1] org.apache.curator.CuratorZookeeperClient: Closing
2018-07-31 05:23:44,225 DEBUG [pool-1-thread-1] org.apache.curator.ConnectionState: Closing
2018-07-31 05:23:44,226 DEBUG [pool-1-thread-1] org.apache.zookeeper.ZooKeeper: Closing session: 0x164ee0d70c10007
2018-07-31 05:23:44,229 INFO [main-EventThread] org.apache.zookeeper.ClientCnxn: EventThread shut down for session: 0x164ee0d70c10007
2018-07-31 05:23:44,230 INFO [pool-1-thread-1] org.apache.zookeeper.ZooKeeper: Session: 0x164ee0d70c10007 closed
2018-07-31 05:23:44,230 INFO [pool-1-thread-1] com.microsoft.frameworklauncher.applicationmaster.ApplicationMaster: com.microsoft.frameworklauncher.applicationmaster.ApplicationMaster stopped

Log Type: AllError.log

Log Upload Time: Tue Jul 31 05:23:45 +0000 2018

Log Length: 0


Log Type: AllWarn.log

Log Upload Time: Tue Jul 31 05:23:45 +0000 2018

Log Length: 2020

2018-07-31 05:23:34,478 WARN [pool-1-thread-1] com.microsoft.frameworklauncher.applicationmaster.ApplicationMaster: [Master][0]: attemptToRetry: Will completeTask. Reason: Task exited due to SUCCEEDED.
2018-07-31 05:23:35,467 WARN [pool-1-thread-1] com.microsoft.frameworklauncher.applicationmaster.ApplicationMaster: [Master][1]: attemptToRetry: Will completeTask. Reason: Task exited due to SUCCEEDED.
2018-07-31 05:23:36,468 WARN [pool-1-thread-1] com.microsoft.frameworklauncher.applicationmaster.ApplicationMaster: [Master][2]: attemptToRetry: Will completeTask. Reason: Task exited due to SUCCEEDED.
2018-07-31 05:23:37,473 WARN [pool-1-thread-1] com.microsoft.frameworklauncher.applicationmaster.ApplicationMaster: [Master][3]: attemptToRetry: Will completeTask. Reason: Task exited due to SUCCEEDED.
2018-07-31 05:23:38,479 WARN [pool-1-thread-1] com.microsoft.frameworklauncher.applicationmaster.ApplicationMaster: [Master][4]: attemptToRetry: Will completeTask. Reason: Task exited due to SUCCEEDED.
2018-07-31 05:23:39,486 WARN [pool-1-thread-1] com.microsoft.frameworklauncher.applicationmaster.ApplicationMaster: [Master][5]: attemptToRetry: Will completeTask. Reason: Task exited due to SUCCEEDED.
2018-07-31 05:23:40,491 WARN [pool-1-thread-1] com.microsoft.frameworklauncher.applicationmaster.ApplicationMaster: [Master][6]: attemptToRetry: Will completeTask. Reason: Task exited due to SUCCEEDED.
2018-07-31 05:23:41,495 WARN [pool-1-thread-1] com.microsoft.frameworklauncher.applicationmaster.ApplicationMaster: [Master][7]: attemptToRetry: Will completeTask. Reason: Task exited due to SUCCEEDED.
2018-07-31 05:23:42,496 WARN [pool-1-thread-1] com.microsoft.frameworklauncher.applicationmaster.ApplicationMaster: [Master][8]: attemptToRetry: Will completeTask. Reason: Task exited due to SUCCEEDED.
2018-07-31 05:23:43,499 WARN [pool-1-thread-1] com.microsoft.frameworklauncher.applicationmaster.ApplicationMaster: [Master][9]: attemptToRetry: Will completeTask. Reason: Task exited due to SUCCEEDED.

Log Type: InternalDebug.log

Log Upload Time: Tue Jul 31 05:23:45 +0000 2018

Log Length: 270681

Showing 4096 bytes of 270681 total. Click here for the full log.

: [ExitDiagnostics]:
2018-07-31 05:23:43,981 INFO [pool-1-thread-1] com.microsoft.frameworklauncher.common.service.AbstractService: Succeeded
2018-07-31 05:23:43,981 INFO [pool-1-thread-1] com.microsoft.frameworklauncher.common.service.AbstractService: [ExitType]: SUCCEEDED
2018-07-31 05:23:43,981 INFO [pool-1-thread-1] com.microsoft.frameworklauncher.common.service.AbstractService: ________________________________________________________________________________________________________________________________________________________________________________________________________
2018-07-31 05:23:43,981 INFO [pool-1-thread-1] com.microsoft.frameworklauncher.common.service.AbstractService: [ExitCustomizedDiagnostics]:
2018-07-31 05:23:43,981 INFO [pool-1-thread-1] com.microsoft.frameworklauncher.common.service.AbstractService: [ApplicationCompletionReason]: All Tasks completed and no ApplicationCompletionPolicy has ever been triggered: TotalTaskCount: 10, FailedTaskCount: 0.
2018-07-31 05:23:43,981 INFO [pool-1-thread-1] com.microsoft.frameworklauncher.common.service.AbstractService: ], Exception = [null]
2018-07-31 05:23:43,981 INFO [pool-1-thread-1] com.microsoft.frameworklauncher.common.service.AbstractService: ________________________________________________________________________________________________________________________________________________________________________________________________________
2018-07-31 05:23:43,981 INFO [pool-1-thread-1] com.microsoft.frameworklauncher.common.service.AbstractService: ________________________________________________________________________________________________________________________________________________________________________________________________________
2018-07-31 05:23:43,981 INFO [pool-1-thread-1] com.microsoft.frameworklauncher.common.service.AbstractService: Stopping com.microsoft.frameworklauncher.applicationmaster.FrameworkInfoPublisher with StopStatus: code = [0], needUnregister = [true], diagnostics = [[ExitStatus]: SUCCEEDED
2018-07-31 05:23:43,981 INFO [pool-1-thread-1] com.microsoft.frameworklauncher.common.service.AbstractService: [ExitCode]: 0
2018-07-31 05:23:43,982 INFO [pool-1-thread-1] com.microsoft.frameworklauncher.common.service.AbstractService: [ExitDiagnostics]:
2018-07-31 05:23:43,982 INFO [pool-1-thread-1] com.microsoft.frameworklauncher.common.service.AbstractService: Succeeded
2018-07-31 05:23:43,982 INFO [pool-1-thread-1] com.microsoft.frameworklauncher.common.service.AbstractService: [ExitType]: SUCCEEDED
2018-07-31 05:23:43,982 INFO [pool-1-thread-1] com.microsoft.frameworklauncher.common.service.AbstractService: ________________________________________________________________________________________________________________________________________________________________________________________________________
2018-07-31 05:23:43,982 INFO [pool-1-thread-1] com.microsoft.frameworklauncher.common.service.AbstractService: [ExitCustomizedDiagnostics]:
2018-07-31 05:23:43,982 INFO [pool-1-thread-1] com.microsoft.frameworklauncher.common.service.AbstractService: [ApplicationCompletionReason]: All Tasks completed and no ApplicationCompletionPolicy has ever been triggered: TotalTaskCount: 10, FailedTaskCount: 0.
2018-07-31 05:23:43,982 INFO [pool-1-thread-1] com.microsoft.frameworklauncher.common.service.AbstractService: ], Exception = [null]
2018-07-31 05:23:43,982 INFO [pool-1-thread-1] com.microsoft.frameworklauncher.common.service.AbstractService: ________________________________________________________________________________________________________________________________________________________________________________________________________
2018-07-31 05:23:43,982 INFO [pool-1-thread-1] com.microsoft.frameworklauncher.applicationmaster.ApplicationMaster: Unregistering com.microsoft.frameworklauncher.applicationmaster.ApplicationMaster to RM
2018-07-31 05:23:44,230 INFO [pool-1-thread-1] com.microsoft.frameworklauncher.applicationmaster.ApplicationMaster: com.microsoft.frameworklauncher.applicationmaster.ApplicationMaster stopped

Log Type: InternalInfo.log

Log Upload Time: Tue Jul 31 05:23:45 +0000 2018

Log Length: 181066

Showing 4096 bytes of 181066 total. Click here for the full log.

: [ExitDiagnostics]:
2018-07-31 05:23:43,981 INFO [pool-1-thread-1] com.microsoft.frameworklauncher.common.service.AbstractService: Succeeded
2018-07-31 05:23:43,981 INFO [pool-1-thread-1] com.microsoft.frameworklauncher.common.service.AbstractService: [ExitType]: SUCCEEDED
2018-07-31 05:23:43,981 INFO [pool-1-thread-1] com.microsoft.frameworklauncher.common.service.AbstractService: ________________________________________________________________________________________________________________________________________________________________________________________________________
2018-07-31 05:23:43,981 INFO [pool-1-thread-1] com.microsoft.frameworklauncher.common.service.AbstractService: [ExitCustomizedDiagnostics]:
2018-07-31 05:23:43,981 INFO [pool-1-thread-1] com.microsoft.frameworklauncher.common.service.AbstractService: [ApplicationCompletionReason]: All Tasks completed and no ApplicationCompletionPolicy has ever been triggered: TotalTaskCount: 10, FailedTaskCount: 0.
2018-07-31 05:23:43,981 INFO [pool-1-thread-1] com.microsoft.frameworklauncher.common.service.AbstractService: ], Exception = [null]
2018-07-31 05:23:43,981 INFO [pool-1-thread-1] com.microsoft.frameworklauncher.common.service.AbstractService: ________________________________________________________________________________________________________________________________________________________________________________________________________
2018-07-31 05:23:43,981 INFO [pool-1-thread-1] com.microsoft.frameworklauncher.common.service.AbstractService: ________________________________________________________________________________________________________________________________________________________________________________________________________
2018-07-31 05:23:43,981 INFO [pool-1-thread-1] com.microsoft.frameworklauncher.common.service.AbstractService: Stopping com.microsoft.frameworklauncher.applicationmaster.FrameworkInfoPublisher with StopStatus: code = [0], needUnregister = [true], diagnostics = [[ExitStatus]: SUCCEEDED
2018-07-31 05:23:43,981 INFO [pool-1-thread-1] com.microsoft.frameworklauncher.common.service.AbstractService: [ExitCode]: 0
2018-07-31 05:23:43,982 INFO [pool-1-thread-1] com.microsoft.frameworklauncher.common.service.AbstractService: [ExitDiagnostics]:
2018-07-31 05:23:43,982 INFO [pool-1-thread-1] com.microsoft.frameworklauncher.common.service.AbstractService: Succeeded
2018-07-31 05:23:43,982 INFO [pool-1-thread-1] com.microsoft.frameworklauncher.common.service.AbstractService: [ExitType]: SUCCEEDED
2018-07-31 05:23:43,982 INFO [pool-1-thread-1] com.microsoft.frameworklauncher.common.service.AbstractService: ________________________________________________________________________________________________________________________________________________________________________________________________________
2018-07-31 05:23:43,982 INFO [pool-1-thread-1] com.microsoft.frameworklauncher.common.service.AbstractService: [ExitCustomizedDiagnostics]:
2018-07-31 05:23:43,982 INFO [pool-1-thread-1] com.microsoft.frameworklauncher.common.service.AbstractService: [ApplicationCompletionReason]: All Tasks completed and no ApplicationCompletionPolicy has ever been triggered: TotalTaskCount: 10, FailedTaskCount: 0.
2018-07-31 05:23:43,982 INFO [pool-1-thread-1] com.microsoft.frameworklauncher.common.service.AbstractService: ], Exception = [null]
2018-07-31 05:23:43,982 INFO [pool-1-thread-1] com.microsoft.frameworklauncher.common.service.AbstractService: ________________________________________________________________________________________________________________________________________________________________________________________________________
2018-07-31 05:23:43,982 INFO [pool-1-thread-1] com.microsoft.frameworklauncher.applicationmaster.ApplicationMaster: Unregistering com.microsoft.frameworklauncher.applicationmaster.ApplicationMaster to RM
2018-07-31 05:23:44,230 INFO [pool-1-thread-1] com.microsoft.frameworklauncher.applicationmaster.ApplicationMaster: com.microsoft.frameworklauncher.applicationmaster.ApplicationMaster stopped

Log Type: stderr

Log Upload Time: Tue Jul 31 05:23:45 +0000 2018

Log Length: 585

SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/var/lib/hadoopdata/nm-local-dir/usercache/test/appcache/application_1533003895110_0040/filecache/10/frameworklauncher-1.0-SNAPSHOT-jar-with-dependencies.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/usr/local/hadoop-2.7.2/share/hadoop/common/lib/slf4j-log4j12-1.7.10.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
SLF4J: Actual binding is of type [org.slf4j.impl.Log4jLoggerFactory]

Log Type: stdout

Log Upload Time: Tue Jul 31 05:23:45 +0000 2018

Log Length: 181066

Showing 4096 bytes of 181066 total. Click here for the full log.

: [ExitDiagnostics]:
2018-07-31 05:23:43,981 INFO [pool-1-thread-1] com.microsoft.frameworklauncher.common.service.AbstractService: Succeeded
2018-07-31 05:23:43,981 INFO [pool-1-thread-1] com.microsoft.frameworklauncher.common.service.AbstractService: [ExitType]: SUCCEEDED
2018-07-31 05:23:43,981 INFO [pool-1-thread-1] com.microsoft.frameworklauncher.common.service.AbstractService: ________________________________________________________________________________________________________________________________________________________________________________________________________
2018-07-31 05:23:43,981 INFO [pool-1-thread-1] com.microsoft.frameworklauncher.common.service.AbstractService: [ExitCustomizedDiagnostics]:
2018-07-31 05:23:43,981 INFO [pool-1-thread-1] com.microsoft.frameworklauncher.common.service.AbstractService: [ApplicationCompletionReason]: All Tasks completed and no ApplicationCompletionPolicy has ever been triggered: TotalTaskCount: 10, FailedTaskCount: 0.
2018-07-31 05:23:43,981 INFO [pool-1-thread-1] com.microsoft.frameworklauncher.common.service.AbstractService: ], Exception = [null]
2018-07-31 05:23:43,981 INFO [pool-1-thread-1] com.microsoft.frameworklauncher.common.service.AbstractService: ________________________________________________________________________________________________________________________________________________________________________________________________________
2018-07-31 05:23:43,981 INFO [pool-1-thread-1] com.microsoft.frameworklauncher.common.service.AbstractService: ________________________________________________________________________________________________________________________________________________________________________________________________________
2018-07-31 05:23:43,981 INFO [pool-1-thread-1] com.microsoft.frameworklauncher.common.service.AbstractService: Stopping com.microsoft.frameworklauncher.applicationmaster.FrameworkInfoPublisher with StopStatus: code = [0], needUnregister = [true], diagnostics = [[ExitStatus]: SUCCEEDED
2018-07-31 05:23:43,981 INFO [pool-1-thread-1] com.microsoft.frameworklauncher.common.service.AbstractService: [ExitCode]: 0
2018-07-31 05:23:43,982 INFO [pool-1-thread-1] com.microsoft.frameworklauncher.common.service.AbstractService: [ExitDiagnostics]:
2018-07-31 05:23:43,982 INFO [pool-1-thread-1] com.microsoft.frameworklauncher.common.service.AbstractService: Succeeded
2018-07-31 05:23:43,982 INFO [pool-1-thread-1] com.microsoft.frameworklauncher.common.service.AbstractService: [ExitType]: SUCCEEDED
2018-07-31 05:23:43,982 INFO [pool-1-thread-1] com.microsoft.frameworklauncher.common.service.AbstractService: ________________________________________________________________________________________________________________________________________________________________________________________________________
2018-07-31 05:23:43,982 INFO [pool-1-thread-1] com.microsoft.frameworklauncher.common.service.AbstractService: [ExitCustomizedDiagnostics]:
2018-07-31 05:23:43,982 INFO [pool-1-thread-1] com.microsoft.frameworklauncher.common.service.AbstractService: [ApplicationCompletionReason]: All Tasks completed and no ApplicationCompletionPolicy has ever been triggered: TotalTaskCount: 10, FailedTaskCount: 0.
2018-07-31 05:23:43,982 INFO [pool-1-thread-1] com.microsoft.frameworklauncher.common.service.AbstractService: ], Exception = [null]
2018-07-31 05:23:43,982 INFO [pool-1-thread-1] com.microsoft.frameworklauncher.common.service.AbstractService: ________________________________________________________________________________________________________________________________________________________________________________________________________
2018-07-31 05:23:43,982 INFO [pool-1-thread-1] com.microsoft.frameworklauncher.applicationmaster.ApplicationMaster: Unregistering com.microsoft.frameworklauncher.applicationmaster.ApplicationMaster to RM
2018-07-31 05:23:44,230 INFO [pool-1-thread-1] com.microsoft.frameworklauncher.applicationmaster.ApplicationMaster: com.microsoft.frameworklauncher.applicationmaster.ApplicationMaster stopped
```

**Comment by lifubang** [comment]
The same tasks will be add every 10 minutes.

**Comment by yqwang-ms** [comment]
These failed jobs (user=dr.who, name = hadoop, applicationtype = YARN) seems unmanaged by PAI, PAI only submits Launcher type jobs (applicationtype = LAUNCHER).

Could you please click into these failed job and provide below info?

Such as:
![Uploading image.png…]()

![image](https://user-images.githubusercontent.com/32826762/43510840-7152d2f4-95a9-11e8-9921-b6c22fc24b8d.png)

Or provide
http://{YARN_RM_ADDR}/ws/v1/cluster/apps/{failed job app id}

**Comment by lifubang** [comment]
@yqwang-ms 
![ub bfe9l 4i 9_g6vvfs4 4](https://user-images.githubusercontent.com/783424/43620424-28d33f52-9705-11e8-9447-42ec128c587e.png)

While click Log:
No logs available for container container_1533003895110_1706_01_000001

**Comment by yqwang-ms** [comment]
It seems not PAI internal jobs or jobs submitted by you, maybe someone hacked your hadoop without through PAI portal.

**Comment by YanjieGao** [comment]
could you attach the logs of the job which could get details of the job?

**Comment by YanjieGao** [comment]
you could try to use linux command to monitor yarn receive job submit port's network connection. Then identify which server's port/process/connection raise this job submission.

**Comment by fanyangCS** [comment]
no further info. closed
