### ISSUE TITLE
Looping on "Waiting for ssh service in other containers"

### ISSUE THREAD

**Issue by hao1939** [Microsoft/pai#1053]
Please check this job: http://10.151.40.234/view.html?jobName=spark-python-example-010

**Comment by yqwang-ms** [comment]
@Gerhut to take a look 

http://10.151.40.234/yarn/10.151.40.233:8042/node/containerlogs/container_e05_1532923417681_1090_01_000002/core/stdout/?start=-4096

[INFO] Waiting for ssh service in other containers ...
Exception in thread "main" java.lang.RuntimeException: core-site.xml not found
	at org.apache.hadoop.conf.Configuration.loadResource(Configuration.java:2566)
	at org.apache.hadoop.conf.Configuration.loadResources(Configuration.java:2492)
	at org.apache.hadoop.conf.Configuration.getProps(Configuration.java:2405)
	at org.apache.hadoop.conf.Configuration.set(Configuration.java:1143)
	at org.apache.hadoop.conf.Configuration.set(Configuration.java:1115)
	at org.apache.hadoop.conf.Configuration.setBoolean(Configuration.java:1451)
	at org.apache.hadoop.util.GenericOptionsParser.processGeneralOptions(GenericOptionsParser.java:321)
	at org.apache.hadoop.util.GenericOptionsParser.parseGeneralOptions(GenericOptionsParser.java:487)
	at org.apache.hadoop.util.GenericOptionsParser.<init>(GenericOptionsParser.java:170)
	at org.apache.hadoop.util.GenericOptionsParser.<init>(GenericOptionsParser.java:153)
	at org.apache.hadoop.util.ToolRunner.run(ToolRunner.java:64)
	at org.apache.hadoop.util.ToolRunner.run(ToolRunner.java:84)
	at org.apache.hadoop.fs.FsShell.main(FsShell.java:340)

**Comment by hao1939** [comment]
The directly cause is node manage config malformed.
It turns fine after `paictl.py service refresh -n hadoop-node-manager`, `paictl.py service stop -n hadoop-node-manager`, `paictl.py service start -n hadoop-node-manager`.

And @Gerhut , would you review the code below again. What about break the loop after retry count down?

```sh
while [ `hdfs dfs -ls $ssh_config_path | grep "/$PAI_JOB_NAME/ssh/config/$APP_ID+" | wc -l` -lt  $PAI_JOB_TASK_COUNT ]; do
  printf "%s %s\n" "[INFO]" "Waiting for ssh service in other containers ..."
  sleep 10
done
```

**Comment by Gerhut** [comment]
This is because `hdfs` command runs failed every time because of lacking of hadoop configuration.

To solve this, adding `pipefail` flag to shell works, but a full check of the whole shell script is necessary after `pipefail` is enabled.
