### ISSUE TITLE
node exporter failed

### ISSUE THREAD

**Issue by shawntian90** [Microsoft/pai#1095]
Hi,

When node exporter container launched, the [healthy_check.py](https://github.com/Microsoft/pai/blob/master/prometheus/exporter/healthy_check.py) will failed when it was running on a `Master` node, which has NVIDIA GPU card. 

This GPU is not configured to used by pai cluster, also not configured in `/cluster-configuration/cluster-configuration.yaml`.

It failed my because the NVIDIA driver is not properly installed or the driver version is not `384.111`.

I'd like to help get out of this bug via PR, which may fixed by check this server is GPU node or CPU node. But I do not find a good way to fix it.

Pls help!

**Comment by YitongFeng** [comment]
Hi, Shawn, could you please provide the node-exporter's error log and your cluster-configuration?

**Comment by shawntian90** [comment]
## cluster-configuration
In the following settings, the node `master-node` has one NVIDIA GPU card, which won't be used in openpai cluster.

```
default-machine-properties:
  # Account with root permission
  username: ****
  password: ****
  sshport: ****


machine-sku:

  WORKER:
    mem: 128
    gpu:
      type: geforcegtxtitanx
      count: 8
    cpu:
      vcore: 32
    dataFolder: "/data"
    #Note: Up to now, the only supported os version is Ubuntu16.04. Please do not change it here.
    os: ubuntu16.04

  CPUNODE:
    mem: 16
    cpu:
      vcore: 16
    dataFolder: "/data"
    #Note: Up to now, the only supported os version is Ubuntu16.04. Pls don't change it here.
    os: ubuntu16.04



machine-list:

    - hostname: master-node
      hostip: IP
      machine-type: CPUNODE
      etcdid: etcdid1
      k8s-role: master
      dashboard: "true"
      zkid: "1"
      pai-master: "true"
      watchdog: "true"
      alert-manager: "true"


    - hostname: worker-node
      hostip: IP
      machine-type: WORKER
      k8s-role: worker
      pai-worker: "true"
```

**Comment by shawntian90** [comment]
## node-exporter error log

```
Readiness probe failed: /bin/sh: 1: nvidia-smi: not found Traceback (most recent call last): File "/usr/local/healthy_check.py", line 88, in <module> main() File "/usr/local/healthy_check.py", line 85, in main raise RuntimeError("gpu-exporter readiness probe failed, error component:" + exception) RuntimeError: gpu-exporter readiness probe failed, error component:| nvidiasmi
```

**Comment by xudifsd** [comment]
@shawntian90 Hi, Shawn. It's exporter's bug not respecting configuration. As you can see from [driver's start script](https://github.com/Microsoft/pai/blob/master/pai-management/bootstrap/drivers/node-label.sh.template). Driver will only be installed on nodes configured with gpu. Whereas the exporter needs to be installed on every node to collect machine & job's info to do alerting. But neither exporter itself nor its health check respect this configuration. You can see the logic from [here](https://github.com/Microsoft/pai/blob/master/prometheus/exporter/healthy_check.py#L43), it will check if the node has gpu, and if the node has it will invoke `nvidia-smi` directly without consulting configuration nor checking it's existence.

If you want to help, maybe you can modify code in `prometheus/exporter/healthy_check.py` and `prometheus/exporter/gpu_exporter.py` by checking if `nvidia-smi` exist, and only invoke it if exist.

This modification will make exporter replay on driver to respect configuration.

**Comment by shawntian90** [comment]
#1117
