### ISSUE TITLE
delete zookeeper failed

### ISSUE THREAD

**Issue by xudifsd** [Microsoft/pai#1102]
executing `./paictl.py service delete -p /cluster-configuration/ -n zookeeper` will prompt with error message:

```
2018-08-20 05:48:33,613 [INFO] - paiLibrary.paiService.service_delete : Begin to execute service zookeeper's delete script.
Call stop to stop all hadoop service first
label "zookeeper" not found.
node/10.151.40.234 not labeled
Create hadoop-delete configmap for deleting data on the host
configmap/zookeeper-delete configured
Create cleaner daemon
daemonset.apps/delete-batch-job-zookeeper unchanged
/usr/local/lib/python2.7/dist-packages/requests/__init__.py:91: RequestsDependencyWarning: urllib3 (1.13.1) or chardet (3.0.4) doesn't match a supported version!
  RequestsDependencyWarning)
/usr/local/lib/python2.7/dist-packages/requests/__init__.py:83: RequestsDependencyWarning: Old version of cryptography ([1, 2, 3]) may cause slowdown.
  warnings.warn(warning, RequestsDependencyWarning)
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/pai/pai-management/k8sPaiLibrary/monitorTool/check_pod_ready_status.py", line 24, in <module>
    from ..monitorlib import servicestatus
  File "/pai/pai-management/k8sPaiLibrary/monitorlib/servicestatus.py", line 21, in <module>
    from kubernetes import client, config
  File "/usr/local/lib/python2.7/dist-packages/kubernetes/__init__.py", line 20, in <module>
    import kubernetes.config
  File "/usr/local/lib/python2.7/dist-packages/kubernetes/config/__init__.py", line 17, in <module>
    from .kube_config import (list_kube_config_contexts, load_kube_config,
  File "/usr/local/lib/python2.7/dist-packages/kubernetes/config/kube_config.py", line 23, in <module>
    import google.auth.transport.requests
  File "/usr/local/lib/python2.7/dist-packages/google/auth/transport/requests.py", line 31, in <module>
    caught_exc,
  File "/usr/lib/python2.7/dist-packages/six.py", line 718, in raise_from
    raise value
ImportError: The requests library is not installed, please install the requests package to use the requests transport.
```

**Comment by xudifsd** [comment]
`./paictl.py service delete -p /cluster-configuration/ -n prometheus` also showed this error:

```
Create prometheus-delete configmap for deleting data on the host
configmap/prometheus-delete created
Create cleaner daemon
daemonset.apps/delete-batch-job-prometheus created
/usr/local/lib/python2.7/dist-packages/requests/__init__.py:91: RequestsDependencyWarning: urllib3 (1.13.1) or chardet (3.0.4) doesn't match a supported version!
  RequestsDependencyWarning)
/usr/local/lib/python2.7/dist-packages/requests/__init__.py:83: RequestsDependencyWarning: Old version of cryptography ([1, 2, 3]) may cause slowdown.
  warnings.warn(warning, RequestsDependencyWarning)
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/pai/pai-management/k8sPaiLibrary/monitorTool/check_pod_ready_status.py", line 24, in <module>
    from ..monitorlib import servicestatus
  File "/pai/pai-management/k8sPaiLibrary/monitorlib/servicestatus.py", line 21, in <module>
    from kubernetes import client, config
  File "/usr/local/lib/python2.7/dist-packages/kubernetes/__init__.py", line 20, in <module>
    import kubernetes.config
  File "/usr/local/lib/python2.7/dist-packages/kubernetes/config/__init__.py", line 17, in <module>
    from .kube_config import (list_kube_config_contexts, load_kube_config,
  File "/usr/local/lib/python2.7/dist-packages/kubernetes/config/kube_config.py", line 23, in <module>
    import google.auth.transport.requests
  File "/usr/local/lib/python2.7/dist-packages/google/auth/transport/requests.py", line 31, in <module>
    caught_exc,
  File "/usr/lib/python2.7/dist-packages/six.py", line 718, in raise_from
    raise value
ImportError: The requests library is not installed, please install the requests package to use the requests transport.
```

**Comment by xudifsd** [comment]
it seems this is due to `cleaning-image` not installed requests library
