### ISSUE TITLE
hadoop-data-node keeps restarting because: `java.net.BindException: Problem binding to [0.0.0.0:50010]`

### ISSUE THREAD

**Issue by hao1939** [Microsoft/pai#1233]
1. hadoop-data-node takes obviously long run usual.
![image](https://user-images.githubusercontent.com/1547343/44894574-00949c00-ad23-11e8-8360-6f4fa78ac3d5.png)

2. It retried several times but can't succeed.
3. Check the pod log, found `Problem binding to [0.0.0.0:50010] java.net.BindException: Address already in use`.
```
...
java.net.BindException: Problem binding to [0.0.0.0:50010] java.net.BindException: Address already in use; For more details see:  http://wiki.apache.org/hadoop/BindException
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
        at org.apache.hadoop.net.NetUtils.wrapWithMessage(NetUtils.java:824)
        at org.apache.hadoop.net.NetUtils.wrapException(NetUtils.java:735)
        at org.apache.hadoop.ipc.Server.bind(Server.java:561)
        at org.apache.hadoop.ipc.Server.bind(Server.java:533)
        at org.apache.hadoop.hdfs.net.TcpPeerServer.<init>(TcpPeerServer.java:52)
        at org.apache.hadoop.hdfs.server.datanode.DataNode.initDataXceiver(DataNode.java:1117)
        at org.apache.hadoop.hdfs.server.datanode.DataNode.startDataNode(DataNode.java:1369)
        at org.apache.hadoop.hdfs.server.datanode.DataNode.<init>(DataNode.java:495)
        at org.apache.hadoop.hdfs.server.datanode.DataNode.makeInstance(DataNode.java:2695)
        at org.apache.hadoop.hdfs.server.datanode.DataNode.instantiateDataNode(DataNode.java:2598)
        at org.apache.hadoop.hdfs.server.datanode.DataNode.createDataNode(DataNode.java:2645)
        at org.apache.hadoop.hdfs.server.datanode.DataNode.secureMain(DataNode.java:2789)
        at org.apache.hadoop.hdfs.server.datanode.DataNode.main(DataNode.java:2813)
Caused by: java.net.BindException: Address already in use
        at sun.nio.ch.Net.bind0(Native Method)
        at sun.nio.ch.Net.bind(Net.java:433)
        at sun.nio.ch.Net.bind(Net.java:425)
        at sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:223)
        at sun.nio.ch.ServerSocketAdaptor.bind(ServerSocketAdaptor.java:74)
        at org.apache.hadoop.ipc.Server.bind(Server.java:544)
        ... 10 more
18/08/31 05:34:24 INFO util.ExitUtil: Exiting with status 1: java.net.BindException: Problem binding to [0.0.0.0:50010] java.net.BindException: Address already in use; For more details see:  http://wiki.apache.org/hadoop/BindException
18/08/31 05:34:24 INFO datanode.DataNode: SHUTDOWN_MSG:
/************************************************************
SHUTDOWN_MSG: Shutting down DataNode at localhost/127.0.0.1
************************************************************/
```

**Comment by hao1939** [comment]
Similar like #1160 .

**Comment by fanyangCS** [comment]
And similar to https://github.com/Microsoft/pai/issues/113

**Comment by DongZhaoYu** [comment]
https://github.com/Microsoft/pai/pull/1337

**Comment by DongZhaoYu** [comment]
the HDFS ports are changed in https://github.com/Microsoft/pai/pull/1337 to avoid conflicts.

**Comment by SushantGautam** [comment]
Do you have Hyper V enabled? check : https://github.com/googlevr/gvr-unity-sdk/issues/1002
