### ISSUE TITLE
[AKS] server paramiko ssh issue

### ISSUE THREAD

**Issue by YanjieGao** [Microsoft/pai#1297]
## Problem: 

Last time deployment not meet this issue.

env:
- deployment at dev-box

- AKS shell ssh between servers could work.

- use Standard D8s v3 (8 vcpus, 32 GB memory) server. 

This time deploy AKS meet this issue at first generate config step:

root@aks-agentpool-25033075-0:~/pai/pai-management# python paictl.py cluster generate-configuration -i quick-start/quick-start-example.yaml -o ~/pai-config -f
2018-09-07 03:33:12,649 [INFO] - paramiko.transport : Connected (version 2.0, client OpenSSH_7.2p2)
2018-09-07 03:33:12,651 [ERROR] - paramiko.transport : Exception: Incompatible ssh peer (no acceptable kex algorithm)
2018-09-07 03:33:12,652 [ERROR] - paramiko.transport : Traceback (most recent call last):
2018-09-07 03:33:12,652 [ERROR] - paramiko.transport :   File "/usr/lib/python2.7/dist-packages/paramiko/transport.py", line 1790, in run
2018-09-07 03:33:12,652 [ERROR] - paramiko.transport :     self._handler_table[ptype](self, m)
2018-09-07 03:33:12,652 [ERROR] - paramiko.transport :   File "/usr/lib/python2.7/dist-packages/paramiko/transport.py", line 1883, in _negotiate_keys
2018-09-07 03:33:12,653 [ERROR] - paramiko.transport :     self._parse_kex_init(m)
2018-09-07 03:33:12,653 [ERROR] - paramiko.transport :   File "/usr/lib/python2.7/dist-packages/paramiko/transport.py", line 2009, in _parse_kex_init
2018-09-07 03:33:12,653 [ERROR] - paramiko.transport :     raise SSHException('Incompatible ssh peer (no acceptable kex algorithm)')
2018-09-07 03:33:12,653 [ERROR] - paramiko.transport : SSHException: Incompatible ssh peer (no acceptable kex algorithm)
2018-09-07 03:33:12,653 [ERROR] - paramiko.transport :
Traceback (most recent call last):
  File "paictl.py", line 623, in <module>
    main()
  File "paictl.py", line 612, in main
    pai_cluster()
  File "paictl.py", line 527, in pai_cluster
    args.force)
  File "/root/pai/pai-management/paiLibrary/paiCluster/cluster_util.py", line 80, in generate_configuration
    "cat /etc/resolv.conf | grep nameserver | cut -d ' ' -f 2 | head -n 1")
  File "/root/pai/pai-management/k8sPaiLibrary/maintainlib/common.py", line 205, in ssh_shell_paramiko_with_result
    ssh.connect(hostname=hostip, port=port, username=username, password=password)
  File "/usr/lib/python2.7/dist-packages/paramiko/client.py", line 325, in connect
    t.start_client()
  File "/usr/lib/python2.7/dist-packages/paramiko/transport.py", line 493, in start_client
    raise e
paramiko.ssh_exception.SSHException: Incompatible ssh peer (no acceptable kex algorithm)

## Dependency:
dev-box & paictl.py

## Reference Solution & Plan:
refer branch yanjga/aks-test

- solution 1: replace with shell ssh cmd to execute ssh related cmd
https://github.com/Microsoft/pai/blob/f2b3d9006697588f00b688494cc90bdb749d105a/pai-management/k8sPaiLibrary/maintainlib/common.py
- solution 2: combine ssh part only in deploy k8s part, and other part didn't need this
- solution 3: other solution

## Dev plan
- yanjie will create a pai/aks branch as master branch for receive all aks related pr. https://github.com/Microsoft/pai/tree/pai/aks
- some knowledge could refer yanjga/aks-test driver related change
- feature dev folk & submit pr to pai/aks branch
- If all tests passed, then cherry pick pai/aks pr to master branch.

**Comment by YanjieGao** [comment]
i try some method will meet new issues;

upgrade paramiko will meet new issue

**Comment by YanjieGao** [comment]
Solution:

update server side /etc/ssh/sshd_config

As a quick fix, the following Cipher/MACs/KexAlgorithms settings on the server side fixes the issue:

In /etc/ssh/sshd_config:

Reference: 

Ciphers aes256-gcm@openssh.com,aes128-gcm@openssh.com,aes256-ctr,aes128-ctr
MACs hmac-sha2-512-etm@openssh.com,hmac-sha2-256-etm@openssh.com,umac-128-etm@openssh.com,hmac-sha2-512,hmac-sha2-256,hmac-ripemd160,hmac-sha1
KexAlgorithms diffie-hellman-group-exchange-sha256,diffie-hellman-group14-sha1,diffie-hellman-group-exchange-sha1
Though... you should analyze those settings from the security point of view. I set it in lab env, so didn't take care about it.


Ref: https://stackoverflow.com/questions/7286929/paramiko-incompatible-ssh-peer-no-acceptable-kex-algorithm

**Comment by xudifsd** [comment]
From [issue](https://github.com/paramiko/paramiko/issues/1329) in paramiko, it seems the only default kex algorithm is still in draft status, it was supported by openssh and libssh but not by paramiko. So to work around with this, should ssh into each node in AKS, change according to what @YanjieGao proposed, and do `sudo service sshd restart`.

**Comment by YanjieGao** [comment]
Potential solution for this issue:
Method1: remove paramiko call from deployment PAI on existing K8s (eq: remove k8s deployment steps). So paramiko call only in k8s deployment. 
Potential issue: 
- For get node hostname requirement, we could use kubectl get nodes to replace it?

Method2: replace paramiko call to shell ssh call.
Potential issue: paramiko call related code needs to affect. need some work to change and test that. 
https://github.com/Microsoft/pai/search?q=paramiko&unscoped_q=paramiko

Method3: keep use paramiko and fix the version issue. [not recommend]
Try many methods above, only hands on config server side kex algo of ssh work (auto scripts seems no permission).

**Comment by YanjieGao** [comment]
record related ssh call during deployment:
Step 2. Generate OpenPAI configuration files
get hostname
https://github.com/Microsoft/pai/blob/3f7190dd185c75ca42a38a03a3c9def172798106/deployment/paiLibrary/paiCluster/cluster_util.py#L102
get dns
https://github.com/Microsoft/pai/blob/3f7190dd185c75ca42a38a03a3c9def172798106/deployment/paiLibrary/paiCluster/cluster_util.py#L89
