### ISSUE TITLE
about job failed

### ISSUE THREAD

**Issue by boozyguo** [Microsoft/pai#1350]
hello, I have depoly PAI of version 0.7.1, and launcher-test runs succeeded.
Then, I try to submit myself job, but it fails. 
The job's josn file as below:
{
  "jobName": "test-tensorflow-test-0913",
  "image": "aiotplatform/test",
  "authFile": "",
  "dataDir": "",
  "outputDir": "",
  "codeDir": "",
  "virtualCluster": "default",
  "gpuType": "",
  "retryCount": 0,
  "taskRoles": [
    {
      "name": "aiotplatform_tf_test",
      "taskNumber": 1,
      "cpuNumber": 1,
      "memoryMB": 8192,
      "gpuNumber": 0,
      "command": "/bin/server",
      "portList": []
    }
  ]
}

And the Application Summary is:
Start Time: 2018/9/13 上午9:24:00

Finish Time: 2018/9/13 上午9:24:56

Exit Diagnostics:

[ExitStatus]: LAUNCHER_EXIT_STATUS_UNDEFINED
[ExitCode]: 177
[ExitDiagnostics]:
ExitStatus undefined in Launcher, maybe UserApplication itself failed.
[ExitType]: UNKNOWN
________________________________________________________________________________________________________________________________________________________________________________________________________
[ExitCustomizedDiagnostics]:
[ExitCode]: 127
[ExitDiagnostics]:
[2018-09-13 01:24:37.488]Exception from container-launch.
Container id: container_e11_1536637490555_0174_01_000002
Exit code: 127
[2018-09-13 01:24:37.488]
[2018-09-13 01:24:37.489]Container exited with a non-zero exit code 127. Error file: prelaunch.err.
Last 4096 bytes of prelaunch.err :
Last 4096 bytes of stderr :
% Total % Received % Xferd Average Speed Time Time Time Current
Dload Upload Total Spent Left Speed
0 0 0 0 0 0 0 0 --:--:-- --:--:-- --:--:-- 0 0 0 0 0 0 0 0 0 --:--:-- --:--:-- --:--:-- 0
100 4731 100 4731 0 0 641k 0 --:--:-- --:--:-- --:--:-- 641k
% Total % Received % Xferd Average Speed Time Time Time Current
Dload Upload Total Spent Left Speed
0 0 0 0 0 0 0 0 --:--:-- --:--:-- --:--:-- 0 0 0 0 0 0 0 0 0 --:--:-- --:--:-- --:--:-- 0
100 6975 100 6975 0 0 765k 0 --:--:-- --:--:-- --:--:-- 765k
WARNING: Your kernel does not support swap limit capabilities or the cgroup is not mounted. Memory limited without swap.
docker: Error response from daemon: oci runtime error: container_linux.go:247: starting container process caused "exec: \"/bin/bash\": stat /bin/bash: no such file or directory".

[2018-09-13 01:24:37.490]
[2018-09-13 01:24:37.490]Container exited with a non-zero exit code 127. Error file: prelaunch.err.
Last 4096 bytes of prelaunch.err :
Last 4096 bytes of stderr :
% Total % Received % Xferd Average Speed Time Time Time Current
Dload Upload Total Spent Left Speed
0 0 0 0 0 0 0 0 --:--:-- --:--:-- --:--:-- 0 0 0 0 0 0 0 0 0 --:--:-- --:--:-- --:--:-- 0
100 4731 100 4731 0 0 641k 0 --:--:-- --:--:-- --:--:-- 641k
% Total % Received % Xferd Average Speed Time Time Time Current
Dload Upload Total Spent Left Speed
0 0 0 0 0 0 0 0 --:--:-- --:--:-- --:--:-- 0 0 0 0 0 0 0 0 0 --:--:-- --:--:-- --:--:-- 0
100 6975 100 6975 0 0 765k 0 --:--:-- --:--:-- --:--:-- 765k
WARNING: Your kernel does not support swap limit capabilities or the cgroup is not mounted. Memory limited without swap.
docker: Error response from daemon: oci runtime error: container_linux.go:247: starting container process caused "exec: \"/bin/bash\": stat /bin/bash: no such file or directory".

[2018-09-13 01:24:37.490]

________________________________________________________________________________________________________________________________________________________________________________________________________
[ExitCustomizedDiagnostics]:

[aiotplatform_tf_test]: [LastCompletedTask]: [TaskStatus]:
{
"taskIndex" : 0,
"taskRoleName" : "aiotplatform_tf_test",
"taskState" : "TASK_COMPLETED",
"taskRetryPolicyState" : {
"retriedCount" : 0,
"succeededRetriedCount" : 0,
"transientNormalRetriedCount" : 0,
"transientConflictRetriedCount" : 0,
"nonTransientRetriedCount" : 0,
"unKnownRetriedCount" : 0
},
"taskCreatedTimestamp" : 1536801843983,
"taskCompletedTimestamp" : 1536801877722,
"taskServiceStatus" : {
"serviceVersion" : 0
},
"containerId" : "container_e11_1536637490555_0174_01_000002",
"containerHost" : "192.168.1.191",
"containerIp" : "192.168.1.191",
"containerPorts" : "http:27015;ssh:27016;",
"containerGpus" : 0,
"containerLogHttpAddress" : "http://192.168.1.191:8042/node/containerlogs/container_e11_1536637490555_0174_01_000002/admin/",
"containerConnectionLostCount" : 0,
"containerIsDecommissioning" : null,
"containerLaunchedTimestamp" : 1536801845751,
"containerCompletedTimestamp" : 1536801877717,
"containerExitCode" : 127,
"containerExitDiagnostics" : "[2018-09-13 01:24:37.488]Exception from container-launch.\nContainer id: container_e11_1536637490555_0174_01_000002\nExit code: 127\n[2018-09-13 01:24:37.488]\n[2018-09-13 01:24:37.489]Container exited with a non-zero exit code 127. Error file: prelaunch.err.\nLast 4096 bytes of prelaunch.err :\nLast 4096 bytes of stderr :\n % Total % Received % Xferd Average Speed Time Time Time Current\n Dload Upload Total Spent Left Speed\n\r 0 0 0 0 0 0 0 0 --:--:-- --:--:-- --:--:-- 0\r 0 0 0 0 0 0 0 0 --:--:-- --:--:-- --:--:-- 0\n\r100 4731 100 4731 0 0 641k 0 --:--:-- --:--:-- --:--:-- 641k\n % Total % Received % Xferd Average Speed Time Time Time Current\n Dload Upload Total Spent Left Speed\n\r 0 0 0 0 0 0 0 0 --:--:-- --:--:-- --:--:-- 0\r 0 0 0 0 0 0 0 0 --:--:-- --:--:-- --:--:-- 0\n\r100 6975 100 6975 0 0 765k 0 --:--:-- --:--:-- --:--:-- 765k\nWARNING: Your kernel does not support swap limit capabilities or the cgroup is not mounted. Memory limited without swap.\ndocker: Error response from daemon: oci runtime error: container_linux.go:247: starting container process caused \"exec: \\\"/bin/bash\\\": stat /bin/bash: no such file or directory\".\n\n[2018-09-13 01:24:37.490]\n[2018-09-13 01:24:37.490]Container exited with a non-zero exit code 127. Error file: prelaunch.err.\nLast 4096 bytes of prelaunch.err :\nLast 4096 bytes of stderr :\n % Total % Received % Xferd Average Speed Time Time Time Current\n Dload Upload Total Spent Left Speed\n\r 0 0 0 0 0 0 0 0 --:--:-- --:--:-- --:--:-- 0\r 0 0 0 0 0 0 0 0 --:--:-- --:--:-- --:--:-- 0\n\r100 4731 100 4731 0 0 641k 0 --:--:-- --:--:-- --:--:-- 641k\n % Total % Received % Xferd Average Speed Time Time Time Current\n Dload Upload Total Spent Left Speed\n\r 0 0 0 0 0 0 0 0 --:--:-- --:--:-- --:--:-- 0\r 0 0 0 0 0 0 0 0 --:--:-- --:--:-- --:--:-- 0\n\r100 6975 100 6975 0 0 765k 0 --:--:-- --:--:-- --:--:-- 765k\nWARNING: Your kernel does not support swap limit capabilities or the cgroup is not mounted. Memory limited without swap.\ndocker: Error response from daemon: oci runtime error: container_linux.go:247: starting container process caused \"exec: \\\"/bin/bash\\\": stat /bin/bash: no such file or directory\".\n\n[2018-09-13 01:24:37.490]\n",
"containerExitType" : "UNKNOWN"
}
[aiotplatform_tf_test]: [LastCompletedTask]: [ContainerLocations]:
ContainerLogHttpAddress: http://192.168.1.191:8042/node/containerlogs/container_e11_1536637490555_0174_01_000002/admin/
ContainerLogNetworkPath: 192.168.1.191:/var/lib/yarn/userlogs/application_1536637490555_0174/container_e11_1536637490555_0174_01_000002
ContainerCacheNetworkPath: 192.168.1.191:/var/lib/hadoopdata/nm-local-dir/usercache/admin/appcache/application_1536637490555_0174/container_e11_1536637490555_0174_01_000002
________________________________________________________________________________________________________________________________________________________________________________________________________
[ApplicationCompletionReason]: [aiotplatform_tf_test]: FailedTaskCount 1 has reached MinFailedTaskCount 1.

the "/applicationhistory/logs/192.168.1.191:8041/container_e11_1536637490555_0174_01_000001/container_e11_1536637490555_0174_01_000001/admin" shows:

 Log Type: AllDebug.log

Log Upload Time: Thu Sep 13 01:24:39 +0000 2018

Log Length: 149406

Showing 4096 bytes of 149406 total. Click here for the full log.

 ERROR [pool-1-thread-1] com.microsoft.frameworklauncher.common.service.AbstractService: Stopping com.microsoft.frameworklauncher.applicationmaster.StatusManager
2018-09-13 01:24:37,729 INFO [pool-1-thread-1] com.microsoft.frameworklauncher.applicationmaster.StatusManager: pushStatus for the last time before stop com.microsoft.frameworklauncher.applicationmaster.StatusManager.
2018-09-13 01:24:37,729 INFO [pool-1-thread-1] com.microsoft.frameworklauncher.applicationmaster.StatusManager: [aiotplatform_tf_test]: Pushing TaskStatuses
2018-09-13 01:24:37,861 INFO [pool-1-thread-1] com.microsoft.frameworklauncher.applicationmaster.StatusManager: TaskStateCounters: [aiotplatform_tf_test][TaskFailed]: Count 1
2018-09-13 01:24:37,861 INFO [pool-1-thread-1] com.microsoft.frameworklauncher.applicationmaster.StatusManager: [aiotplatform_tf_test]: Pushed TaskStatuses
2018-09-13 01:24:37,867 ERROR [pool-1-thread-1] com.microsoft.frameworklauncher.common.service.AbstractService: Stopping com.microsoft.frameworklauncher.applicationmaster.RequestManager
2018-09-13 01:24:37,867 ERROR [pool-1-thread-1] com.microsoft.frameworklauncher.common.service.AbstractService: Stopping com.microsoft.frameworklauncher.applicationmaster.FrameworkInfoPublisher
2018-09-13 01:24:37,867 INFO [pool-1-thread-1] com.microsoft.frameworklauncher.applicationmaster.ApplicationMaster: Unregistering com.microsoft.frameworklauncher.applicationmaster.ApplicationMaster to RM
2018-09-13 01:24:37,872 INFO [pool-1-thread-1] org.apache.hadoop.yarn.client.api.impl.AMRMClientImpl: Waiting for application to be successfully unregistered.
2018-09-13 01:24:37,973 DEBUG [pool-1-thread-1] org.apache.hadoop.service.AbstractService: Service: org.apache.hadoop.yarn.client.api.async.AMRMClientAsync entered state STOPPED
2018-09-13 01:24:37,974 DEBUG [AMRM Heartbeater thread] org.apache.hadoop.yarn.client.api.async.impl.AMRMClientAsyncImpl: Heartbeater interrupted
java.lang.InterruptedException: sleep interrupted
	at java.lang.Thread.sleep(Native Method)
	at org.apache.hadoop.yarn.client.api.async.impl.AMRMClientAsyncImpl$HeartbeatThread.run(AMRMClientAsyncImpl.java:291)
2018-09-13 01:24:37,975 DEBUG [pool-1-thread-1] org.apache.hadoop.service.AbstractService: Service: org.apache.hadoop.yarn.client.api.impl.AMRMClientImpl entered state STOPPED
2018-09-13 01:24:37,975 DEBUG [pool-1-thread-1] org.apache.curator.framework.imps.CuratorFrameworkImpl: Closing
2018-09-13 01:24:37,975 DEBUG [AMRM Callback Handler Thread] org.apache.hadoop.yarn.client.api.async.impl.AMRMClientAsyncImpl: Interrupted while waiting for queue
java.lang.InterruptedException
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.reportInterruptAfterWait(AbstractQueuedSynchronizer.java:2014)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2048)
	at java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:442)
	at org.apache.hadoop.yarn.client.api.async.impl.AMRMClientAsyncImpl$CallbackHandlerThread.run(AMRMClientAsyncImpl.java:312)
2018-09-13 01:24:37,976 INFO [Curator-Framework-0] org.apache.curator.framework.imps.CuratorFrameworkImpl: backgroundOperationsLoop exiting
2018-09-13 01:24:37,976 DEBUG [pool-1-thread-1] org.apache.curator.CuratorZookeeperClient: Closing
2018-09-13 01:24:37,976 DEBUG [pool-1-thread-1] org.apache.curator.ConnectionState: Closing
2018-09-13 01:24:37,978 DEBUG [pool-1-thread-1] org.apache.zookeeper.ZooKeeper: Closing session: 0x165c6ba9d4600af
2018-09-13 01:24:37,986 INFO [pool-1-thread-1] org.apache.zookeeper.ZooKeeper: Session: 0x165c6ba9d4600af closed
2018-09-13 01:24:37,986 INFO [main-EventThread] org.apache.zookeeper.ClientCnxn: EventThread shut down for session: 0x165c6ba9d4600af
2018-09-13 01:24:37,987 INFO [pool-1-thread-1] com.microsoft.frameworklauncher.applicationmaster.ApplicationMaster: com.microsoft.frameworklauncher.applicationmaster.ApplicationMaster stopped
2018-09-13 01:24:37,989 DEBUG [Thread-7] org.apache.hadoop.util.ShutdownHookManager: ShutdownHookManger complete shutdown.

Log Type: AllError.log

Log Upload Time: Thu Sep 13 01:24:39 +0000 2018

Log Length: 19129

Showing 4096 bytes of 19129 total. Click here for the full log.

\".\n\n[2018-09-13 01:24:37.490]\n[2018-09-13 01:24:37.490]Container exited with a non-zero exit code 127. Error file: prelaunch.err.\nLast 4096 bytes of prelaunch.err :\nLast 4096 bytes of stderr :\n  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current\n                                 Dload  Upload   Total   Spent    Left  Speed\n\r  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0\r  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0\n\r100  4731  100  4731    0     0   641k      0 --:--:-- --:--:-- --:--:--  641k\n  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current\n                                 Dload  Upload   Total   Spent    Left  Speed\n\r  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0\r  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0\n\r100  6975  100  6975    0     0   765k      0 --:--:-- --:--:-- --:--:--  765k\nWARNING: Your kernel does not support swap limit capabilities or the cgroup is not mounted. Memory limited without swap.\ndocker: Error response from daemon: oci runtime error: container_linux.go:247: starting container process caused \"exec: \\\"/bin/bash\\\": stat /bin/bash: no such file or directory\".\n\n[2018-09-13 01:24:37.490]\n",
2018-09-13 01:24:37,728 ERROR [pool-1-thread-1] com.microsoft.frameworklauncher.common.service.AbstractService:   "containerExitType" : "UNKNOWN"
2018-09-13 01:24:37,728 ERROR [pool-1-thread-1] com.microsoft.frameworklauncher.common.service.AbstractService: }
2018-09-13 01:24:37,728 ERROR [pool-1-thread-1] com.microsoft.frameworklauncher.common.service.AbstractService: [aiotplatform_tf_test]: [LastCompletedTask]: [ContainerLocations]:
2018-09-13 01:24:37,728 ERROR [pool-1-thread-1] com.microsoft.frameworklauncher.common.service.AbstractService: ContainerLogHttpAddress: http://192.168.1.191:8042/node/containerlogs/container_e11_1536637490555_0174_01_000002/admin/
2018-09-13 01:24:37,729 ERROR [pool-1-thread-1] com.microsoft.frameworklauncher.common.service.AbstractService: ContainerLogNetworkPath: 192.168.1.191:/var/lib/yarn/userlogs/application_1536637490555_0174/container_e11_1536637490555_0174_01_000002
2018-09-13 01:24:37,729 ERROR [pool-1-thread-1] com.microsoft.frameworklauncher.common.service.AbstractService: ContainerCacheNetworkPath: 192.168.1.191:/var/lib/hadoopdata/nm-local-dir/usercache/admin/appcache/application_1536637490555_0174/container_e11_1536637490555_0174_01_000002
2018-09-13 01:24:37,729 ERROR [pool-1-thread-1] com.microsoft.frameworklauncher.common.service.AbstractService: ________________________________________________________________________________________________________________________________________________________________________________________________________
2018-09-13 01:24:37,729 ERROR [pool-1-thread-1] com.microsoft.frameworklauncher.common.service.AbstractService: [ApplicationCompletionReason]: [aiotplatform_tf_test]: FailedTaskCount 1 has reached MinFailedTaskCount 1.
2018-09-13 01:24:37,729 ERROR [pool-1-thread-1] com.microsoft.frameworklauncher.common.service.AbstractService: ], Exception = [null]
2018-09-13 01:24:37,729 ERROR [pool-1-thread-1] com.microsoft.frameworklauncher.common.service.AbstractService: ________________________________________________________________________________________________________________________________________________________________________________________________________
2018-09-13 01:24:37,729 ERROR [pool-1-thread-1] com.microsoft.frameworklauncher.common.service.AbstractService: Stopping com.microsoft.frameworklauncher.applicationmaster.StatusManager
2018-09-13 01:24:37,867 ERROR [pool-1-thread-1] com.microsoft.frameworklauncher.common.service.AbstractService: Stopping com.microsoft.frameworklauncher.applicationmaster.RequestManager
2018-09-13 01:24:37,867 ERROR [pool-1-thread-1] com.microsoft.frameworklauncher.common.service.AbstractService: Stopping com.microsoft.frameworklauncher.applicationmaster.FrameworkInfoPublisher

Log Type: AllWarn.log

Log Upload Time: Thu Sep 13 01:24:39 +0000 2018

Log Length: 19359

Showing 4096 bytes of 19359 total. Click here for the full log.

\".\n\n[2018-09-13 01:24:37.490]\n[2018-09-13 01:24:37.490]Container exited with a non-zero exit code 127. Error file: prelaunch.err.\nLast 4096 bytes of prelaunch.err :\nLast 4096 bytes of stderr :\n  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current\n                                 Dload  Upload   Total   Spent    Left  Speed\n\r  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0\r  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0\n\r100  4731  100  4731    0     0   641k      0 --:--:-- --:--:-- --:--:--  641k\n  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current\n                                 Dload  Upload   Total   Spent    Left  Speed\n\r  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0\r  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0\n\r100  6975  100  6975    0     0   765k      0 --:--:-- --:--:-- --:--:--  765k\nWARNING: Your kernel does not support swap limit capabilities or the cgroup is not mounted. Memory limited without swap.\ndocker: Error response from daemon: oci runtime error: container_linux.go:247: starting container process caused \"exec: \\\"/bin/bash\\\": stat /bin/bash: no such file or directory\".\n\n[2018-09-13 01:24:37.490]\n",
2018-09-13 01:24:37,728 ERROR [pool-1-thread-1] com.microsoft.frameworklauncher.common.service.AbstractService:   "containerExitType" : "UNKNOWN"
2018-09-13 01:24:37,728 ERROR [pool-1-thread-1] com.microsoft.frameworklauncher.common.service.AbstractService: }
2018-09-13 01:24:37,728 ERROR [pool-1-thread-1] com.microsoft.frameworklauncher.common.service.AbstractService: [aiotplatform_tf_test]: [LastCompletedTask]: [ContainerLocations]:
2018-09-13 01:24:37,728 ERROR [pool-1-thread-1] com.microsoft.frameworklauncher.common.service.AbstractService: ContainerLogHttpAddress: http://192.168.1.191:8042/node/containerlogs/container_e11_1536637490555_0174_01_000002/admin/
2018-09-13 01:24:37,729 ERROR [pool-1-thread-1] com.microsoft.frameworklauncher.common.service.AbstractService: ContainerLogNetworkPath: 192.168.1.191:/var/lib/yarn/userlogs/application_1536637490555_0174/container_e11_1536637490555_0174_01_000002
2018-09-13 01:24:37,729 ERROR [pool-1-thread-1] com.microsoft.frameworklauncher.common.service.AbstractService: ContainerCacheNetworkPath: 192.168.1.191:/var/lib/hadoopdata/nm-local-dir/usercache/admin/appcache/application_1536637490555_0174/container_e11_1536637490555_0174_01_000002
2018-09-13 01:24:37,729 ERROR [pool-1-thread-1] com.microsoft.frameworklauncher.common.service.AbstractService: ________________________________________________________________________________________________________________________________________________________________________________________________________
2018-09-13 01:24:37,729 ERROR [pool-1-thread-1] com.microsoft.frameworklauncher.common.service.AbstractService: [ApplicationCompletionReason]: [aiotplatform_tf_test]: FailedTaskCount 1 has reached MinFailedTaskCount 1.
2018-09-13 01:24:37,729 ERROR [pool-1-thread-1] com.microsoft.frameworklauncher.common.service.AbstractService: ], Exception = [null]
2018-09-13 01:24:37,729 ERROR [pool-1-thread-1] com.microsoft.frameworklauncher.common.service.AbstractService: ________________________________________________________________________________________________________________________________________________________________________________________________________
2018-09-13 01:24:37,729 ERROR [pool-1-thread-1] com.microsoft.frameworklauncher.common.service.AbstractService: Stopping com.microsoft.frameworklauncher.applicationmaster.StatusManager
2018-09-13 01:24:37,867 ERROR [pool-1-thread-1] com.microsoft.frameworklauncher.common.service.AbstractService: Stopping com.microsoft.frameworklauncher.applicationmaster.RequestManager
2018-09-13 01:24:37,867 ERROR [pool-1-thread-1] com.microsoft.frameworklauncher.common.service.AbstractService: Stopping com.microsoft.frameworklauncher.applicationmaster.FrameworkInfoPublisher

Log Type: InternalDebug.log

Log Upload Time: Thu Sep 13 01:24:39 +0000 2018

Log Length: 90253

Showing 4096 bytes of 90253 total. Click here for the full log.

mory limited without swap.\ndocker: Error response from daemon: oci runtime error: container_linux.go:247: starting container process caused \"exec: \\\"/bin/bash\\\": stat /bin/bash: no such file or directory\".\n\n[2018-09-13 01:24:37.490]\n",
2018-09-13 01:24:37,728 ERROR [pool-1-thread-1] com.microsoft.frameworklauncher.common.service.AbstractService:   "containerExitType" : "UNKNOWN"
2018-09-13 01:24:37,728 ERROR [pool-1-thread-1] com.microsoft.frameworklauncher.common.service.AbstractService: }
2018-09-13 01:24:37,728 ERROR [pool-1-thread-1] com.microsoft.frameworklauncher.common.service.AbstractService: [aiotplatform_tf_test]: [LastCompletedTask]: [ContainerLocations]:
2018-09-13 01:24:37,728 ERROR [pool-1-thread-1] com.microsoft.frameworklauncher.common.service.AbstractService: ContainerLogHttpAddress: http://192.168.1.191:8042/node/containerlogs/container_e11_1536637490555_0174_01_000002/admin/
2018-09-13 01:24:37,729 ERROR [pool-1-thread-1] com.microsoft.frameworklauncher.common.service.AbstractService: ContainerLogNetworkPath: 192.168.1.191:/var/lib/yarn/userlogs/application_1536637490555_0174/container_e11_1536637490555_0174_01_000002
2018-09-13 01:24:37,729 ERROR [pool-1-thread-1] com.microsoft.frameworklauncher.common.service.AbstractService: ContainerCacheNetworkPath: 192.168.1.191:/var/lib/hadoopdata/nm-local-dir/usercache/admin/appcache/application_1536637490555_0174/container_e11_1536637490555_0174_01_000002
2018-09-13 01:24:37,729 ERROR [pool-1-thread-1] com.microsoft.frameworklauncher.common.service.AbstractService: ________________________________________________________________________________________________________________________________________________________________________________________________________
2018-09-13 01:24:37,729 ERROR [pool-1-thread-1] com.microsoft.frameworklauncher.common.service.AbstractService: [ApplicationCompletionReason]: [aiotplatform_tf_test]: FailedTaskCount 1 has reached MinFailedTaskCount 1.
2018-09-13 01:24:37,729 ERROR [pool-1-thread-1] com.microsoft.frameworklauncher.common.service.AbstractService: ], Exception = [null]
2018-09-13 01:24:37,729 ERROR [pool-1-thread-1] com.microsoft.frameworklauncher.common.service.AbstractService: ________________________________________________________________________________________________________________________________________________________________________________________________________
2018-09-13 01:24:37,729 ERROR [pool-1-thread-1] com.microsoft.frameworklauncher.common.service.AbstractService: Stopping com.microsoft.frameworklauncher.applicationmaster.StatusManager
2018-09-13 01:24:37,729 INFO [pool-1-thread-1] com.microsoft.frameworklauncher.applicationmaster.StatusManager: pushStatus for the last time before stop com.microsoft.frameworklauncher.applicationmaster.StatusManager.
2018-09-13 01:24:37,729 INFO [pool-1-thread-1] com.microsoft.frameworklauncher.applicationmaster.StatusManager: [aiotplatform_tf_test]: Pushing TaskStatuses
2018-09-13 01:24:37,861 INFO [pool-1-thread-1] com.microsoft.frameworklauncher.applicationmaster.StatusManager: TaskStateCounters: [aiotplatform_tf_test][TaskFailed]: Count 1
2018-09-13 01:24:37,861 INFO [pool-1-thread-1] com.microsoft.frameworklauncher.applicationmaster.StatusManager: [aiotplatform_tf_test]: Pushed TaskStatuses
2018-09-13 01:24:37,867 ERROR [pool-1-thread-1] com.microsoft.frameworklauncher.common.service.AbstractService: Stopping com.microsoft.frameworklauncher.applicationmaster.RequestManager
2018-09-13 01:24:37,867 ERROR [pool-1-thread-1] com.microsoft.frameworklauncher.common.service.AbstractService: Stopping com.microsoft.frameworklauncher.applicationmaster.FrameworkInfoPublisher
2018-09-13 01:24:37,867 INFO [pool-1-thread-1] com.microsoft.frameworklauncher.applicationmaster.ApplicationMaster: Unregistering com.microsoft.frameworklauncher.applicationmaster.ApplicationMaster to RM
2018-09-13 01:24:37,987 INFO [pool-1-thread-1] com.microsoft.frameworklauncher.applicationmaster.ApplicationMaster: com.microsoft.frameworklauncher.applicationmaster.ApplicationMaster stopped

Log Type: InternalInfo.log

Log Upload Time: Thu Sep 13 01:24:39 +0000 2018

Log Length: 66383

Showing 4096 bytes of 66383 total. Click here for the full log.

mory limited without swap.\ndocker: Error response from daemon: oci runtime error: container_linux.go:247: starting container process caused \"exec: \\\"/bin/bash\\\": stat /bin/bash: no such file or directory\".\n\n[2018-09-13 01:24:37.490]\n",
2018-09-13 01:24:37,728 ERROR [pool-1-thread-1] com.microsoft.frameworklauncher.common.service.AbstractService:   "containerExitType" : "UNKNOWN"
2018-09-13 01:24:37,728 ERROR [pool-1-thread-1] com.microsoft.frameworklauncher.common.service.AbstractService: }
2018-09-13 01:24:37,728 ERROR [pool-1-thread-1] com.microsoft.frameworklauncher.common.service.AbstractService: [aiotplatform_tf_test]: [LastCompletedTask]: [ContainerLocations]:
2018-09-13 01:24:37,728 ERROR [pool-1-thread-1] com.microsoft.frameworklauncher.common.service.AbstractService: ContainerLogHttpAddress: http://192.168.1.191:8042/node/containerlogs/container_e11_1536637490555_0174_01_000002/admin/
2018-09-13 01:24:37,729 ERROR [pool-1-thread-1] com.microsoft.frameworklauncher.common.service.AbstractService: ContainerLogNetworkPath: 192.168.1.191:/var/lib/yarn/userlogs/application_1536637490555_0174/container_e11_1536637490555_0174_01_000002
2018-09-13 01:24:37,729 ERROR [pool-1-thread-1] com.microsoft.frameworklauncher.common.service.AbstractService: ContainerCacheNetworkPath: 192.168.1.191:/var/lib/hadoopdata/nm-local-dir/usercache/admin/appcache/application_1536637490555_0174/container_e11_1536637490555_0174_01_000002
2018-09-13 01:24:37,729 ERROR [pool-1-thread-1] com.microsoft.frameworklauncher.common.service.AbstractService: ________________________________________________________________________________________________________________________________________________________________________________________________________
2018-09-13 01:24:37,729 ERROR [pool-1-thread-1] com.microsoft.frameworklauncher.common.service.AbstractService: [ApplicationCompletionReason]: [aiotplatform_tf_test]: FailedTaskCount 1 has reached MinFailedTaskCount 1.
2018-09-13 01:24:37,729 ERROR [pool-1-thread-1] com.microsoft.frameworklauncher.common.service.AbstractService: ], Exception = [null]
2018-09-13 01:24:37,729 ERROR [pool-1-thread-1] com.microsoft.frameworklauncher.common.service.AbstractService: ________________________________________________________________________________________________________________________________________________________________________________________________________
2018-09-13 01:24:37,729 ERROR [pool-1-thread-1] com.microsoft.frameworklauncher.common.service.AbstractService: Stopping com.microsoft.frameworklauncher.applicationmaster.StatusManager
2018-09-13 01:24:37,729 INFO [pool-1-thread-1] com.microsoft.frameworklauncher.applicationmaster.StatusManager: pushStatus for the last time before stop com.microsoft.frameworklauncher.applicationmaster.StatusManager.
2018-09-13 01:24:37,729 INFO [pool-1-thread-1] com.microsoft.frameworklauncher.applicationmaster.StatusManager: [aiotplatform_tf_test]: Pushing TaskStatuses
2018-09-13 01:24:37,861 INFO [pool-1-thread-1] com.microsoft.frameworklauncher.applicationmaster.StatusManager: TaskStateCounters: [aiotplatform_tf_test][TaskFailed]: Count 1
2018-09-13 01:24:37,861 INFO [pool-1-thread-1] com.microsoft.frameworklauncher.applicationmaster.StatusManager: [aiotplatform_tf_test]: Pushed TaskStatuses
2018-09-13 01:24:37,867 ERROR [pool-1-thread-1] com.microsoft.frameworklauncher.common.service.AbstractService: Stopping com.microsoft.frameworklauncher.applicationmaster.RequestManager
2018-09-13 01:24:37,867 ERROR [pool-1-thread-1] com.microsoft.frameworklauncher.common.service.AbstractService: Stopping com.microsoft.frameworklauncher.applicationmaster.FrameworkInfoPublisher
2018-09-13 01:24:37,867 INFO [pool-1-thread-1] com.microsoft.frameworklauncher.applicationmaster.ApplicationMaster: Unregistering com.microsoft.frameworklauncher.applicationmaster.ApplicationMaster to RM
2018-09-13 01:24:37,987 INFO [pool-1-thread-1] com.microsoft.frameworklauncher.applicationmaster.ApplicationMaster: com.microsoft.frameworklauncher.applicationmaster.ApplicationMaster stopped

Log Type: prelaunch.err

Log Upload Time: Thu Sep 13 01:24:39 +0000 2018

Log Length: 0

Log Type: prelaunch.out

Log Upload Time: Thu Sep 13 01:24:39 +0000 2018

Log Length: 70

Setting up env variables
Setting up job resources
Launching container

Log Type: stderr

Log Upload Time: Thu Sep 13 01:24:39 +0000 2018

Log Length: 586

SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/var/lib/hadoopdata/nm-local-dir/usercache/admin/appcache/application_1536637490555_0174/filecache/10/frameworklauncher-1.0-SNAPSHOT-jar-with-dependencies.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/usr/local/hadoop-2.9.0/share/hadoop/common/lib/slf4j-log4j12-1.7.25.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
SLF4J: Actual binding is of type [org.slf4j.impl.Log4jLoggerFactory]

Log Type: stdout

Log Upload Time: Thu Sep 13 01:24:39 +0000 2018

Log Length: 0

**Comment by fanyangCS** [comment]
what you posted is yarn am's log. 
"docker: Error response from daemon: oci runtime error: container_linux.go:247: starting container process caused "exec: "/bin/bash": stat /bin/bash: no such file or directory"."

Maybe **"command": "/bin/server"** does not exist in your docker image?

Please post your container log for further analysis. it is here:http://192.168.1.191:8042/node/containerlogs/container_e11_1536637490555_0174_01_000002/admin/

**Comment by boozyguo** [comment]
Thans @fanyangCS 
I check the image, there is no /bin/bash. So, I add /bin/bash in the image and re-submit it.
Then the job is ok, and showing "running". But the container hasn't ssh service, how can I login the container?  

![default](https://user-images.githubusercontent.com/20755762/45466434-671ab080-b74c-11e8-95bf-2b99589b5eaa.png)

**Comment by fanyangCS** [comment]
please click "go to Tracking Page" to see the log for find out detailed log about ssh. also, when you move your mouse cursor to "View SSH Info" you will have a rough idea.

**Comment by boozyguo** [comment]
there are some logs, which one should I find information:

 DockerContainerDebug.log : Total file length is 48584 bytes.
YarnContainerDebug.log : Total file length is 190295 bytes.
prelaunch.err : Total file length is 0 bytes.
prelaunch.out : Total file length is 70 bytes.
stderr : Total file length is 915 bytes.
stdout : Total file length is 2210 bytes.

**Comment by fanyangCS** [comment]
I would start with Docker container log. But you might need to see all.

**Comment by boozyguo** [comment]
thanks @fanyangCS , I will check the logs.

**Comment by fanyangCS** [comment]
no further update for a month so we close the issue.
