### ISSUE TITLE
Unfriendly error message when submitting two jobs with the same job name through rest server

### ISSUE THREAD

**Issue by qyyy** [Microsoft/pai#1405]
Here is the error message, it's too unfriendly for me to find the reason(job name already exists).

500 b'{"code":"UnknownError","message":"[WebHDFS] 404 {\\"RemoteException\\":{\\"exception\\":\\"FileNotFoundException\\",\\"javaClassName\\":\"java.io.FileNotFoundException\\",\\"message\\":\\"File does not exist: /Container/yuqian/keras_tensorflow_backend_mnist_2018-09-19_01-56-46/YanContainerScripts/0.sh (inode 321838) Holder DFSClient_NONMAPREDUCE_1439931666_128 does not have any open files.\\\\n\\\\tat org.apache.hadoop.dfs.server.namenode.FSNamesystem.checkLease(FSNamesystem.java:2666)\\\\n\\\\tat org.apache.hadoop.hdfs.server.namenode.FSDirWriteFileOp.analyzeileState(FSDirWriteFileOp.java:521)\\\\n\\\\tat org.apache.hadoop.hdfs.server.namenode.FSDirWriteFileOp.validateAddBlock(FSDirWriteFileOp.java:61)\\\\n\\\\tat org.apache.hadoop.hdfs.server.namenode.FSNamesystem.getAdditionalBlock(FSNamesystem.java:2547)\\\\n\\\\tat org.apache.hadoop.hds.server.namenode.NameNodeRpcServer.addBlock(NameNodeRpcServer.java:846)\\\\n\\\\tat org.apache.hadoop.hdfs.protocolPB.ClientNamenodeProtocolSeverSideTranslatorPB.addBlock(ClientNamenodeProtocolServerSideTranslatorPB.java:510)\\\\n\\\\tat org.apache.hadoop.hdfs.protocol.proto.ClientNamnodeProtocolProtos$ClientNamenodeProtocol$2.callBlockingMethod(ClientNamenodeProtocolProtos.java)\\\\n\\\\tat org.apache.hadoop.ipc.ProtobufRpcngine$Server$ProtoBufRpcInvoker.call(ProtobufRpcEngine.java:503)\\\\n\\\\tat org.apache.hadoop.ipc.RPC$Server.call(RPC.java:989)\\\\n\\\\tat or.apache.hadoop.ipc.Server$RpcCall.run(Server.java:868)\\\\n\\\\tat org.apache.hadoop.ipc.Server$RpcCall.run(Server.java:814)\\\\n\\\\tat java.scurity.AccessController.doPrivileged(Native Method)\\\\n\\\\tat javax.security.auth.Subject.doAs(Subject.java:422)\\\\n\\\\tat org.apache.hadoo.security.UserGroupInformation.doAs(UserGroupInformation.java:1886)\\\\n\\\\tat org.apache.hadoop.ipc.Server$Handler.run(Server.java:2603)\\\\n\"}}"}'

**Comment by Gerhut** [comment]
The actual error is

    File does not exist: /Container/yuqian/keras_tensorflow_backend_mnist_2018-09-19_01-56-46/YanContainerScripts/0.sh

I checked the HDFS, the file exists at present.

The REST server log is

```
Error: [WebHDFS] 404 {"RemoteException":{"exception":"FileNotFoundException","javaClassName":"java.io.FileNotFoundException","message":"File does not exist: /Container/yuqian/keras_tensorflow_backend_mnist_2018-09-19_01-56-46/YarnContainerScripts/0.sh (inode 321838) Holder DFSClient_NONMAPREDUCE_1439931666_128 does not have any open files.\n\tat org.apache.hadoop.hdfs.server.namenode.FSNamesystem.checkLease(FSNamesystem.java:2666)\n\tat org.apache.hadoop.hdfs.server.namenode.FSDirWriteFileOp.analyzeFileState(FSDirWriteFileOp.java:521)\n\tat org.apache.hadoop.hdfs.server.namenode.FSDirWriteFileOp.validateAddBlock(FSDirWriteFileOp.java:161)\n\tat org.apache.hadoop.hdfs.server.namenode.FSNamesystem.getAdditionalBlock(FSNamesystem.java:2547)\n\tat org.apache.hadoop.hdfs.server.namenode.NameNodeRpcServer.addBlock(NameNodeRpcServer.java:846)\n\tat org.apache.hadoop.hdfs.protocolPB.ClientNamenodeProtocolServerSideTranslatorPB.addBlock(ClientNamenodeProtocolServerSideTranslatorPB.java:510)\n\tat org.apache.hadoop.hdfs.protocol.proto.ClientNamenodeProtocolProtos$ClientNamenodeProtocol$2.callBlockingMethod(ClientNamenodeProtocolProtos.java)\n\tat org.apache.hadoop.ipc.ProtobufRpcEngine$Server$ProtoBufRpcInvoker.call(ProtobufRpcEngine.java:503)\n\tat org.apache.hadoop.ipc.RPC$Server.call(RPC.java:989)\n\tat org.apache.hadoop.ipc.Server$RpcCall.run(Server.java:868)\n\tat org.apache.hadoop.ipc.Server$RpcCall.run(Server.java:814)\n\tat java.security.AccessController.doPrivileged(Native Method)\n\tat javax.security.auth.Subject.doAs(Subject.java:422)\n\tat org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1886)\n\tat org.apache.hadoop.ipc.Server$Handler.run(Server.java:2603)\n"}}
    at Hdfs._constructErrorObject (/usr/src/app/src/util/hdfs.js:63:14)
    at unirest.put.send.end (/usr/src/app/src/util/hdfs.js:107:21)
    at Request.handleRequestResponse [as _callback] (/usr/src/app/node_modules/unirest/index.js:463:26)
    at Request.self.callback (/usr/src/app/node_modules/unirest/node_modules/request/request.js:187:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:191:7)
    at Request.<anonymous> (/usr/src/app/node_modules/unirest/node_modules/request/request.js:1044:10)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:188:7)
    at IncomingMessage.<anonymous> (/usr/src/app/node_modules/unirest/node_modules/request/request.js:965:12) 
```

Shows it was throwed in `Hdfs#_createFile`

https://github.com/Microsoft/pai/blob/master/src/rest-server/src/util/hdfs.js#L107

The HDFS error is 

```
File does not exist: /Container/yuqian/keras_tensorflow_backend_mnist_2018-09-19_01-56-46/YarnContainerScripts/0.sh (inode 321838) Holder DFSClient_NONMAPREDUCE_1439931666_128 does not have any open files.
        at org.apache.hadoop.hdfs.server.namenode.FSNamesystem.checkLease(FSNamesystem.java:2666)
        at org.apache.hadoop.hdfs.server.namenode.FSDirWriteFileOp.analyzeFileState(FSDirWriteFileOp.java:521)
        at org.apache.hadoop.hdfs.server.namenode.FSDirWriteFileOp.validateAddBlock(FSDirWriteFileOp.java:161)
        at org.apache.hadoop.hdfs.server.namenode.FSNamesystem.getAdditionalBlock(FSNamesystem.java:2547)
        at org.apache.hadoop.hdfs.server.namenode.NameNodeRpcServer.addBlock(NameNodeRpcServer.java:846)
        at org.apache.hadoop.hdfs.protocolPB.ClientNamenodeProtocolServerSideTranslatorPB.addBlock(ClientNamenodeProtocolServerSideTranslatorPB.java:510)
        at org.apache.hadoop.hdfs.protocol.proto.ClientNamenodeProtocolProtos$ClientNamenodeProtocol$2.callBlockingMethod(ClientNamenodeProtocolProtos.java)
        at org.apache.hadoop.ipc.ProtobufRpcEngine$Server$ProtoBufRpcInvoker.call(ProtobufRpcEngine.java:503)
        at org.apache.hadoop.ipc.RPC$Server.call(RPC.java:989)
        at org.apache.hadoop.ipc.Server$RpcCall.run(Server.java:868)
        at org.apache.hadoop.ipc.Server$RpcCall.run(Server.java:814)
        at java.security.AccessController.doPrivileged(Native Method)
        at javax.security.auth.Subject.doAs(Subject.java:422)
        at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1886)
        at org.apache.hadoop.ipc.Server$Handler.run(Server.java:2603)
```

What scenario will cause HDFS response 404 in create operation? Ping @DongZhaoYu for help.

**Comment by fanyangCS** [comment]
close as no further input
