### ISSUE TITLE
Launcher crash because too many jobs

### ISSUE THREAD

**Issue by hao1939** [Microsoft/pai#1419]
If there are too many job, the zookeeper client crash:

```
2018-09-20 03:27:52,317 WARN [main-SendThread(10.151.40.234:2181)] org.apache.zookeeper.ClientCnxn: Session 0x165eaed04211b5e for server 10.151.40.234/10.151.40.234:2181, unexpected error, closing socket connection and attempting reconnect
java.io.IOException: Packet len4204059 is out of range!
                at org.apache.zookeeper.ClientCnxnSocket.readLength(ClientCnxnSocket.java:112)
                at org.apache.zookeeper.ClientCnxnSocketNIO.doIO(ClientCnxnSocketNIO.java:79)
                at org.apache.zookeeper.ClientCnxnSocketNIO.doTransport(ClientCnxnSocketNIO.java:366)
                at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1141)
```

We can workaround via increasing the buffer size `-Djute.maxbuffer=49107800`.
And there is a side effect that the launcher would take a very long time starting up.
When launcher starts up, it will handle all job entries one by one, it would take a long time if the size increase to 100k and above.

**Comment by yqwang-ms** [comment]
We now have limit for total task number, the task number in one framework.
How about also limit the total Framework number?
It can help to avoid this issue.

**Comment by hao1939** [comment]
Cool, I have done the mitigation.

Well, since we are going to leverage history server to store the GCed jobs, the currently behavior is fine.
My test is an extremely case, it's running hug amount of short elapsed jobs, which is not a reasonable user scenario.

**Comment by fanyangCS** [comment]
It would be great to document the setting and state the limit of the running jobs.

**Comment by hao1939** [comment]
Add a faq #1462
