### ISSUE TITLE
on int bed, yarn-exporter is logging errors

### ISSUE THREAD

**Issue by DongZhaoYu** [Microsoft/pai#1482]
the error log is :
10.151.40.234 - - [13/Oct/2018 03:46:50] "GET /metrics HTTP/1.1" 200 1524
10.151.40.234 - - [13/Oct/2018 03:47:11] "GET /metrics HTTP/1.1" 200 1524
10.151.40.234 - - [13/Oct/2018 03:47:41] "GET /metrics HTTP/1.1" 200 1524
10.151.40.234 - - [13/Oct/2018 03:48:11] "GET /metrics HTTP/1.1" 200 1524
10.90.6.147 - - [13/Oct/2018 03:48:33] "GET / HTTP/1.1" 200 1523
10.90.6.147 - - [13/Oct/2018 03:48:33] "GET /favicon.ico HTTP/1.1" 200 1523
10.151.40.234 - - [13/Oct/2018 03:48:52] "GET /metrics HTTP/1.1" 200 1523
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/wsgiref/handlers.py", line 138, in run
    self.finish_response()
  File "/usr/local/lib/python3.7/wsgiref/handlers.py", line 180, in finish_response
    self.write(data)
  File "/usr/local/lib/python3.7/wsgiref/handlers.py", line 274, in write
    self.send_headers()
  File "/usr/local/lib/python3.7/wsgiref/handlers.py", line 332, in send_headers
    self.send_preamble()
  File "/usr/local/lib/python3.7/wsgiref/handlers.py", line 255, in send_preamble
    ('Date: %s\r\n' % format_date_time(time.time())).encode('iso-8859-1')
  File "/usr/local/lib/python3.7/wsgiref/handlers.py", line 453, in _write
    result = self.stdout.write(data)
  File "/usr/local/lib/python3.7/socketserver.py", line 796, in write
    self._sock.sendall(b)
BrokenPipeError: [Errno 32] Broken pipe

**Comment by xudifsd** [comment]
I think this is how wsgi handler handles disconnection. It's not a big deal.

**Comment by fanyangCS** [comment]
@xudifsd , please close this issue if there is no need for further action.
