### ISSUE TITLE
watchdog has error `Back-off restarting failed container`

### ISSUE THREAD

**Issue by shawntian90** [Microsoft/pai#1492]
hi, 

The k8s dashboard show the error message of pod `Back-off restarting failed container` while other service of k8s is runing normally. I find the docker container and get logs of it:

```
10.xx.xx.246 - - [15/Oct/2018 09:51:03] "GET / HTTP/1.1" 200 14775
2018-10-15 09:51:06,473 - WARNING - watchdog.py:164 - unkown pod batch-job-hadoop-vhvqc
2018-10-15 09:51:06,473 - WARNING - watchdog.py:164 - unkown pod etcd-server-10.xx.xx.2
2018-10-15 09:51:06,476 - ERROR - watchdog.py:326 - ssh to 10.xx.xx.1 failed
Traceback (most recent call last):
  File "/watchdog.py", line 320, in collect_docker_daemon_status
    out, err = ssh_exec(host, cmd)
  File "/watchdog.py", line 133, in ssh_exec
    ssh.connect(hostname=hostip, port=port, username=username, password=password)
  File "/usr/local/lib/python2.7/site-packages/paramiko/client.py", line 357, in connect
    raise NoValidConnectionsError(errors)
NoValidConnectionsError: [Errno None] Unable to connect to port 22 on 10.xx.xx.2
2018-10-15 09:51:06,476 - ERROR - watchdog.py:326 - ssh to 10.xx.xx.1 failed
Traceback (most recent call last):
  File "/watchdog.py", line 320, in collect_docker_daemon_status
    out, err = ssh_exec(host, cmd)
  File "/watchdog.py", line 133, in ssh_exec
    ssh.connect(hostname=hostip, port=port, username=username, password=password)
  File "/usr/local/lib/python2.7/site-packages/paramiko/client.py", line 357, in connect
    raise NoValidConnectionsError(errors)
NoValidConnectionsError: [Errno None] Unable to connect to port 22 on 10.xx.xx.1
```

Seems the failure reason is that ssh to nodes of cluster failed because of wrong ssh `PORT` loading from `cluster-configuration`.

It should be some `2222` instead of `22` in my `/cluster-configuration`.

Cluster INFO:

- pai tag: v0.7.2
- two nodes
- deployed via dev-box

**Comment by shawntian90** [comment]
## cluster-configuration.yaml

```yaml
default-machine-properties:
  # Account with root permission
  username: myusername
  password: mypassword
  sshport: 2222


machine-sku:

  WORKER:
    mem: 512
    gpu:
      type: xxxx
      count: 4
    cpu:
      vcore: 32
    dataFolder: "/data"
    #Note: Up to now, the only supported os version is Ubuntu16.04. Please do not change it here.
    os: ubuntu16.04

  MASTER:
    mem: 16
    cpu:
      vcore: 8
    dataFolder: "/data"
    #Note: Up to now, the only supported os version is Ubuntu16.04. Pls don't change it here.
    os: ubuntu16.04



machine-list:

    - hostname: master01
      hostip: 10.xx.xx.2
      machine-type: MASTER
      etcdid: etcdid1
      k8s-role: master
      dashboard: "true"
      zkid: "1"
      pai-master: "true"


    - hostname: worker01
      hostip: 10.xx.xx.2
      machine-type: WORKER
      k8s-role: worker
      pai-worker: "true"
```

**Comment by YanjieGao** [comment]
currently code's default use 22 https://github.com/Microsoft/pai/blob/eb91fb3692931265057260f8ba6389c664e1fe4c/src/watchdog/src/watchdog.py#L125

@shawntian90  if you use latest version of pai, you could change watchdog ssh port and rebuild watchdog image and redeploy watchdog.

build:
https://github.com/Microsoft/pai/blob/master/docs/pai-build/pai-build.md
restart  1 service:
https://github.com/Microsoft/pai/blob/master/docs/pai-management/doc/cluster-bootup.md#c-step-5

@xudifsd , it seems we make it as a config item will be more extensible

**Comment by xudifsd** [comment]
@shawntian90 watchdog copied cluster-configuration's sshport into configmap, but they use different keys, one using sshport, another using port, thus caused your problem, I already submitted a PR.
