### ISSUE TITLE
Launcher cannot work with Java 9

### ISSUE THREAD

**Issue by yqwang-ms** [Microsoft/pai#157]
Launcher cannot work with Java 9 due to hibernate validator's getJavaRelease.

`Caused by: java.lang.ArrayIndexOutOfBoundsException: 1
	at org.hibernate.validator.internal.util.Version.getJavaRelease(Version.java:36)
	at org.hibernate.validator.internal.engine.ConfigurationImpl.<init>(ConfigurationImpl.java:119)
	at org.hibernate.validator.internal.engine.ConfigurationImpl.<init>(ConfigurationImpl.java:95)
	at org.hibernate.validator.HibernateValidator.createGenericConfiguration(HibernateValidator.java:31)
	at javax.validation.Validation$GenericBootstrapImpl.configure(Validation.java:296)
	at javax.validation.Validation.buildDefaultValidatorFactory(Validation.java:103)
	at com.microsoft.frameworklauncher.common.ModelValidation.<clinit>(ModelValidation.java:32)
	at com.microsoft.frameworklauncher.common.model.FrameworkDescriptor.setTaskRoles(FrameworkDescriptor.java:103)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at com.fasterxml.jackson.databind.deser.impl.MethodProperty.set(MethodProperty.java:115)
	... 50 more`

**Comment by yqwang-ms** [comment]
low priority, backlog it.

**Comment by scarlett2018** [comment]
cleaning old issues,  @yqwang-ms  please help to evaluate whether this is still an issue, thanks.

**Comment by fanyangCS** [comment]
we fix the version of java. https://github.com/Microsoft/pai/pull/2097
