### ISSUE TITLE
watchdog triggered None exception

### ISSUE THREAD

**Issue by xudifsd** [Microsoft/pai#1602]
log
```
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/wsgiref/handlers.py", line 85, in run
    self.result = application(self.environ, self.start_response)
  File "/usr/local/lib/python2.7/site-packages/prometheus_client/exposition.py", line 41, in prometheus_app
    output = generate_latest(r)
  File "/usr/local/lib/python2.7/site-packages/prometheus_client/exposition.py", line 78, in generate_latest
    for k, v in sorted(labels.items())]))
AttributeError: 'NoneType' object has no attribute 'replace'
```

**Comment by xudifsd** [comment]
Maybe caused by

```
2018-10-26 09:55:14,778 - ERROR - watchdog.py:252 - requesting 10.150.140.21:10255/healthz failed
Traceback (most recent call last):
  File "/watchdog.py", line 248, in collect_healthz
    error = requests.get("http://{}:{}{}".format(address, port, url)).text
  File "/usr/local/lib/python2.7/site-packages/requests/api.py", line 72, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/requests/api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/requests/sessions.py", line 512, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python2.7/site-packages/requests/sessions.py", line 622, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/requests/adapters.py", line 513, in send
    raise ConnectionError(e, request=request)
ConnectionError: HTTPConnectionPool(host='10.150.140.21', port=10255): Max retries exceeded with url: /healthz (Caused by NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x7fe5f597afd0&gt;: Failed to establish a new connection: [Errno 111] Connection refused',))
```

**Comment by xudifsd** [comment]
One of labels value is None

**Comment by xudifsd** [comment]
May caused by [this](https://github.com/Microsoft/pai/blob/master/src/watchdog/src/watchdog.py#L172). `batch-job-hadoop` does not have `app` label, thus service_name will be None. We should ignore services do not have `app` label.

Should check if other value may be None.
