### ISSUE TITLE
hadoop-node-manager startup failed

### ISSUE THREAD

**Issue by shawntian90** [Microsoft/pai#1765]
Hi,

I found a bug when I add new node to existing cluster `version v0.7.2`, which server's hostname is upper case like 'MG357', etc.

The error message of container on worker is:
```
root@MG357:/data# docker logs -f 6b36
The ip-address of this machine is: 10.0.0.357
Traceback (most recent call last):
  File "/usr/local/host-configure.py", line 90, in <module>
    main()
  File "/usr/local/host-configure.py", line 84, in main
    target_file_latest = generate_from_template(target_file_origin, cluster_config, hostname)
  File "/usr/local/host-configure.py", line 50, in generate_from_template
    "host_config": cluster_config[ hostname ],
KeyError: 'MG357'
```

So when I change the hostname via `hostnamectl set-hostname mg357` and wait for 5mins, it works without any error.

**Comment by mzmssg** [comment]
Please update to 0.8
