### ISSUE TITLE
How to use GPUs on different machines? And how to change maxGPUs?

### ISSUE THREAD

**Issue by ICEORY** [Microsoft/pai#1832]
Hi, I build a cluster with 2 workers, and each worker has 10 GPU. How to use the GPU on different machine? When I set the number of GPUs to 15, I get the following error:
```
Exception:
org.apache.hadoop.yarn.exceptions.InvalidResourceRequestException: Invalid resource request, requested GPUs < 0, or requested GPUs > max configured, requestedGPUs=15, maxGPUs=8
at org.apache.hadoop.yarn.server.resourcemanager.scheduler.SchedulerUtils.validateResourceRequest(SchedulerUtils.java:284)
at org.apache.hadoop.yarn.server.resourcemanager.scheduler.SchedulerUtils.normalizeAndValidateRequest(SchedulerUtils.java:231)
at org.apache.hadoop.yarn.server.resourcemanager.scheduler.SchedulerUtils.normalizeAndvalidateRequest(SchedulerUtils.java:247)
at org.apache.hadoop.yarn.server.resourcemanager.RMServerUtils.normalizeAndValidateRequests(RMServerUtils.java:246)
at org.apache.hadoop.yarn.server.resourcemanager.DefaultAMSProcessor.allocate(DefaultAMSProcessor.java:214)
at org.apache.hadoop.yarn.server.resourcemanager.AMSProcessingChain.allocate(AMSProcessingChain.java:92)
at org.apache.hadoop.yarn.server.resourcemanager.ApplicationMasterService.allocate(ApplicationMasterService.java:388)
at org.apache.hadoop.yarn.api.impl.pb.service.ApplicationMasterProtocolPBServiceImpl.allocate(ApplicationMasterProtocolPBServiceImpl.java:60)
at org.apache.hadoop.yarn.proto.ApplicationMasterProtocol$ApplicationMasterProtocolService$2.callBlockingMethod(ApplicationMasterProtocol.java:99)
at org.apache.hadoop.ipc.ProtobufRpcEngine$Server$ProtoBufRpcInvoker.call(ProtobufRpcEngine.java:503)
at org.apache.hadoop.ipc.RPC$Server.call(RPC.java:989)
at org.apache.hadoop.ipc.Server$RpcCall.run(Server.java:868)
at org.apache.hadoop.ipc.Server$RpcCall.run(Server.java:814)
at java.security.AccessController.doPrivileged(Native Method)
at javax.security.auth.Subject.doAs(Subject.java:422)
at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1886)
at org.apache.hadoop.ipc.Server$Handler.run(Server.java:2603)
```
But when I run 3 tasks to use 8, 8, 4 GPUs, and force the third task to use GPUs on two machines. I get 

```
Start Time: 12/5/2018, 10:55:43 PM

Finish Time: 12/5/2018, 11:14:12 PM

Exit Diagnostics:


[ExitStatus]: AM_INTERNAL_TRANSIENT_CONFLICT_ERROR
[ExitCode]: 215
[ExitDiagnostics]:
AM internal transient conflict error
[ExitType]: TRANSIENT_CONFLICT
_____________________________________________________________
[ExitCustomizedDiagnostics]:
GangAllocation cannot be satisfied in time: Still waiting for 1 outstanding Tasks after timeout 1100s, maybe current available **resource for the application is not enough, please retry later.**
```
How to solve this issue?
Thanks!

**Comment by fanyangCS** [comment]
Please read the job tutorial and this example to learn how to run a distributed job.
https://github.com/Microsoft/pai/blob/master/docs/job_tutorial.md#a-deep-learning-job-example-
At the high level, you will need to specify >1 task in a taskRole, or more than 1 taskRole to have multiple containers running in the platform. And you can leverage the PAI environment variables to retrieve the IP addresses of the containers so as to run a distributed job.

**Comment by fanyangCS** [comment]
if the 10GPUs are in one server, I believe you can use them in a container. Please let us know if you run into any issue.
