### ISSUE TITLE
Race condition in YARN when recover job

### ISSUE THREAD

**Issue by mzmssg** [microsoft/pai#1936]
**Organization Name**: ms

**Short summary about the issue/question**: YARN bug in version 2.9

**Brief what process you are following**: upgrade as instruction

**How to reproduce it**: unkonwn

**OpenPAI Environment**:
- OpenPAI version: master, I think it will also happen on release branch.
- Cloud provider or hardware configuration: 133 bed
- OS (e.g. from /etc/os-release): ubuntu
- Kernel (e.g. `uname -a`): 4.4.0-130-generic
- Others:

**Anything else we need to know**:
It should be **RM bug** https://issues.apache.org/jira/browse/YARN-6827?page=com.atlassian.jira.plugin.system.issuetabpanels%3Aall-tabpanel, it has been fixed in **hadoop 2.10**

Log from RM, and it hangs at the end
```
18/12/25 11:34:14 INFO capacity.CapacityScheduler: Priority '0' is acceptable in queue : default for application: application_1543831011585_1518
18/12/25 11:34:14 WARN rmapp.RMAppImpl: The specific max attempts: 3 for application: 1518 is invalid, because it is out of the range [1, 2]. Use the global max attempts instead.
18/12/25 11:34:14 INFO rmapp.RMAppImpl: The attemptFailuresValidityInterval for the application: application_1543831011585_1518 is 10000.
18/12/25 11:34:14 ERROR metrics.TimelineServiceV1Publisher: Error when publishing entity [YARN_APPLICATION,application_1543831011585_1518]
java.lang.NullPointerException
        at org.apache.hadoop.yarn.client.api.impl.TimelineClientImpl.putEntities(TimelineClientImpl.java:178)
        at org.apache.hadoop.yarn.server.resourcemanager.metrics.TimelineServiceV1Publisher.putEntity(TimelineServiceV1Publisher.java:372)
        at org.apache.hadoop.yarn.server.resourcemanager.metrics.TimelineServiceV1Publisher.appFinished(TimelineServiceV1Publisher.java:158)
        at org.apache.hadoop.yarn.server.resourcemanager.rmapp.RMAppImpl$FinalTransition.transition(RMAppImpl.java:1448)
        at org.apache.hadoop.yarn.server.resourcemanager.rmapp.RMAppImpl$RMAppRecoveredTransition.transition(RMAppImpl.java:1067)
        at org.apache.hadoop.yarn.server.resourcemanager.rmapp.RMAppImpl$RMAppRecoveredTransition.transition(RMAppImpl.java:1056)
        at org.apache.hadoop.yarn.state.StateMachineFactory$MultipleInternalArc.doTransition(StateMachineFactory.java:385)
        at org.apache.hadoop.yarn.state.StateMachineFactory.doTransition(StateMachineFactory.java:302)
        at org.apache.hadoop.yarn.state.StateMachineFactory.access$500(StateMachineFactory.java:46)
        at org.apache.hadoop.yarn.state.StateMachineFactory$InternalStateMachine.doTransition(StateMachineFactory.java:487)
        at org.apache.hadoop.yarn.server.resourcemanager.rmapp.RMAppImpl.handle(RMAppImpl.java:880)
        at org.apache.hadoop.yarn.server.resourcemanager.RMAppManager.recoverApplication(RMAppManager.java:340)
        at org.apache.hadoop.yarn.server.resourcemanager.RMAppManager.recover(RMAppManager.java:528)
        at org.apache.hadoop.yarn.server.resourcemanager.ResourceManager.recover(ResourceManager.java:1394)
        at org.apache.hadoop.yarn.server.resourcemanager.ResourceManager$RMActiveServices.serviceStart(ResourceManager.java:758)
        at org.apache.hadoop.service.AbstractService.start(AbstractService.java:194)
        at org.apache.hadoop.yarn.server.resourcemanager.ResourceManager.startActiveServices(ResourceManager.java:1147)
        at org.apache.hadoop.yarn.server.resourcemanager.ResourceManager$1.run(ResourceManager.java:1187)
        at org.apache.hadoop.yarn.server.resourcemanager.ResourceManager$1.run(ResourceManager.java:1183)
        at java.security.AccessController.doPrivileged(Native Method)
        at javax.security.auth.Subject.doAs(Subject.java:422)
        at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1886)
        at org.apache.hadoop.yarn.server.resourcemanager.ResourceManager.transitionToActive(ResourceManager.java:1183)
        at org.apache.hadoop.yarn.server.resourcemanager.ResourceManager.serviceStart(ResourceManager.java:1223)
        at org.apache.hadoop.service.AbstractService.start(AbstractService.java:194)
        at org.apache.hadoop.yarn.server.resourcemanager.ResourceManager.main(ResourceManager.java:1422)
18/12/25 11:34:14 INFO capacity.CapacityScheduler: Priority '0' is acceptable in queue : default for application: application_1543831011585_1519
18/12/25 11:34:14 WARN rmapp.RMAppImpl: The specific max attempts: 3 for application: 1519 is invalid, because it is out of the range [1, 2]. Use the global max attempts instead.
18/12/25 11:34:14 INFO rmapp.RMAppImpl: The attemptFailuresValidityInterval for the application: application_1543831011585_1519 is 10000.
18/12/25 11:34:14 ERROR metrics.TimelineServiceV1Publisher: Error when publishing entity [YARN_APPLICATION,application_1543831011585_1519]
java.lang.NullPointerException
        at org.apache.hadoop.yarn.client.api.impl.TimelineClientImpl.putEntities(TimelineClientImpl.java:178)
        at org.apache.hadoop.yarn.server.resourcemanager.metrics.TimelineServiceV1Publisher.putEntity(TimelineServiceV1Publisher.java:372)
        at org.apache.hadoop.yarn.server.resourcemanager.metrics.TimelineServiceV1Publisher.appFinished(TimelineServiceV1Publisher.java:158)
        at org.apache.hadoop.yarn.server.resourcemanager.rmapp.RMAppImpl$FinalTransition.transition(RMAppImpl.java:1448)
        at org.apache.hadoop.yarn.server.resourcemanager.rmapp.RMAppImpl$RMAppRecoveredTransition.transition(RMAppImpl.java:1067)
        at org.apache.hadoop.yarn.server.resourcemanager.rmapp.RMAppImpl$RMAppRecoveredTransition.transition(RMAppImpl.java:1056)
        at org.apache.hadoop.yarn.state.StateMachineFactory$MultipleInternalArc.doTransition(StateMachineFactory.java:385)
        at org.apache.hadoop.yarn.state.StateMachineFactory.doTransition(StateMachineFactory.java:302)
        at org.apache.hadoop.yarn.state.StateMachineFactory.access$500(StateMachineFactory.java:46)
        at org.apache.hadoop.yarn.state.StateMachineFactory$InternalStateMachine.doTransition(StateMachineFactory.java:487)
        at org.apache.hadoop.yarn.server.resourcemanager.rmapp.RMAppImpl.handle(RMAppImpl.java:880)
        at org.apache.hadoop.yarn.server.resourcemanager.RMAppManager.recoverApplication(RMAppManager.java:340)
        at org.apache.hadoop.yarn.server.resourcemanager.RMAppManager.recover(RMAppManager.java:528)
        at org.apache.hadoop.yarn.server.resourcemanager.ResourceManager.recover(ResourceManager.java:1394)
        at org.apache.hadoop.yarn.server.resourcemanager.ResourceManager$RMActiveServices.serviceStart(ResourceManager.java:758)
        at org.apache.hadoop.service.AbstractService.start(AbstractService.java:194)
        at org.apache.hadoop.yarn.server.resourcemanager.ResourceManager.startActiveServices(ResourceManager.java:1147)
        at org.apache.hadoop.yarn.server.resourcemanager.ResourceManager$1.run(ResourceManager.java:1187)
        at org.apache.hadoop.yarn.server.resourcemanager.ResourceManager$1.run(ResourceManager.java:1183)
        at java.security.AccessController.doPrivileged(Native Method)
        at javax.security.auth.Subject.doAs(Subject.java:422)
        at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1886)
        at org.apache.hadoop.yarn.server.resourcemanager.ResourceManager.transitionToActive(ResourceManager.java:1183)
        at org.apache.hadoop.yarn.server.resourcemanager.ResourceManager.serviceStart(ResourceManager.java:1223)
        at org.apache.hadoop.service.AbstractService.start(AbstractService.java:194)
        at org.apache.hadoop.yarn.server.resourcemanager.ResourceManager.main(ResourceManager.java:1422)
18/12/25 11:34:14 INFO resourcemanager.RMAppManager: Successfully recovered 1002 out of 1002 applications
18/12/25 11:34:14 INFO resourcemanager.ResourceManager: Recovery ended
18/12/25 11:34:14 INFO security.RMContainerTokenSecretManager: Rolling master-key for container-tokens
18/12/25 11:34:14 INFO security.NMTokenSecretManagerInRM: Rolling master-key for nm-tokens
18/12/25 11:34:14 INFO delegation.AbstractDelegationTokenSecretManager: Updating the current master key for generating delegation tokens
18/12/25 11:34:14 INFO security.RMDelegationTokenSecretManager: storing master key with keyID 1030
18/12/25 11:34:14 INFO recovery.RMStateStore: Storing RMDTMasterKey.
18/12/25 11:34:15 INFO delegation.AbstractDelegationTokenSecretManager: Starting expired delegation token remover thread, tokenRemoverScanInterval=60 min(s)
18/12/25 11:34:15 INFO delegation.AbstractDelegationTokenSecretManager: Updating the current master key for generating delegation tokens
18/12/25 11:34:15 INFO security.RMDelegationTokenSecretManager: storing master key with keyID 1031
18/12/25 11:34:15 INFO recovery.RMStateStore: Storing RMDTMasterKey.

```

**Comment by scarlett2018** [comment]
@mzmssg - what's the impact to PAI with this Yarn's bug?

**Comment by mzmssg** [comment]
Closed, it hangs mostly because of zk.

**Comment by GitHub007Dra** [comment]
me too  ..   plz help me

**Comment by scarlett2018** [comment]
@mzmssg ^^^ @GitHub007Dra

**Comment by GitHub007Dra** [comment]
![image](https://user-images.githubusercontent.com/36945182/55928725-57b10680-5c4c-11e9-8623-2bc6bf06ba6c.png)

**Comment by GitHub007Dra** [comment]
[logs-from-hadoop-resource-manager-in-hadoop-resource-manager-ds-w6lq8.txt](https://github.com/Microsoft/pai/files/3067442/logs-from-hadoop-resource-manager-in-hadoop-resource-manager-ds-w6lq8.txt)

this is log ..

**Comment by mzmssg** [comment]
@GitHub007Dra 
Could you restart zookeeper?

**Comment by GitHub007Dra** [comment]
> @GitHub007Dra
> Could you restart zookeeper, then restart resource manager

ye,but it doesn't work. i've already done it.

**Comment by GitHub007Dra** [comment]
> @GitHub007Dra
> Could you restart zookeeper, then restart resource manager
![image](https://user-images.githubusercontent.com/36945182/55941627-2567cf00-5c75-11e9-8c09-e0b16b55b06d.png)

is this zookeeper?

**Comment by GitHub007Dra** [comment]
> @GitHub007Dra
> Could you restart zookeeper, then restart resource manager
![image](https://user-images.githubusercontent.com/36945182/55942236-8f34a880-5c76-11e9-825f-7c0c8c866d8d.png)
is this zookeeper?

**Comment by mzmssg** [comment]
Yeah, please add zookeeper log as well

**Comment by GitHub007Dra** [comment]
> Yeah, please add zookeeper log as well, I also suggest open debug log:
> 
> 1. Change INFO to DEBUG at 
>      
>        
>          [pai/src/hadoop-resource-manager/deploy/hadoop-resource-manager.yaml.template](https://github.com/Microsoft/pai/blob/48a5bad172a82e9f7b006c27a3185375988d8f2b/src/hadoop-resource-manager/deploy/hadoop-resource-manager.yaml.template#L85)
>        
>        
>             Line 85
>          in
>          [48a5bad](/Microsoft/pai/commit/48a5bad172a82e9f7b006c27a3185375988d8f2b)
>        
>        
>        
>        
>    
>            
>              
>               value: INFO,console,RFA
> 2. Then restart hadoop resource manager
>    ```
>    ./paictl.py service stop -n hadoop-resource-manager
>    ./paictl.py service start -n hadoop-resource-manager
>    ```
![image](https://user-images.githubusercontent.com/36945182/55945201-e5a4e580-5c7c-11e9-8f00-d35f19c1113b.png)

There is no name field. then i add 
execute this cmd
`python paictl.py service stop -c ~/.kube/config && python paictl.py cluster k8s-clean -p ~/pai-config`
this is the zk log

**Comment by mzmssg** [comment]
Oops, it seems due to hdfs safemode:
```
19/04/11 09:43:05 DEBUG retry.RetryInvocationHandler: org.apache.hadoop.ipc.RemoteException(org.apache.hadoop.hdfs.server.namenode.SafeModeException): Cannot create directory /yarn/node-labels. Name node is in safe mode.
The reported blocks 0 needs additional 484 blocks to reach the threshold 0.9900 of total blocks 489.
```
Need more details from hdfs log(name/data-node). If you haven't used PAI, delete all service for a clean enviroments might be a option: `./paictl.py service delete`

**Comment by mzmssg** [comment]
Inactive
