### ISSUE TITLE
pai-0.8.2 deployment  problem of rest-server

### ISSUE THREAD

**Issue by dongluyang** [Microsoft/pai#1956]
when i deploy the pod of rest-server from pai v0.8.2, the following error is shown, it blocked me for several days.

2018-12-28T06:21:33.875Z [INFO] config: {"env":"production","logLevel":"debug","serverPort":8080,"jwtSecret":"pai-secret"} 
2018-12-28T06:21:33.878Z [INFO] launcher config: 
2018-12-28T06:21:33.883Z [INFO] RESTful API server starts on port 8080 
/usr/src/app/src/config/launcher.js:144
      throw new Error('cannot connect to framework launcher');
      ^
 Error: cannot connect to framework launcher
    at unirest.get.timeout.end (/usr/src/app/src/config/launcher.js:144:13)
    at Request.handleRequestResponse [as _callback] (/usr/src/app/node_modules/unirest/index.js:355:15)
    at self.callback (/usr/src/app/node_modules/unirest/node_modules/request/request.js:187:22)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:188:7)
    at Timeout._onTimeout (/usr/src/app/node_modules/unirest/node_modules/request/request.js:762:12)
    at ontimeout (timers.js:386:11)
    at tryOnTimeout (timers.js:250:5)
    at Timer.listOnTimeout (timers.js:214:5)
 npm ERR! Linux 4.4.0-141-generic
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
npm ERR! node v6.12.0
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! pai-rest-server@0.8.0 start: `node index.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the pai-rest-server@0.8.0 start script 'node index.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the pai-rest-server package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node index.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs pai-rest-server
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls pai-rest-server
npm ERR! There is likely additional logging output above.
 npm ERR! Please include the following file with any support request:
npm ERR!     /usr/src/app/npm-debug.log

Can anyone help me.

thank you very much sincerely

OpenPAI Environment:

OpenPAI version: v0.8.2
OS (16.04.1 LTS (Xenial Xerus)):
Kernel (Linux pai-2 4.4.0-31-generic #50-Ubuntu SMP Wed Jul 13 00:07:12 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux):
Hardware (e.g. core:32, memory:30 GB, storage size: 203G ,):

**Comment by Gerhut** [comment]
Hi @dongluyang 

Could you please make sure that `yarn-frameworklauncher` started successfully?

**Comment by dongluyang** [comment]
ok, i see , the problem still is port is not opened,thank you very much
