### ISSUE TITLE
etcd cannot auto recover in case of data corruption

### ISSUE THREAD

**Issue by fanyangCS** [microsoft/pai#2126]
**Organization Name**: OpenPAI

**Short summary about the issue/question**: one etcd instance fails and is trapped in infinite crash recovery loop.

**Brief what process you are following**: 

**How to reproduce it**: 
corruption of etcd data

**OpenPAI Environment**: 
- OpenPAI version: 0.9.0
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Hardware (e.g. core number, memory size, storage size, GPU type etc.):
- Others:

**Anything else we need to know**:

**Comment by fanyangCS** [comment]
here is the log of etcd.

2019-02-02 07:32:32.972383 I | etcdmain: etcd Version: 3.2.17 
2019-02-02 07:32:32.972434 I | etcdmain: Git SHA: 28c47bb2f 
2019-02-02 07:32:32.972438 I | etcdmain: Go Version: go1.8.7 
2019-02-02 07:32:32.972441 I | etcdmain: Go OS/Arch: linux/amd64 
2019-02-02 07:32:32.972444 I | etcdmain: setting maximum number of CPUs to 16, total number of available CPUs is 16 
2019-02-02 07:32:32.972477 N | etcdmain: the server is already initialized as member before, starting as etcd member... 
2019-02-02 07:32:32.972523 I | embed: listening for peers on http://0.0.0.0:2380 
2019-02-02 07:32:32.972551 I | embed: listening for client requests on 0.0.0.0:4001 
2019-02-02 07:32:32.973554 I | etcdserver: name = etcdid3 
2019-02-02 07:32:32.973565 I | etcdserver: data dir = /var/etcd/data 
2019-02-02 07:32:32.973584 I | etcdserver: member dir = /var/etcd/data/member 
2019-02-02 07:32:32.973588 I | etcdserver: heartbeat = 100ms 
2019-02-02 07:32:32.973590 I | etcdserver: election = 1000ms 
2019-02-02 07:32:32.973593 I | etcdserver: snapshot count = 100000 
2019-02-02 07:32:32.973603 I | etcdserver: advertise client URLs = http://10.1.0.6:4001 
2019-02-02 07:32:32.973784 I | etcdserver: restarting member 981d16e74d5b93b0 in cluster 2a4e4334d3f30cc3 at commit index 0 
2019-02-02 07:32:32.973806 I | raft: 981d16e74d5b93b0 became follower at term 1 
2019-02-02 07:32:32.973813 I | raft: newRaft 981d16e74d5b93b0 [peers: [], term: 1, commit: 0, applied: 0, lastindex: 0, lastterm: 0] 
2019-02-02 07:32:32.978980 W | auth: simple token is not cryptographically signed 
2019-02-02 07:32:32.981649 I | etcdserver: starting server... [version: 3.2.17, cluster version: to_be_decided] 
2019-02-02 07:32:33.003083 I | raft: 981d16e74d5b93b0 [term: 1] received a MsgHeartbeat message with higher term from d626a147a331bb82 [term: 312] 
2019-02-02 07:32:33.003100 I | raft: 981d16e74d5b93b0 became follower at term 312 
2019-02-02 07:32:33.003139 C | raft: tocommit(10890480) is out of range [lastIndex(0)]. Was the raft log corrupted, truncated, or lost? 
panic: tocommit(10890480) is out of range [lastIndex(0)]. Was the raft log corrupted, truncated, or lost? 

goroutine 72 [running]: 
github.com/coreos/etcd/cmd/vendor/github.com/coreos/pkg/capnslog.(*PackageLogger).Panicf(0xc420174840, 0xfa963c, 0x5d, 0xc420277260, 0x2, 0x2) 
	/usr/local/google/home/jpbetz/Projects/etcd/src/github.com/coreos/etcd/release/etcd/gopath/src/github.com/coreos/etcd/cmd/vendor/github.com/coreos/pkg/capnslog/pkg_logger.go:75 +0x15c 
github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/raft.(*raftLog).commitTo(0xc420210930, 0xa62cf0) 
	/usr/local/google/home/jpbetz/Projects/etcd/src/github.com/coreos/etcd/release/etcd/gopath/src/github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/raft/log.go:191 +0x15c 
github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/raft.(*raft).handleHeartbeat(0xc4202721e0, 0x8, 0x981d16e74d5b93b0, 0xd626a147a331bb82, 0x138, 0x0, 0x0, 0x0, 0x0, 0x0, ...) 
	/usr/local/google/home/jpbetz/Projects/etcd/src/github.com/coreos/etcd/release/etcd/gopath/src/github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/raft/raft.go:1100 +0x54 
github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/raft.stepFollower(0xc4202721e0, 0x8, 0x981d16e74d5b93b0, 0xd626a147a331bb82, 0x138, 0x0, 0x0, 0x0, 0x0, 0x0, ...) 
	/usr/local/google/home/jpbetz/Projects/etcd/src/github.com/coreos/etcd/release/etcd/gopath/src/github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/raft/raft.go:1046 +0x2b3 
github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/raft.(*raft).Step(0xc4202721e0, 0x8, 0x981d16e74d5b93b0, 0xd626a147a331bb82, 0x138, 0x0, 0x0, 0x0, 0x0, 0x0, ...) 
	/usr/local/google/home/jpbetz/Projects/etcd/src/github.com/coreos/etcd/release/etcd/gopath/src/github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/raft/raft.go:778 +0x10f7 
github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/raft.(*node).run(0xc42018f260, 0xc4202721e0) 
	/usr/local/google/home/jpbetz/Projects/etcd/src/github.com/coreos/etcd/release/etcd/gopath/src/github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/raft/node.go:323 +0x67b 
created by github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/raft.RestartNode 
	/usr/local/google/home/jpbetz/Projects/etcd/src/github.com/coreos/etcd/release/etcd/gopath/src/github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/raft/node.go:223 +0x33e

**Comment by fanyangCS** [comment]
The script [etcdfix ](https://github.com/Microsoft/pai/blob/d26f762301f0de2efd263b84548f958b453d979b/deployment/k8sPaiLibrary/maintainlib/etcdfix.py)can mitigate this issue.

**Comment by fanyangCS** [comment]
need to add an alert to monitor the healthiness of etcd.

**Comment by ydye** [comment]
> 1.need to add an alert to monitor the healthiness of etcd.
> 2. please investigate whether the system can fix it automatically.

There is one thing that you should know. Etcd isn't a part of OpenPAI. It's a component of kubernetes. What's more, in my opinion, etcd is the base of kubernetes. I don't think OpenPAI should add alerts to monitor it.

**Comment by fanyangCS** [comment]
@ydye , that is a good point. For us, there are two cases.
1. for k8s deployed using our own code, we have to take care of it. this mainly includes on-premise case.
2. for k8s deployed by other solution like AKS. it is indeed not our obligation to detect the healthiness of k8s itself. we need think of the boundary of what PAI should do and what PAI should not do.

**Comment by fanyangCS** [comment]
https://github.com/microsoft/pai/pull/3307
