### ISSUE TITLE
YarnSchedulerBackend$YarnDriverEndpoint:54 - Disabling executor 9.

### ISSUE THREAD

**Issue by 784134748** [microsoft/pai#2512]
在/example/spark镜像内执行以下命令：
PYSPARK_PYTHON=/usr/bin/python3.5 /spark-example/spark-2.3.1-bin-hadoop2.7/bin/spark-submit   --master yarn --num-executors=2 --verbose /spark-example/spark-2.3.1-bin-hadoop2.7/examples/src/main/python/pi.py 1000

出现的错误如下：
2019-04-08 05:19:32 ERROR TransportClient:233 - Failed to send RPC 6459674793645256158 to /10.20.41.233:42200: java.nio.channels.ClosedChannelException
java.nio.channels.ClosedChannelException
	at io.netty.channel.AbstractChannel$AbstractUnsafe.write(...)(Unknown Source)
2019-04-08 05:19:32 INFO  BlockManagerMasterEndpoint:54 - Removing block manager BlockManagerId(2, 10.20.94.51, 37659, None)
2019-04-08 05:19:32 INFO  BlockManagerMaster:54 - Removed 2 successfully in removeExecutor
2019-04-08 05:19:32 INFO  DAGScheduler:54 - Shuffle files lost for executor: 2 (epoch 0)
2019-04-08 05:19:32 WARN  YarnSchedulerBackend$YarnSchedulerEndpoint:87 - Attempted to get executor loss reason for executor id 2 at RPC address 10.20.94.51:54978, but got no response. Marking as slave lost.
java.io.IOException: Failed to send RPC 6459674793645256158 to /10.20.41.233:42200: java.nio.channels.ClosedChannelException
	at org.apache.spark.network.client.TransportClient.lambda$sendRpc$2(TransportClient.java:237)
	at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:507)
	at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:481)
	at io.netty.util.concurrent.DefaultPromise.access$000(DefaultPromise.java:34)
	at io.netty.util.concurrent.DefaultPromise$1.run(DefaultPromise.java:431)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:403)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:463)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:138)
	at java.lang.Thread.run(Thread.java:748)
其中的RPC远程调用的的端口号为随机，请问该如何解决

**Comment by mzmssg** [comment]
Firstly, please check yarn log for the reason, is there following errors?
```
Container xxx is running beyond virtual memory limits. Current usage: xxx MB of 1 GB physical memory used; xxx of 2.1 GB virtual memory used.
```
If so, please follow this issue: https://issues.apache.org/jira/browse/YARN-4714

**Comment by 784134748** [comment]
> Firstly, please check yarn log for the reason, is there following errors?
> 
> ```
> Container xxx is running beyond virtual memory limits. Current usage: xxx MB of 1 GB physical memory used; xxx of 2.1 GB virtual memory used.
> ```
> If so, please follow this issue: https://issues.apache.org/jira/browse/YARN-4714

Log Type: stdout
Log Upload Time: Mon Apr 08 06:42:55 +0000 2019
Log Length: 7513
Showing 4096 bytes of 7513 total. Click here for the full log.
$HADOOP_MAPRED_HOME/share/hadoop/mapreduce/lib/*<CPS>{{PWD}}/__spark_conf__/__hadoop_conf__
    SPARK_YARN_STAGING_DIR -> hdfs://10.20.37.175:9000/user/admin/.sparkStaging/application_1554382769719_0030
    SPARK_USER -> admin
    PYTHONPATH -> {{PWD}}/pyspark.zip<CPS>{{PWD}}/py4j-0.10.7-src.zip

  command:
    {{JAVA_HOME}}/bin/java \ 
      -server \ 
      -Xmx1024m \ 
      -Djava.io.tmpdir={{PWD}}/tmp \ 
      '-Dspark.driver.port=43026' \ 
      -Dspark.yarn.app.container.log.dir=<LOG_DIR> \ 
      -XX:OnOutOfMemoryError='kill %p' \ 
      org.apache.spark.executor.CoarseGrainedExecutorBackend \ 
      --driver-url \ 
      spark://CoarseGrainedScheduler@10.20.94.51:43026 \ 
      --executor-id \ 
      <executorId> \ 
      --hostname \ 
      <hostname> \ 
      --cores \ 
      1 \ 
      --app-id \ 
      application_1554382769719_0030 \ 
      --user-class-path \ 
      file:$PWD/__app__.jar \ 
      1><LOG_DIR>/stdout \ 
      2><LOG_DIR>/stderr

  resources:
    pyspark.zip -> resource { scheme: "hdfs" host: "10.20.37.175" port: 9000 file: "/user/admin/.sparkStaging/application_1554382769719_0030/pyspark.zip" } size: 542919 timestamp: 1554705752999 type: FILE visibility: PRIVATE
    py4j-0.10.7-src.zip -> resource { scheme: "hdfs" host: "10.20.37.175" port: 9000 file: "/user/admin/.sparkStaging/application_1554382769719_0030/py4j-0.10.7-src.zip" } size: 42437 timestamp: 1554705753026 type: FILE visibility: PRIVATE
    __spark_libs__ -> resource { scheme: "hdfs" host: "10.20.37.175" port: 9000 file: "/user/admin/.sparkStaging/application_1554382769719_0030/__spark_libs__7090736666408697348.zip" } size: 235113920 timestamp: 1554705752586 type: ARCHIVE visibility: PRIVATE
    __spark_conf__ -> resource { scheme: "hdfs" host: "10.20.37.175" port: 9000 file: "/user/admin/.sparkStaging/application_1554382769719_0030/__spark_conf__.zip" } size: 219454 timestamp: 1554705753290 type: ARCHIVE visibility: PRIVATE

===============================================================================
2019-04-08 06:42:47 INFO  RMProxy:98 - Connecting to ResourceManager at /10.20.37.175:8030
2019-04-08 06:42:47 INFO  YarnRMClient:54 - Registering the ApplicationMaster
2019-04-08 06:42:47 INFO  YarnAllocator:54 - Will request 2 executor container(s), each with 1 core(s) and 1408 MB memory (including 384 MB of overhead)
2019-04-08 06:42:47 INFO  YarnAllocator:54 - Submitted 2 unlocalized container requests.
2019-04-08 06:42:47 INFO  ApplicationMaster:54 - Started progress reporter thread with (heartbeat : 3000, initial allocation : 200) intervals
2019-04-08 06:42:47 INFO  AMRMClientImpl:360 - Received new token for : 10.20.41.233:8041
2019-04-08 06:42:47 INFO  AMRMClientImpl:360 - Received new token for : 10.20.94.51:8041
2019-04-08 06:42:47 INFO  YarnAllocator:54 - Launching container container_e10_1554382769719_0030_02_000002 on host 10.20.94.51 for executor with ID 3
2019-04-08 06:42:47 INFO  YarnAllocator:54 - Launching container container_e10_1554382769719_0030_02_000003 on host 10.20.41.233 for executor with ID 4
2019-04-08 06:42:47 INFO  YarnAllocator:54 - Received 2 containers from YARN, launching executors on 2 of them.
2019-04-08 06:42:47 INFO  ContainerManagementProtocolProxy:81 - yarn.client.max-cached-nodemanagers-proxies : 0
2019-04-08 06:42:47 INFO  ContainerManagementProtocolProxy:81 - yarn.client.max-cached-nodemanagers-proxies : 0
2019-04-08 06:42:47 INFO  ContainerManagementProtocolProxy:260 - Opening proxy : 10.20.94.51:8041
2019-04-08 06:42:47 INFO  ContainerManagementProtocolProxy:260 - Opening proxy : 10.20.41.233:8041
2019-04-08 06:42:53 ERROR ApplicationMaster:43 - RECEIVED SIGNAL TERM
2019-04-08 06:42:53 INFO  ApplicationMaster:54 - Final app status: UNDEFINED, exitCode: 16, (reason: Shutdown hook called before final status was reported.)
2019-04-08 06:42:53 INFO  ApplicationMaster:54 - Unregistering ApplicationMaster with UNDEFINED (diag message: Shutdown hook called before final status was reported.)
2019-04-08 06:42:53 INFO  AMRMClientImpl:382 - Waiting for application to be successfully unregistered.

并没有发现你所提供的错误内容，因为每次调用的端口号是随机生成的，docker对外开放的端口为固定值。因此，可能还是端口无法请求导致的错误。
Attempted to get executor loss reason for executor id 2 at RPC address 10.20.94.51:54978, but got no response. Marking as slave lost.

**Comment by mzmssg** [comment]
Could you login to master node and get resource-manager container log. 
I think the reason might be the spark executors were killed when resource overused.

**Comment by fanyangCS** [comment]
close as no further response.
