### ISSUE TITLE
安装openapi报错

### ISSUE THREAD

**Issue by JuiYang** [Microsoft/pai#2645]
运行python paictl.py cluster k8s-bootup -p ~/pai-config报错：

```
Traceback (most recent call last):
  File "paictl.py", line 101, in <module>
    main(sys.argv[1:])
  File "paictl.py", line 93, in main
    parserd.handler(parserd)
  File "/pai/deployment/clusterCmd.py", line 44, in k8s_bootup
    k8s_util.maintain_cluster_k8s(com, option_name="deploy", clean=True)
  File "/pai/deployment/k8sPaiLibrary/maintainlib/k8s_util.py", line 34, in maintain_cluster_k8s
    job_instance.run()
  File "/pai/deployment/k8sPaiLibrary/maintainlib/deploy.py", line 206, in run
    self.job_executer(node_config, "{0}-deployment".format(role))
  File "/pai/deployment/k8sPaiLibrary/maintainlib/deploy.py", line 97, in job_executer
    if common.ssh_shell_with_password_input_paramiko(node_config, commandline) == False:
  File "/pai/deployment/k8sPaiLibrary/maintainlib/common.py", line 321, in ssh_shell_with_password_input_paramiko
    for response_msg in stdout:
  File "/usr/lib/python2.7/dist-packages/paramiko/file.py", line 102, in next
    line = self.readline()
  File "/usr/lib/python2.7/dist-packages/paramiko/file.py", line 270, in readline
    return line if self._flags & self.FLAG_BINARY else u(line)
  File "/usr/lib/python2.7/dist-packages/paramiko/py3compat.py", line 53, in u
    return s.decode(encoding)
  File "/usr/lib/python2.7/encodings/utf_8.py", line 16, in decode
    return codecs.utf_8_decode(input, errors, True)
UnicodeDecodeError: 'utf8' codec can't decode bytes in position 78-79: invalid continuation byte
```

**Comment by fanyangCS** [comment]
did you use Chinese characters in the setting like hostname, password, etc?

**Comment by scarlett2018** [comment]
@JuiYang thanks for submitting the question, may you fill in more info to help us understand the context?

Organization Name:

Short summary about the issue/question:

How to reproduce it:

OpenPAI Environment:
OpenPAI version:
Cloud provider or hardware configuration:
OS (e.g. from /etc/os-release):
Kernel (e.g. uname -a):
Hardware (e.g. core number, memory size, storage size, GPU type etc.):

Anything else we need to know:
