### ISSUE TITLE
job always fail due to no space left 

### ISSUE THREAD

**Issue by edenbuaa** [Microsoft/pai#2660]
**issue description**

**I try to submit jobs, but always get failed immediately. and the tracking page give the Diagnostics info as follows:**

Application application_1556071429753_0176 failed 2 times in previous 10000 milliseconds due to AM Container for appattempt_1556071429753_0176_000002 exited with exitCode: -1000
Failing this attempt.Diagnostics: [2019-04-24 10:41:30.121]No space available in any of the local directories.[2019-04-24 10:41:30.122]
For more detailed output, check the application tracking page: http://<master-ip>:8188/applicationhistory/app/application_1556071429753_0176 Then click on links to logs of each attempt.
. Failing the application.

I have changed the docker dir and hdfs data to disk which have enough space. so what's the reason?

**Comment by edenbuaa** [comment]
sometimes show this:

Application application_1556071429753_1699 failed 2 times in previous 10000 milliseconds due to Error launching appattempt_1556071429753_1699_000002. Got exception: org.apache.hadoop.yarn.exceptions.YarnException: java.io.IOException: org.iq80.leveldb.DBException: IO error: /var/lib/yarn/yarn-nm-recovery/yarn-nm-state/000021.log: No such file or directory
at org.apache.hadoop.yarn.ipc.RPCUtil.getRemoteException(RPCUtil.java:38)
at org.apache.hadoop.yarn.server.nodemanager.containermanager.ContainerManagerImpl.startContainers(ContainerManagerImpl.java:954)
at org.apache.hadoop.yarn.api.impl.pb.service.ContainerManagementProtocolPBServiceImpl.startContainers(ContainerManagementProtocolPBServiceImpl.java:101)
at org.apache.hadoop.yarn.proto.ContainerManagementProtocol$ContainerManagementProtocolService$2.callBlockingMethod(ContainerManagementProtocol.java:223)
at org.apache.hadoop.ipc.ProtobufRpcEngine$Server$ProtoBufRpcInvoker.call(ProtobufRpcEngine.java:503)
at org.apache.hadoop.ipc.RPC$Server.call(RPC.java:989)
at org.apache.hadoop.ipc.Server$RpcCall.run(Server.java:868)
at org.apache.hadoop.ipc.Server$RpcCall.run(Server.java:814)
at java.security.AccessController.doPrivileged(Native Method)
at javax.security.auth.Subject.doAs(Subject.java:422)
at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1886)
at org.apache.hadoop.ipc.Server$Handler.run(Server.java:2603)
Caused by: java.io.IOException: org.iq80.leveldb.DBException: IO error: /var/lib/yarn/yarn-nm-recovery/yarn-nm-state/000021.log: No such file or directory
at org.apache.hadoop.yarn.server.nodemanager.recovery.NMLeveldbStateStoreService.storeApplication(NMLeveldbStateStoreService.java:630)
at org.apache.hadoop.yarn.server.nodemanager.containermanager.ContainerManagerImpl.startContainerInternal(ContainerManagerImpl.java:1133)
at org.apache.hadoop.yarn.server.nodemanager.containermanager.ContainerManagerImpl.startContainers(ContainerManagerImpl.java:945)
... 10 more
Caused by: org.iq80.leveldb.DBException: IO error: /var/lib/yarn/yarn-nm-recovery/yarn-nm-state/000021.log: No such file or directory
at org.fusesource.leveldbjni.internal.JniDB.put(JniDB.java:129)
at org.fusesource.leveldbjni.internal.JniDB.put(JniDB.java:106)
at org.apache.hadoop.yarn.server.nodemanager.recovery.NMLeveldbStateStoreService.storeApplication(NMLeveldbStateStoreService.java:628)
... 12 more
Caused by: org.fusesource.leveldbjni.internal.NativeDB$DBException: IO error: /var/lib/yarn/yarn-nm-recovery/yarn-nm-state/000021.log: No such file or directory
at org.fusesource.leveldbjni.internal.NativeDB.checkStatus(NativeDB.java:200)
at org.fusesource.leveldbjni.internal.NativeDB.put(NativeDB.java:259)
at org.fusesource.leveldbjni.internal.NativeDB.put(NativeDB.java:254)
at org.fusesource.leveldbjni.internal.NativeDB.put(NativeDB.java:244)
at org.fusesource.leveldbjni.internal.JniDB.put(JniDB.java:126)
... 14 more
at sun.reflect.GeneratedConstructorAccessor90.newInstance(Unknown Source)
at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
at org.apache.hadoop.yarn.ipc.RPCUtil.instantiateException(RPCUtil.java:53)
at org.apache.hadoop.yarn.ipc.RPCUtil.instantiateYarnException(RPCUtil.java:75)
at org.apache.hadoop.yarn.ipc.RPCUtil.unwrapAndThrowException(RPCUtil.java:116)
at org.apache.hadoop.yarn.api.impl.pb.client.ContainerManagementProtocolPBClientImpl.startContainers(ContainerManagementProtocolPBClientImpl.java:131)
at sun.reflect.GeneratedMethodAccessor106.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.apache.hadoop.io.retry.RetryInvocationHandler.invokeMethod(RetryInvocationHandler.java:422)
at org.apache.hadoop.io.retry.RetryInvocationHandler$Call.invokeMethod(RetryInvocationHandler.java:165)
at org.apache.hadoop.io.retry.RetryInvocationHandler$Call.invoke(RetryInvocationHandler.java:157)
at org.apache.hadoop.io.retry.RetryInvocationHandler$Call.invokeOnce(RetryInvocationHandler.java:95)
at org.apache.hadoop.io.retry.RetryInvocationHandler.invoke(RetryInvocationHandler.java:359)
at com.sun.proxy.$Proxy89.startContainers(Unknown Source)
at org.apache.hadoop.yarn.server.resourcemanager.amlauncher.AMLauncher.launch(AMLauncher.java:123)
at org.apache.hadoop.yarn.server.resourcemanager.amlauncher.AMLauncher.run(AMLauncher.java:307)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
Caused by: org.apache.hadoop.ipc.RemoteException(org.apache.hadoop.yarn.exceptions.YarnException): java.io.IOException: org.iq80.leveldb.DBException: IO error: /var/lib/yarn/yarn-nm-recovery/yarn-nm-state/000021.log: No such file or directory
at org.apache.hadoop.yarn.ipc.RPCUtil.getRemoteException(RPCUtil.java:38)
at org.apache.hadoop.yarn.server.nodemanager.containermanager.ContainerManagerImpl.startContainers(ContainerManagerImpl.java:954)
at org.apache.hadoop.yarn.api.impl.pb.service.ContainerManagementProtocolPBServiceImpl.startContainers(ContainerManagementProtocolPBServiceImpl.java:101)
at org.apache.hadoop.yarn.proto.ContainerManagementProtocol$ContainerManagementProtocolService$2.callBlockingMethod(ContainerManagementProtocol.java:223)
at org.apache.hadoop.ipc.ProtobufRpcEngine$Server$ProtoBufRpcInvoker.call(ProtobufRpcEngine.java:503)
at org.apache.hadoop.ipc.RPC$Server.call(RPC.java:989)
at org.apache.hadoop.ipc.Server$RpcCall.run(Server.java:868)
at org.apache.hadoop.ipc.Server$RpcCall.run(Server.java:814)
at java.security.AccessController.doPrivileged(Native Method)
at javax.security.auth.Subject.doAs(Subject.java:422)
at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1886)
at org.apache.hadoop.ipc.Server$Handler.run(Server.java:2603)
Caused by: java.io.IOException: org.iq80.leveldb.DBException: IO error: /var/lib/yarn/yarn-nm-recovery/yarn-nm-state/000021.log: No such file or directory
at org.apache.hadoop.yarn.server.nodemanager.recovery.NMLeveldbStateStoreService.storeApplication(NMLeveldbStateStoreService.java:630)
at org.apache.hadoop.yarn.server.nodemanager.containermanager.ContainerManagerImpl.startContainerInternal(ContainerManagerImpl.java:1133)
at org.apache.hadoop.yarn.server.nodemanager.containermanager.ContainerManagerImpl.startContainers(ContainerManagerImpl.java:945)
... 10 more
Caused by: org.iq80.leveldb.DBException: IO error: /var/lib/yarn/yarn-nm-recovery/yarn-nm-state/000021.log: No such file or directory
at org.fusesource.leveldbjni.internal.JniDB.put(JniDB.java:129)
at org.fusesource.leveldbjni.internal.JniDB.put(JniDB.java:106)
at org.apache.hadoop.yarn.server.nodemanager.recovery.NMLeveldbStateStoreService.storeApplication(NMLeveldbStateStoreService.java:628)
... 12 more
Caused by: org.fusesource.leveldbjni.internal.NativeDB$DBException: IO error: /var/lib/yarn/yarn-nm-recovery/yarn-nm-state/000021.log: No such file or directory
at org.fusesource.leveldbjni.internal.NativeDB.checkStatus(NativeDB.java:200)
at org.fusesource.leveldbjni.internal.NativeDB.put(NativeDB.java:259)
at org.fusesource.leveldbjni.internal.NativeDB.put(NativeDB.java:254)
at org.fusesource.leveldbjni.internal.NativeDB.put(NativeDB.java:244)
at org.fusesource.leveldbjni.internal.JniDB.put(JniDB.java:126)
... 14 more
at org.apache.hadoop.ipc.Client.getRpcResponse(Client.java:1493)
at org.apache.hadoop.ipc.Client.call(Client.java:1439)
at org.apache.hadoop.ipc.Client.call(Client.java:1349)
at org.apache.hadoop.ipc.ProtobufRpcEngine$Invoker.invoke(ProtobufRpcEngine.java:227)
at org.apache.hadoop.ipc.ProtobufRpcEngine$Invoker.invoke(ProtobufRpcEngine.java:116)
at com.sun.proxy.$Proxy88.startContainers(Unknown Source)
at org.apache.hadoop.yarn.api.impl.pb.client.ContainerManagementProtocolPBClientImpl.startContainers(ContainerManagementProtocolPBClientImpl.java:128)
... 14 more
. Failing the application.

**Comment by scarlett2018** [comment]
@edenbuaa thanks for submitting the question, may you fill in more info to help us understand the context?

**Organization Name:

Short summary about the issue/question:

Brief what process you are following:

How to reproduce it:

OpenPAI Environment:

OpenPAI version:
Cloud provider or hardware configuration:
OS (e.g. from /etc/os-release):
Kernel (e.g. uname -a):
Hardware (e.g. core number, memory size, storage size, GPU type etc.):
Others:
Anything else we need to know:**

**Comment by edenbuaa** [comment]
@scarlett2018  thanks. It may be caused by hdfs block missing.
