### ISSUE TITLE
openpai 配置出问题

### ISSUE THREAD

**Issue by 425172555** [microsoft/pai#2683]
/usr/local/lib/python2.7/dist-packages/requests/__init__.py:83: RequestsDependencyWarning: Old version of cryptography ([1, 2, 3]) may cause slowdown.
  warnings.warn(warning, RequestsDependencyWarning)
/pai/deployment/paiLibrary/common/file_handler.py:37: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  cluster_data = yaml.load(f)
2019-04-28 03:07:18,382 [INFO] - deployment.clusterObjectModel.cluster_object_model : Begin to do pre-validation for each service parser.
2019-04-28 03:07:18,382 [INFO] - deployment.clusterObjectModel.cluster_object_model : Begin to do pre-validation of layout
2019-04-28 03:07:18,382 [INFO] - deployment.clusterObjectModel.cluster_object_model : Pre-validation of layout is passed
2019-04-28 03:07:18,382 [INFO] - deployment.clusterObjectModel.cluster_object_model : Begin to do pre-validation of kubernetes
2019-04-28 03:07:18,382 [INFO] - deployment.clusterObjectModel.cluster_object_model : Pre-validation of kubernetes is passed
2019-04-28 03:07:18,383 [INFO] - deployment.clusterObjectModel.cluster_object_model : Pre-validation is successful!
2019-04-28 03:07:18,383 [INFO] - deployment.clusterObjectModel.cluster_object_model : Begin to do generate cluster object model.
2019-04-28 03:07:18,383 [INFO] - deployment.clusterObjectModel.cluster_object_model : Begin to do generate object model of layout.
2019-04-28 03:07:18,383 [INFO] - deployment.clusterObjectModel.cluster_object_model : Object model of layout is generated.
2019-04-28 03:07:18,383 [INFO] - deployment.clusterObjectModel.cluster_object_model : Begin to do generate object model of kubernetes.
2019-04-28 03:07:18,383 [INFO] - deployment.clusterObjectModel.cluster_object_model : Object model of kubernetes is generated.
2019-04-28 03:07:18,383 [INFO] - deployment.clusterObjectModel.cluster_object_model : Cluster Object Model is generated.
2019-04-28 03:07:18,383 [INFO] - deployment.clusterObjectModel.cluster_object_model : Begin to do post-validation.
2019-04-28 03:07:18,383 [INFO] - deployment.clusterObjectModel.cluster_object_model : Begin to do post-validation of layout.
2019-04-28 03:07:18,384 [INFO] - deployment.clusterObjectModel.cluster_object_model : Post-validation of layout is passed.
2019-04-28 03:07:18,384 [INFO] - deployment.clusterObjectModel.cluster_object_model : Begin to do post-validation of kubernetes.
2019-04-28 03:07:18,384 [INFO] - deployment.clusterObjectModel.cluster_object_model : Post-validation of kubernetes is passed.
2019-04-28 03:07:18,384 [INFO] - deployment.clusterObjectModel.cluster_object_model : Post-validation is successful!
2019-04-28 03:07:18,384 [INFO] - deployment.clusterCmd : Begin to initialize PAI k8s cluster.
/pai/deployment/k8sPaiLibrary/maintainlib/common.py:42: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  file_data = yaml.load(f)
2019-04-28 03:07:18,399 [WARNING] - deployment.k8sPaiLibrary.maintainlib.deploy : Begin to deploy a new cluster to your machine or vm.
2019-04-28 03:07:18,399 [INFO] - deployment.k8sPaiLibrary.maintainlib.deploy : Begin to deploy k8s on host 10.120.139.72, the node role is [ master ]
2019-04-28 03:07:18,459 [INFO] - paramiko.transport : Connected (version 2.0, client OpenSSH_7.2p2)
/usr/lib/python2.7/dist-packages/Crypto/Cipher/blockalgo.py:141: FutureWarning: CTR mode needs counter parameter, not IV
  self._cipher = factory.new(key, *args, **kwargs)
2019-04-28 03:07:18,628 [INFO] - paramiko.transport : Authentication (password) successful!
2019-04-28 03:07:18,775 [INFO] - deployment.k8sPaiLibrary.maintainlib.common : Executing the command on host [10.120.139.72]: getent passwd ubuntu | cut -d: -f6
/home/ubuntu
2019-04-28 03:07:18,784 [INFO] - paramiko.transport : Connected (version 2.0, client OpenSSH_7.2p2)
2019-04-28 03:07:18,967 [INFO] - paramiko.transport : Authentication (password) successful!
********
[sudo] ubuntu 的密码： 
2019-04-28 03:07:19,204 [INFO] - paramiko.transport : Connected (version 2.0, client OpenSSH_7.2p2)
2019-04-28 03:07:19,366 [INFO] - paramiko.transport : Authentication (password) successful!
2019-04-28 03:07:19,548 [INFO] - paramiko.transport.sftp : [chan 0] Opened sftp connection (server version 3)
2019-04-28 03:07:19,558 [INFO] - paramiko.transport.sftp : [chan 0] sftp session closed.
2019-04-28 03:07:19,568 [INFO] - paramiko.transport : Connected (version 2.0, client OpenSSH_7.2p2)
2019-04-28 03:07:19,751 [INFO] - paramiko.transport : Authentication (password) successful!
2019-04-28 03:07:19,953 [INFO] - deployment.k8sPaiLibrary.maintainlib.common : Executing the command on host [10.120.139.72]: tar -xvf master-deployment.tar
master-deployment/docker-daemon.json
master-deployment/docker-config-update.py
master-deployment/docker-ce-install.sh
master-deployment/kubelet.sh
master-deployment/kubelet-start.sh
master-deployment/hosts-check.sh
master-deployment/etc/kubernetes/config
master-deployment/etc/kubernetes/manifests/scheduler.yaml
master-deployment/etc/kubernetes/manifests/controller-manager.yaml
master-deployment/etc/kubernetes/manifests/apiserver.yaml
master-deployment/etc/kubernetes/manifests/etcd.yaml
2019-04-28 03:07:19,973 [INFO] - paramiko.transport : Connected (version 2.0, client OpenSSH_7.2p2)
2019-04-28 03:07:20,155 [INFO] - paramiko.transport : Authentication (password) successful!
2019-04-28 03:07:20,357 [INFO] - deployment.k8sPaiLibrary.maintainlib.common : Executing the command on host [10.120.139.72]: sudo ./master-deployment/hosts-check.sh 10.120.139.72
********
[sudo] ubuntu 的密码： 
2019-04-28 03:07:20,397 [INFO] - paramiko.transport : Connected (version 2.0, client OpenSSH_7.2p2)
2019-04-28 03:07:20,579 [INFO] - paramiko.transport : Authentication (password) successful!
2019-04-28 03:07:20,778 [INFO] - deployment.k8sPaiLibrary.maintainlib.common : Executing the command on host [10.120.139.72]: sudo ./master-deployment/docker-ce-install.sh master-deployment
********
[sudo] ubuntu 的密码： 
python has been installed. And skip python install.
命中:1 http://cn.archive.ubuntu.com/ubuntu xenial InRelease                    
Traceback (most recent call last):
  File "paictl.py", line 101, in <module>
    main(sys.argv[1:])
  File "paictl.py", line 93, in main
    parserd.handler(parserd)
  File "/pai/deployment/clusterCmd.py", line 44, in k8s_bootup
    k8s_util.maintain_cluster_k8s(com, option_name="deploy", clean=True)
  File "/pai/deployment/k8sPaiLibrary/maintainlib/k8s_util.py", line 34, in maintain_cluster_k8s
    job_instance.run()
  File "/pai/deployment/k8sPaiLibrary/maintainlib/deploy.py", line 206, in run
    self.job_executer(node_config, "{0}-deployment".format(role))
  File "/pai/deployment/k8sPaiLibrary/maintainlib/deploy.py", line 97, in job_executer
    if common.ssh_shell_with_password_input_paramiko(node_config, commandline) == False:
  File "/pai/deployment/k8sPaiLibrary/maintainlib/common.py", line 321, in ssh_shell_with_password_input_paramiko
    for response_msg in stdout:
  File "/usr/lib/python2.7/dist-packages/paramiko/file.py", line 102, in next
    line = self.readline()
  File "/usr/lib/python2.7/dist-packages/paramiko/file.py", line 270, in readline
    return line if self._flags & self.FLAG_BINARY else u(line)
  File "/usr/lib/python2.7/dist-packages/paramiko/py3compat.py", line 53, in u
    return s.decode(encoding)
  File "/usr/lib/python2.7/encodings/utf_8.py", line 16, in decode
    return codecs.utf_8_decode(input, errors, True)
UnicodeDecodeError: 'utf8' codec can't decode byte 0xe8 in position 159: invalid continuation byte

配置无中文，还是报错utf8问题

**Comment by kunyao2015** [comment]
I met the same error

**Comment by JuiYang** [comment]
> I met the same error

python2.x需要修改decode(“utf8”,"ignore")方法

**Comment by scarlett2018** [comment]
Thanks Juiyang! 

@425172555 @kunyao2015 - does @JuiYang 's suggestion work for you? I'm closing this ticket as it has been 2 months. Please feel free to reopen it if you are still having problem and need more help.
