### ISSUE TITLE
GPU Utilization and GPU Memory always "No data points" in dashboard

### ISSUE THREAD

**Issue by leonfg** [microsoft/pai#2999]
**Organization Name**:

**Short summary about the issue/question**:
GPU Utilization and GPU Memory always "No data points" in dashboard
**Brief what process you are following**:
Run a job, after GPUs run, the dashboard will not update GPU Utilization and Memory informations.

[Distributed deploy](https://github.com/microsoft/pai/blob/master/docs/pai-management/doc/distributed-deploy.md)
Dev-box docker image + Driver 418.30:v0.11.0

**How to reproduce it**:
Run a job, after GPUs run, the dashboard will not update GPU Utilization and Memory informations.

**OpenPAI Environment**: 
- OpenPAI version: v0.12.0
- Cloud provider or hardware configuration: Two Workers and one master
- OS (e.g. from /etc/os-release): Ubuntu Server 16.04 
- Kernel (e.g. `uname -a`): 
Master: 4.4.0-142-generic
Worker: 4.4.0-150-generic
- Hardware (e.g. core number, memory size, storage size, GPU type etc.):
Worker: Xeon 6130 * 2, 256G Memory, 2080TI * 8
Master: Xeon 5118 * 2, 256G Memory, No GPU
- Others:
Restart PAI Service can not solve this problem.
iftop in job-exporter is OK. [1719](https://github.com/microsoft/pai/issues/1719)
**Anything else we need to know**:
Dashboard screenshot:
![](https://tva1.sinaimg.cn/large/007DFXDhgy1g4di65gsulj31i30u0ako.jpg)
GPU working screenshot:
![](https://tva1.sinaimg.cn/large/007DFXDhgy1g4di8e1kdej31i30u0qca.jpg)

**Comment by scarlett2018** [comment]
@leonfg - would mind share the Org info as well?

**Comment by leonfg** [comment]
> 
> 
> @leonfg - would mind share the Org info as well?

Yes but what is Org info?

**Comment by leonfg** [comment]
> 
> 
> @leonfg - would mind share the Org info as well?

Is that necessary?

**Comment by scarlett2018** [comment]
@leonfg - it's not mandatory, but as project's PM, I'd like to hold the usage info.  And contact to users whenever needed. I won't broadcast the info without any permissions from the org. if sharing it public is a concern, please drop me a private note with my email: scarli@microsoft.com, thanks.

**Comment by leonfg** [comment]
> 
> 
> @leonfg - it's not mandatory, but as project's PM, I'd like to hold the usage info. And contact to users whenever needed. I won't broadcast the info without any permissions from the org. if sharing it public is a concern, please drop me a private note with my email: [scarli@microsoft.com](mailto:scarli@microsoft.com), thanks.

Information Science Academy of China Electronics Technology Group Corporation

**Comment by leonfg** [comment]
> 
> 
> @leonfg - it's not mandatory, but as project's PM, I'd like to hold the usage info. And contact to users whenever needed. I won't broadcast the info without any permissions from the org. if sharing it public is a concern, please drop me a private note with my email: [scarli@microsoft.com](mailto:scarli@microsoft.com), thanks.

Is there any way for troubleshooting? E.g. checking any log, port, process.

**Comment by scarlett2018** [comment]
@leonfg - try out https://gitter.im/Microsoft/pai chat room to discuss with developer.

**Comment by ydye** [comment]
@leonfg Can you share us some log of job-exporter in your cluster?

**Comment by ydye** [comment]
> > @leonfg - it's not mandatory, but as project's PM, I'd like to hold the usage info. And contact to users whenever needed. I won't broadcast the info without any permissions from the org. if sharing it public is a concern, please drop me a private note with my email: [scarli@microsoft.com](mailto:scarli@microsoft.com), thanks.
> 
> Is there any way for troubleshooting? E.g. checking any log, port, process.

You can get service's log through k8s's dashboard to get the log of job-exporter.

**Comment by leonfg** [comment]
> 
> 
> > > @leonfg - it's not mandatory, but as project's PM, I'd like to hold the usage info. And contact to users whenever needed. I won't broadcast the info without any permissions from the org. if sharing it public is a concern, please drop me a private note with my email, thanks.
> > 
> > 
> > Is there any way for troubleshooting? E.g. checking any log, port, process.
> 
> You can get the log of job-exporter through k8s's dashboard.

```text
 
search
Search
日志
命名空间
default
容器日志 
job-exporter
 位于 
job-exporter-mfgdf
     
2019-07-03 17:07:06,452 - WARNING - container_collector - network.py:162 - unknown format of lsof ['node_expo', '23874', 'nobody', '5u', 'IPv6', '42544', '0t0', 'TCP', '192.168.16.19:9100-&gt;192.168.8.40:48228', '(ESTABLISHEDlsof:', 'no', 'pwd', 'entry', 'for', 'UID', '1000']
2019-07-03 17:07:23,594 - WARNING - container_collector - network.py:162 - unknown format of lsof ['node_expo', '23874', 'nobody', '5u', 'IPv6', '42544', '0t0', 'TCP', '192.168.16.19:9100-&gt;192.168.8.40:48228', '(ESTABLISHEDlsof:', 'no', 'pwd', 'entry', 'for', 'UID', '1000']
2019-07-03 17:07:24,074 - WARNING - container_collector - network.py:162 - unknown format of lsof ['node_expo', '23874', 'nobody', '5u', 'IPv6', '42544', '0t0', 'TCP', '192.168.16.19:9100-&gt;192.168.8.40:48228', '(ESTABLISHEDlsof:', 'no', 'pwd', 'entry', 'for', 'UID', '1000']
2019-07-03 17:07:25,079 - WARNING - container_collector - network.py:162 - unknown format of lsof ['node_expo', '23874', 'nobody', '5u', 'IPv6', '42544', '0t0', 'TCP', '192.168.16.19:9100-&gt;192.168.8.40:48228', '(ESTABLISHEDlsof:', 'no', 'pwd', 'entry', 'for', 'UID', '1000']
2019-07-03 17:07:26,164 - WARNING - container_collector - network.py:162 - unknown format of lsof ['node_expo', '23874', 'nobody', '5u', 'IPv6', '42544', '0t0', 'TCP', '192.168.16.19:9100-&gt;192.168.8.40:48228', '(ESTABLISHEDlsof:', 'no', 'pwd', 'entry', 'for', 'UID', '1000']
WARNING: No swap limit support
2019-07-03 17:07:35,889 - ERROR - gpu_collector - nvidia.py:172 - exec nvidia-smi error
Traceback (most recent call last):
  File "/job_exporter/nvidia.py", line 165, in nvidia_smi
    return parse_smi_xml_result(smi_output)
  File "/job_exporter/nvidia.py", line 134, in parse_smi_xml_result
    single = volatile.getElementsByTagName("single_bit")[0].getElementsByTagName("total")[0]
IndexError: list index out of range
2019-07-03 17:07:42,887 - WARNING - container_collector - network.py:162 - unknown format of lsof ['node_expo', '23874', 'nobody', '5u', 'IPv6', '42544', '0t0', 'TCP', '192.168.16.19:9100-&gt;192.168.8.40:48228', '(ESTABLISHEDlsof:', 'no', 'pwd', 'entry', 'for', 'UID', '1000']
2019-07-03 17:07:43,497 - WARNING - container_collector - network.py:162 - unknown format of lsof ['node_expo', '23874', 'nobody', '5u', 'IPv6', '42544', '0t0', 'TCP', '192.168.16.19:9100-&gt;192.168.8.40:48228', '(ESTABLISHEDlsof:', 'no', 'pwd', 'entry', 'for', 'UID', '1000']
2019-07-03 17:07:44,717 - WARNING - container_collector - network.py:162 - unknown format of lsof ['node_expo', '23874', 'nobody', '5u', 'IPv6', '42544', '0t0', 'TCP', '192.168.16.19:9100-&gt;192.168.8.40:48228', '(ESTABLISHEDlsof:', 'no', 'pwd', 'entry', 'for', 'UID', '1000']
2019-07-03 17:07:46,032 - WARNING - container_collector - network.py:162 - unknown format of lsof ['node_expo', '23874', 'nobody', '5u', 'IPv6', '42544', '0t0', 'TCP', '192.168.16.19:9100-&gt;192.168.8.40:48228', '(ESTABLISHEDlsof:', 'no', 'pwd', 'entry', 'for', 'UID', '1000']
WARNING: No swap limit support
2019-07-03 17:08:03,036 - WARNING - container_collector - network.py:162 - unknown format of lsof ['node_expo', '23874', 'nobody', '5u', 'IPv6', '42544', '0t0', 'TCP', '192.168.16.19:9100-&gt;192.168.8.40:48228', '(ESTABLISHEDlsof:', 'no', 'pwd', 'entry', 'for', 'UID', '1000']
2019-07-03 17:08:03,504 - WARNING - container_collector - network.py:162 - unknown format of lsof ['node_expo', '23874', 'nobody', '5u', 'IPv6', '42544', '0t0', 'TCP', '192.168.16.19:9100-&gt;192.168.8.40:48228', '(ESTABLISHEDlsof:', 'no', 'pwd', 'entry', 'for', 'UID', '1000']
2019-07-03 17:08:04,664 - WARNING - container_collector - network.py:162 - unknown format of lsof ['node_expo', '23874', 'nobody', '5u', 'IPv6', '42544', '0t0', 'TCP', '192.168.16.19:9100-&gt;192.168.8.40:48228', '(ESTABLISHEDlsof:', 'no', 'pwd', 'entry', 'for', 'UID', '1000']
2019-07-03 17:08:05,990 - WARNING - container_collector - network.py:162 - unknown format of lsof ['node_expo', '23874', 'nobody', '5u', 'IPv6', '42544', '0t0', 'TCP', '192.168.16.19:9100-&gt;192.168.8.40:48228', '(ESTABLISHEDlsof:', 'no', 'pwd', 'entry', 'for', 'UID', '1000']
2019-07-03 17:08:06,713 - ERROR - gpu_collector - nvidia.py:172 - exec nvidia-smi error
Traceback (most recent call last):
  File "/job_exporter/nvidia.py", line 165, in nvidia_smi
    return parse_smi_xml_result(smi_output)
  File "/job_exporter/nvidia.py", line 134, in parse_smi_xml_result
    single = volatile.getElementsByTagName("single_bit")[0].getElementsByTagName("total")[0]
IndexError: list index out of range
2019-07-03 17:08:23,190 - WARNING - container_collector - network.py:162 - unknown format of lsof ['node_expo', '23874', 'nobody', '5u', 'IPv6', '42544', '0t0', 'TCP', '192.168.16.19:9100-&gt;192.168.8.40:48228', '(ESTABLISHEDlsof:', 'no', 'pwd', 'entry', 'for', 'UID', '1000']
2019-07-03 17:08:23,854 - WARNING - container_collector - network.py:162 - unknown format of lsof ['node_expo', '23874', 'nobody', '5u', 'IPv6', '42544', '0t0', 'TCP', '192.168.16.19:9100-&gt;192.168.8.40:48228', '(ESTABLISHEDlsof:', 'no', 'pwd', 'entry', 'for', 'UID', '1000']
2019-07-03 17:08:24,979 - WARNING - container_collector - network.py:162 - unknown format of lsof ['node_expo', '23874', 'nobody', '5u', 'IPv6', '42544', '0t0', 'TCP', '192.168.16.19:9100-&gt;192.168.8.40:48228', '(ESTABLISHEDlsof:', 'no', 'pwd', 'entry', 'for', 'UID', '1000']
2019-07-03 17:08:26,213 - WARNING - container_collector - network.py:162 - unknown format of lsof ['node_expo', '23874', 'nobody', '5u', 'IPv6', '42544', '0t0', 'TCP', '192.168.16.19:9100-&gt;192.168.8.40:48228', '(ESTABLISHEDlsof:', 'no', 'pwd', 'entry', 'for', 'UID', '1000']
WARNING: No swap limit support
2019-07-03 17:08:37,527 - ERROR - gpu_collector - nvidia.py:172 - exec nvidia-smi error
Traceback (most recent call last):
  File "/job_exporter/nvidia.py", line 165, in nvidia_smi
    return parse_smi_xml_result(smi_output)
  File "/job_exporter/nvidia.py", line 134, in parse_smi_xml_result
    single = volatile.getElementsByTagName("single_bit")[0].getElementsByTagName("total")[0]
IndexError: list index out of range
2019-07-03 17:08:43,394 - WARNING - container_collector - network.py:162 - unknown format of lsof ['node_expo', '23874', 'nobody', '5u', 'IPv6', '42544', '0t0', 'TCP', '192.168.16.19:9100-&gt;192.168.8.40:48228', '(ESTABLISHEDlsof:', 'no', 'pwd', 'entry', 'for', 'UID', '1000']
2019-07-03 17:08:43,975 - WARNING - container_collector - network.py:162 - unknown format of lsof ['node_expo', '23874', 'nobody', '5u', 'IPv6', '42544', '0t0', 'TCP', '192.168.16.19:9100-&gt;192.168.8.40:48228', '(ESTABLISHEDlsof:', 'no', 'pwd', 'entry', 'for', 'UID', '1000']
2019-07-03 17:08:45,239 - WARNING - container_collector - network.py:162 - unknown format of lsof ['node_expo', '23874', 'nobody', '5u', 'IPv6', '42544', '0t0', 'TCP', '192.168.16.19:9100-&gt;192.168.8.40:48228', '(ESTABLISHEDlsof:', 'no', 'pwd', 'entry', 'for', 'UID', '1000']
2019-07-03 17:08:46,418 - WARNING - container_collector - network.py:162 - unknown format of lsof ['node_expo', '23874', 'nobody', '5u', 'IPv6', '42544', '0t0', 'TCP', '192.168.16.19:9100-&gt;192.168.8.40:48228', '(ESTABLISHEDlsof:', 'no', 'pwd', 'entry', 'for', 'UID', '1000']
WARNING: No swap limit support
2019-07-03 17:09:03,631 - WARNING - container_collector - network.py:162 - unknown format of lsof ['node_expo', '23874', 'nobody', '5u', 'IPv6', '42544', '0t0', 'TCP', '192.168.16.19:9100-&gt;192.168.8.40:48228', '(ESTABLISHEDlsof:', 'no', 'pwd', 'entry', 'for', 'UID', '1000']
2019-07-03 17:09:04,206 - WARNING - container_collector - network.py:162 - unknown format of lsof ['node_expo', '23874', 'nobody', '5u', 'IPv6', '42544', '0t0', 'TCP', '192.168.16.19:9100-&gt;192.168.8.40:48228', '(ESTABLISHEDlsof:', 'no', 'pwd', 'entry', 'for', 'UID', '1000']
2019-07-03 17:09:05,424 - WARNING - container_collector - network.py:162 - unknown format of lsof ['node_expo', '23874', 'nobody', '5u', 'IPv6', '42544', '0t0', 'TCP', '192.168.16.19:9100-&gt;192.168.8.40:48228', '(ESTABLISHEDlsof:', 'no', 'pwd', 'entry', 'for', 'UID', '1000']
2019-07-03 17:09:06,531 - WARNING - container_collector - network.py:162 - unknown format of lsof ['node_expo', '23874', 'nobody', '5u', 'IPv6', '42544', '0t0', 'TCP', '192.168.16.19:9100-&gt;192.168.8.40:48228', '(ESTABLISHEDlsof:', 'no', 'pwd', 'entry', 'for', 'UID', '1000']
2019-07-03 17:09:08,323 - ERROR - gpu_collector - nvidia.py:172 - exec nvidia-smi error
Traceback (most recent call last):
  File "/job_exporter/nvidia.py", line 165, in nvidia_smi
    return parse_smi_xml_result(smi_output)
  File "/job_exporter/nvidia.py", line 134, in parse_smi_xml_result
    single = volatile.getElementsByTagName("single_bit")[0].getElementsByTagName("total")[0]
IndexError: list index out of range
2019-07-03 17:09:23,770 - WARNING - container_collector - network.py:162 - unknown format of lsof ['node_expo', '23874', 'nobody', '5u', 'IPv6', '42544', '0t0', 'TCP', '192.168.16.19:9100-&gt;192.168.8.40:48228', '(ESTABLISHEDlsof:', 'no', 'pwd', 'entry', 'for', 'UID', '1000']
2019-07-03 17:09:24,442 - WARNING - container_collector - network.py:162 - unknown format of lsof ['node_expo', '23874', 'nobody', '5u', 'IPv6', '42544', '0t0', 'TCP', '192.168.16.19:9100-&gt;192.168.8.40:48228', '(ESTABLISHEDlsof:', 'no', 'pwd', 'entry', 'for', 'UID', '1000']
2019-07-03 17:09:25,558 - WARNING - container_collector - network.py:162 - unknown format of lsof ['node_expo', '23874', 'nobody', '5u', 'IPv6', '42544', '0t0', 'TCP', '192.168.16.19:9100-&gt;192.168.8.40:48228', '(ESTABLISHEDlsof:', 'no', 'pwd', 'entry', 'for', 'UID', '1000']
2019-07-03 17:09:26,810 - WARNING - container_collector - network.py:162 - unknown format of lsof ['node_expo', '23874', 'nobody', '5u', 'IPv6', '42544', '0t0', 'TCP', '192.168.16.19:9100-&gt;192.168.8.40:48228', '(ESTABLISHEDlsof:', 'no', 'pwd', 'entry', 'for', 'UID', '1000']
WARNING: No swap limit support
2019-07-03 17:09:39,150 - ERROR - gpu_collector - nvidia.py:172 - exec nvidia-smi error
Traceback (most recent call last):
  File "/job_exporter/nvidia.py", line 165, in nvidia_smi
    return parse_smi_xml_result(smi_output)
  File "/job_exporter/nvidia.py", line 134, in parse_smi_xml_result
    single = volatile.getElementsByTagName("single_bit")[0].getElementsByTagName("total")[0]
IndexError: list index out of range
WARNING: No swap limit support
2019-07-03 17:10:10,006 - ERROR - gpu_collector - nvidia.py:172 - exec nvidia-smi error
Traceback (most recent call last):
  File "/job_exporter/nvidia.py", line 165, in nvidia_smi
    return parse_smi_xml_result(smi_output)
  File "/job_exporter/nvidia.py", line 134, in parse_smi_xml_result
    single = volatile.getElementsByTagName("single_bit")[0].getElementsByTagName("total")[0]
IndexError: list index out of range
WARNING: No swap limit support
2019-07-03 17:10:40,841 - ERROR - gpu_collector - nvidia.py:172 - exec nvidia-smi error
Traceback (most recent call last):
  File "/job_exporter/nvidia.py", line 165, in nvidia_smi
    return parse_smi_xml_result(smi_output)
  File "/job_exporter/nvidia.py", line 134, in parse_smi_xml_result
    single = volatile.getElementsByTagName("single_bit")[0].getElementsByTagName("total")[0]
IndexError: list index out of range
WARNING: No swap limit support
2019-07-03 17:11:11,801 - ERROR - gpu_collector - nvidia.py:172 - exec nvidia-smi error
Traceback (most recent call last):
  File "/job_exporter/nvidia.py", line 165, in nvidia_smi
    return parse_smi_xml_result(smi_output)
  File "/job_exporter/nvidia.py", line 134, in parse_smi_xml_result
    single = volatile.getElementsByTagName("single_bit")[0].getElementsByTagName("total")[0]
IndexError: list index out of range
WARNING: No swap limit support
日志范围从 7/3/19 5:07 PM 到 7/3/19 5:11 PM UTC
 
 
 ```
It seems nvidia-smi failed. But jobs are OK.

**Comment by abuccts** [comment]
@leonfg It's a parsing error in job exporter.
Could you share your GPU type and an output of `nvidia-smi`? Thanks.
