### ISSUE TITLE
rest-server container startup failure

### ISSUE THREAD

**Issue by EthanSheng405** [microsoft/pai#3127]
&gt; pai-rest-server@0.0.0 start /usr/src/app
&gt; node index.js
 fs.js:646
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^
 Error: ENOENT: no such file or directory, open '/job-exit-spec-configuration/job-exit-spec.yaml'
    at Object.fs.openSync (fs.js:646:18)
    at Object.fs.readFileSync (fs.js:551:33)
    at Object.&lt;anonymous&gt; (/usr/src/app/src/models/job.js:48:39)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! pai-rest-server@0.0.0 start: `node index.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the pai-rest-server@0.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
 npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2019-07-09T07_43_42_154Z-debug.log

The container has crashed and restarted, and I cannot view the log file in the path shown above

**Comment by EthanSheng405** [comment]
All the other containers have started properly, only this one has reported an error,This prevented me from logging into openpai's dashboard

**Comment by lvyufeng** [comment]
how do you fix this problem?
