### ISSUE TITLE
HDFS No such file or directory

### ISSUE THREAD

**Issue by Davidham3** [microsoft/pai#3239]
I deploy OpenPAI on four GPU machines, and I install vscode openpai extension on two different devices, one is my laptop, the other one is a remote linux server. I found the jobs submitted from my laptop can run successfully, but the jobs submitted from the remote linux server run failed. The exit Diagnostics info is listed below:

```
[Exit Trigger Info]

ExitTriggerMessage: FailedTaskCount 1 has reached MinFailedTaskCount 1 in TaskRole [task]
ExitTriggerTaskRole: task
ExitTriggerTaskIndex: 0
UserExitCode: 1

--------------------------------------------------------------------------------

[Exit Spec]

code: 255
phrase: CONTAINER_RUNTIME_UNKNOWN_FAILURE
issuer: PAI_RUNTIME
causer: UNKNOWN
type: UNKNOWN_FAILURE
stage: COMPLETING
behavior: UNKNOWN
reaction: RETRY_TO_MAX
reason: Container failed but the failure cannot be recognized by PAI Runtime
repro:
  - User program directly exits with exitcode 1
solution:
  - Check container log and find root cause
  - Wait result from next retry


--------------------------------------------------------------------------------

[Exit Diagnostics]

[2019-07-22 09:24:21.707]Exception from container-launch: 
ExitCodeException exitCode=255: 
	at org.apache.hadoop.util.Shell.runCommand(Shell.java:998)
	at org.apache.hadoop.util.Shell.run(Shell.java:884)
	at org.apache.hadoop.util.Shell$ShellCommandExecutor.execute(Shell.java:1216)
	at org.apache.hadoop.yarn.server.nodemanager.DockerContainerExecutor.launchContainer(DockerContainerExecutor.java:312)
	at org.apache.hadoop.yarn.server.nodemanager.containermanager.launcher.ContainerLaunch.launchContainer(ContainerLaunch.java:443)
	at org.apache.hadoop.yarn.server.nodemanager.containermanager.launcher.ContainerLaunch.call(ContainerLaunch.java:294)
	at org.apache.hadoop.yarn.server.nodemanager.containermanager.launcher.ContainerLaunch.call(ContainerLaunch.java:92)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

[2019-07-22 09:24:21.707]
[2019-07-22 09:24:21.708]Container exited with a non-zero exit code 255. Last 40960 bytes of runtime.pai.agg.error :
[PAI_RUNTIME_ERROR_START]
exitcode: 255
trigger: 
reason: |
  
solution: |
  
originalUserExitCode: 1
dockerStatus: 
caughtSignal: 
caughtException:
matchedUserLogString:
errorLogs:
  user: |
  runtime: |
    stat: `hdfs://172.31.246.52:9000/TestUser/STHGCN_490680d3': No such file or directory
    1563787461 INFO USER_EXIT_CODE 1
  diskCleaner: |
[PAI_RUNTIME_ERROR_END]

[2019-07-22 09:24:21.709]
```

And I tried to submit job from the web page, the problem is same as the jobs submitted from the remote server. Can anyone help me solve this problem? Thanks!

**Comment by Davidham3** [comment]
I retried submit from web page, remove codeDir, dataDir, and outputDir, and it runs successfully. 
And then I remove there keys in json file and submit it on the remove linux server, it runs successfully too. So I think maybe the openpai extension can't acquire the environment variables like $PAI_DEFAULT_FS_URI, so it can't create the folder for my job.

**Comment by fanyangCS** [comment]
@yiyione ?

**Comment by mzmssg** [comment]
Could you provide the job log? As you said, the submission from webportal have the same issue, so it might not caused by extension, but by runtime?
Anyway, detailed log could help address it.

**Comment by fanyangCS** [comment]
closed as no response.
