### ISSUE TITLE
[Bug]Number of gpu is incorrect without reason

### ISSUE THREAD

**Issue by edenbuaa** [microsoft/pai#3537]
PAI Version: v0.11.0
Driver Version: 410.73
I have a cluster which has 3 nodes (2x v100 in each one). deploy successed, The dashboard shows 3 work nodes, but only 4 gpus in total. The hardware page shows N/A GPU in one work node. The k8s dashboard didn't report any error. 
the logs in job-exporter container show this:
...
```
- ERROR - gpu_collector -nvidia.py:168 - command  '['/var/drivers/nvidia/current/bin/nvidia-smi', '-q', '-x']' return with error (code 9): b"NVIDIA-SMI has failed because it couldn't communicate with the NVIDIA driver. Make sure that the lastest NVIDIA driver is installed and running. \n\n"
Traceback (most recent call last):
   File "/job_exporter/nvidia.py", line 163, in nvidia_smi
      histogram=histogram, timeout=timeout)
   File "/job_exporter/utils.py", line 37, in exec_cmd
      return subprocess.check_output(*args, **kwargs).decode("utf-8")
   File "/usr/local/lib/python3.7/subprocess.py", line 395, in check_output
      **kwargs).stdout
   File "/usr/local/lib/python3.7/subprocess.py", line 487, in run
     output=stdout, stderr=stderr)
subporcess.CalledProcessError: Command '[' /var/drivers/nvidia/current/bin/nvidia-smi', '-q', '-x']' returned non-zero exit status 9.
```
...
logs in driver-one-shot:
...
```
+ echo NVIDIA gpu not detected, skipping driver installation
NVIDIA gpu not detected, skipping driver installation
+ lspci
+ grep -qE '(Network|Infiniband) controller.*mellanox.*ConnectX'
+ echo Infiniband hardware is not detected, skipping driver installation
Infiniband hardware is not detected, skipping driver installation
+mkdir -p /jobstatus
+ touch /jobstatus/jobok
+ true
+ sleep 1000
```

logs in /var/log/drivers/nvidia-installer.log:
...
```
WARNING: Unable to determine the path to install the libglvnd EGL verndor library config files. Check that you have pkg-config and the libglvnd development libraries installed, or specify a path with --glvnd-egl-config-path.
Will install libEGL vendor library config file to /usr/share/glvnd/egl_vendor.d
-> Searching for conflicting files:
-> done.
-> Installing 'NVIDIA Accelerated Graphics Driver for Linux-x86_64' (410.73):
     executing: '/sbin/ldconfig'...
-> done.
-> Driver file installation is omplete.
-> Installing DKMS kernel module:
-> done.
-> Running post-install sanity check:
-> done.
-> Post-install sanity check passed.
-> Running runtime sanity check:
-> done.
-> Runtime sanity check passed.
-> Installation of the kernel module for the NVIDIA Accelerated Graphics Driver for Linux-x86_64(version 410.73) is now complete.
```

any suggestion? thanks.

**Comment by abuccts** [comment]
> \+ echo NVIDIA gpu not detected, skipping driver installation
> NVIDIA gpu not detected, skipping driver installation

You didn't install NVIDIA drivers on that node, what's the output of `lspci | grep NVIDIA`?

**Comment by edenbuaa** [comment]
output nothing.  I installed nvidia runtime on this machine.

**Comment by abuccts** [comment]
> output nothing. I installed nvidia runtime on this machine.

It means there's no NVIDIA device connected to PCI buses on that machine.
You can install nvidia-runtime without GPU but cannot run container with it.

**Comment by edenbuaa** [comment]
ok, got it , thanks.
