### ISSUE TITLE
paramiko sshclient报错

### ISSUE THREAD

**Issue by HistoryGift** [microsoft/pai#3753]
执行python paictl.py config generate -i /pai/deployment/quick-start/quick-start.yaml -o ~/pai-config –f
报错：
Traceback (most recent call last):
  File "paictl.py", line 101, in <module>
    main(sys.argv[1:])
  File "paictl.py", line 93, in main
    parserd.handler(parserd)
  File "/opt/pai/deployment/configCmd.py", line 169, in generate_configuration
    args.force)
  File "/opt/pai/deployment/configCmd.py", line 77, in generate_configuration
    "cat /etc/resolv.conf | grep nameserver | cut -d ' ' -f 2 | head -n 1")
  File "/opt/pai/deployment/k8sPaiLibrary/maintainlib/common.py", line 259, in ssh_shell_paramiko_with_result
    ssh.connect(hostname=hostip, port=port, key_filename=key_filename, username=username, password=password)
  File "/usr/lib/python2.7/site-packages/paramiko/client.py", line 406, in connect
    t.start_client(timeout=timeout)
  File "/usr/lib/python2.7/site-packages/paramiko/transport.py", line 660, in start_client
    raise e
TypeError: from_buffer() cannot return the address of the raw string within a str or unicode or bytearray object

定位到pai/deployment/k8sPaiLibrary/maintainlib/common.py 中的sshclient代码报出异常

我的paramiko=2.6.0  python=2.7.5
请问： 我的python 是要变成python3.X ?

**Comment by HistoryGift** [comment]
找到原因了，paramiko 依赖的一个模块文件失效了，重新安装就好了

**Comment by AprLie** [comment]
> 找到原因了，paramiko 依赖的一个模块文件失效了，重新安装就好了

请问是安装的哪一个呀?
