### ISSUE TITLE
K8S-dashboard judge whether the ssl certs is provided based on rbac enable or not.

### ISSUE THREAD

**Issue by ydye** [microsoft/pai#4107]
```

Traceback (most recent call last):
  File "/pai/deployment/paiLibrary/paiService/service_template_generate.py", line 113, in generate_template
    generated_template = template_handler.generate_from_template_dict(template_data, service_conf_dict)
  File "/pai/deployment/paiLibrary/common/template_handler.py", line 28, in generate_from_template_dict
    map_table
  File "/usr/lib/python2.7/dist-packages/jinja2/environment.py", line 989, in render
    return self.environment.handle_exception(exc_info, True)
  File "/usr/lib/python2.7/dist-packages/jinja2/environment.py", line 754, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "<template>", line 24, in top-level template code
  File "/usr/lib/python2.7/dist-packages/jinja2/environment.py", line 389, in getitem
    return obj[argument]
UndefinedError: 'dict object' has no attribute 'ssl'
2020-01-06 07:52:59,218 [ERROR] - deployment.paiLibrary.paiService.service_management_start : Some error occurs when starting service k8s-dashboard
Traceback (most recent call last):
  File "/pai/deployment/paiLibrary/paiService/service_management_start.py", line 85, in start
    service_template_generater.run()
  File "/pai/deployment/paiLibrary/paiService/service_template_generate.py", line 128, in run
    self.generate_template()
  File "/pai/deployment/paiLibrary/paiService/service_template_generate.py", line 116, in generate_template
    raise e
UndefinedError: 'dict object' has no attribute 'ssl'
```

**Comment by ydye** [comment]
#4109
