### ISSUE TITLE
add data source HDFS

### ISSUE THREAD

**Issue by qingdo** [microsoft/pai#4364]
**Organization Name**:

**Short summary about the issue/question**: Error message when I tried use HDFS location as data source

**Brief what process you are following**:

This issue happens when we try to use an **HDFS** folder as **OpenPAI** data source. 
![image](https://user-images.githubusercontent.com/15830408/78526188-16cfcd00-778e-11ea-9e75-2feabf606656.png)
 Then openpai will automatically insert the following command into the **.yaml** file before any other commands. 

>    commands:
      - '`#CUSTOM_STORAGE_START`'
      - '`#Auto generated code, please do not modify`'
      - >-
        pip install hdfs &>> storage_plugin.log && touch ~/.hdfscli.cfg && echo
        '[dev.alias]' >> ~/.hdfscli.cfg && echo 'url = http://some.ip.address.here:50070'
        >> ~/.hdfscli.cfg
      - >-
        if [ ! -d /pai_data/data ]; then mkdir --parents /pai_data/data; fi &>>
        storage_plugin.log
      - hdfscli download --alias=dev /data /pai_data/data
      - '`#CUSTOM_STORAGE_END`'

I believe the error is in the last command. Here is the full error message. 

> ERROR	Error while downloading. Attempting cleanup.
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/hdfs/client.py", line 814, in download
    _map_async(n_threads, _download, fpath_tuples)
  File "/usr/local/lib/python3.6/dist-packages/hdfs/client.py", line 1179, in _map_async
    pool = ThreadPool(pool_size)
  File "/usr/lib/python3.6/multiprocessing/pool.py", line 789, in __init__
    Pool.__init__(self, processes, initializer, initargs)
  File "/usr/lib/python3.6/multiprocessing/pool.py", line 174, in __init__
    self._repopulate_pool()
  File "/usr/lib/python3.6/multiprocessing/pool.py", line 239, in _repopulate_pool
    w.start()
  File "/usr/lib/python3.6/multiprocessing/dummy/__init__.py", line 48, in start
    threading.Thread.start(self)
  File "/usr/lib/python3.6/threading.py", line 846, in start
    _start_new_thread(self._bootstrap, ())
RuntimeError: can't start new thread
ERROR	Unable to cleanup temporary folder.
ERROR	Unexpected exception.
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/hdfs/config.py", line 195, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/hdfs/__main__.py", line 233, in main
    progress=progress,
  File "/usr/local/lib/python3.6/dist-packages/hdfs/client.py", line 825, in download
    raise err
  File "/usr/local/lib/python3.6/dist-packages/hdfs/client.py", line 814, in download
    _map_async(n_threads, _download, fpath_tuples)
  File "/usr/local/lib/python3.6/dist-packages/hdfs/client.py", line 1179, in _map_async
    pool = ThreadPool(pool_size)
  File "/usr/lib/python3.6/multiprocessing/pool.py", line 789, in __init__
    Pool.__init__(self, processes, initializer, initargs)
  File "/usr/lib/python3.6/multiprocessing/pool.py", line 174, in __init__
    self._repopulate_pool()
  File "/usr/lib/python3.6/multiprocessing/pool.py", line 239, in _repopulate_pool
    w.start()
  File "/usr/lib/python3.6/multiprocessing/dummy/__init__.py", line 48, in start
    threading.Thread.start(self)
  File "/usr/lib/python3.6/threading.py", line 846, in start
    _start_new_thread(self._bootstrap, ())
RuntimeError: can't start new thread

Could you please help me figure out why? Thanks.

**Comment by fanyangCS** [comment]
what version do you use? 0.14?

**Comment by Binyang2014** [comment]
@qingdo, Please provide you `job-config`, so we can try to reproduce this issue.

**Comment by scarlett2018** [comment]
@qingdo - may you please provide the info for the above questions so that we can provide more help here? thanks.

**Comment by qingdo** [comment]
Thanks for the help. We have upgraded to v1.0.0 and no longer facing this issue.
