### ISSUE TITLE
[openpai start failure] Openpai service start failed due to rest-server failure

### ISSUE THREAD

**Issue by JosephKang** [microsoft/pai#4542]
**Organization Name**: 
Advantech

**Short summary about the issue/question**:
Openpai service start failed due to rest-server failure

**Brief what process you are following**:
- Initial deployment
1.  ./paictl.py service start
2. Console output
2020-05-18 02:40:34,326 [INFO] - deployment.paiLibrary.paiService.service_management_start : Begin to execute service rest-server's start script.
configmap/group-configuration configured
configmap/job-exit-spec-configuration configured
2020-05-18 02:40:35,007 [INFO] - legacy_user_migrate.py:217 : Starts to migrate legacy user data from etcd to kubernetes secrets
Traceback (most recent call last):
  File "legacy_user_migrate.py", line 237, in <module>
    main()
  File "legacy_user_migrate.py", line 221, in main
    if transferCli.check_transfer_flag() is False and in_cluster is False:
  File "legacy_user_migrate.py", line 154, in check_transfer_flag
    check_res = http_get(self.etcd_conn, self.flag_path)
  File "legacy_user_migrate.py", line 181, in http_get
    conn.request("GET", url, headers=headers)
  File "/usr/lib/python3.5/http/client.py", line 1122, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib/python3.5/http/client.py", line 1167, in _send_request
    self.endheaders(body)
  File "/usr/lib/python3.5/http/client.py", line 1118, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python3.5/http/client.py", line 944, in _send_output
    self.send(msg)
  File "/usr/lib/python3.5/http/client.py", line 887, in send
    self.connect()
  File "/usr/lib/python3.5/http/client.py", line 859, in connect
    (self.host,self.port), self.timeout, self.source_address)
  File "/usr/lib/python3.5/socket.py", line 711, in create_connection
    raise err
  File "/usr/lib/python3.5/socket.py", line 702, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused
2020-05-18 02:40:35,056 [ERROR] - deployment.paiLibrary.common.linux_shell : Failed to execute the start script of service rest-server
2020-05-18 02:40:35,057 [ERROR] - deployment.paiLibrary.paiService.service_management_start : Failed to start service rest-server

**How to reproduce it**:
Just execute: ./paictl.py service start

**OpenPAI Environment**: 
- OpenPAI version: 0.17.0
- Cloud provider or hardware configuration: OpenStack VM
- OS (e.g. from /etc/os-release): Ubuntu 16.04.6 LTS
- Kernel (e.g. `uname -a`): 4.4.0-150-generic
- Others: api server on proxy
kubectl proxy --port=8080 &
curl http://localhost:8080/api/
{
  "kind": "APIVersions",
  "versions": [
    "v1"
  ],
  "serverAddressByClientCIDRs": [
    {
      "clientCIDR": "0.0.0.0/0",
      "serverAddress": "192.168.211.24:6443"
    }
  ]
}

**Anything else we need to know**:
- layout.yaml configuration for deployment
..
kubernetes:
  api-servers-url: http://192.168.211.24:8080
  dashboard-url: https://192.168.211.24:6443
..

**Comment by scarlett2018** [comment]
@JosephKang - per wechat discussion with your PM, this 0.17.0 deploy is to try out new K8S based OpenPAI deployment, right? 0.17.0 is actually an internal intermediate release. would you please directly try out the recent v1.0.0 release?

**Comment by JosephKang** [comment]
@scarlett2018
Yap. I am testing the v1.0.0 release deployment right now. Going to close the ticket.
