### ISSUE TITLE
[Deploy]rest-server crash to deploy v1.0

### ISSUE THREAD

**Issue by edenbuaa** [microsoft/pai#4668]
**OpenPAI Environment**:
- OpenPAI version: v1.0.1
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release): ubuntu16.04
- Kernel (e.g. `uname -a`):
- Hardware (e.g. core number, memory size, storage size, GPU type etc.):
- Others:

**Anything else we need to know**:
I deploy  OpenPAI v1.0.1 follow the install [guideline](https://openpai.readthedocs.io/en/latest/manual/cluster-admin/installation-guide.html#installation-requirements).
The rest-server pod became `CrashLoopBackOff` status after running for  a very short time. 
![image](https://user-images.githubusercontent.com/16248697/86461196-314d1e80-bd5c-11ea-963c-1d8de047eab2.png)

the logs in the rest-server pod:
`# kubectl logs rest-server-ds-djt4j`

```
> pai-rest-server@1.0.1 start /usr/src/app
> node index.js

(node:17) UnhandledPromiseRejectionWarning: Error: Cannot find skuTypes in hivedscheduler config.
    at Object.<anonymous> (/usr/src/app/src/config/vc.js:56:11)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/usr/src/app/src/models/v2/virtual-cluster/k8s.js:22:25)
    at Module._compile (module.js:653:30)
(node:17) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:17) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```
The OpenPAI can be deployed successfully even the rest-server keeping `CrashLoopBackOff ` status. but can not login by the webportal.

How to solve this? 
thanks.

**Comment by edenbuaa** [comment]
It's seems not the latest codes. close.
