### ISSUE TITLE
File corruption when training with the Azure blob 

### ISSUE THREAD

**Issue by zheng-ningxin** [microsoft/pai#4768]
**Organization Name**: Microsoft

**Short summary about the issue/question**:
I use OpenPAI to train a classification model on imagenet. The imagenet dataset is stored in the azure blob. I submit several jobs with different hyperparameters(such as learning rate). Some of these tasks can run smoothly, and the others will meet the following exception:

```

Traceback (most recent call last):
  File "constrained_pruner.py", line 200, in <module>
    acc1 = test(net1, device, criterion1, val_loader)
  File "constrained_pruner.py", line 125, in test
    for data, target in val_loader:
  File "/usr/local/lib/python3.5/dist-packages/torch/utils/data/dataloader.py", line 345, in __next__
    data = self._next_data()
  File "/usr/local/lib/python3.5/dist-packages/torch/utils/data/dataloader.py", line 856, in _next_data
    return self._process_data(data)
  File "/usr/local/lib/python3.5/dist-packages/torch/utils/data/dataloader.py", line 881, in _process_data
    data.reraise()
  File "/usr/local/lib/python3.5/dist-packages/torch/_utils.py", line 394, in reraise
    raise self.exc_type(msg)
OSError: Caught OSError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/torch/utils/data/_utils/worker.py", line 178, in _worker_loop
    data = fetcher.fetch(index)
  File "/usr/local/lib/python3.5/dist-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/usr/local/lib/python3.5/dist-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/usr/local/lib/python3.5/dist-packages/torchvision/datasets/folder.py", line 138, in __getitem__
    sample = self.loader(path)
  File "/usr/local/lib/python3.5/dist-packages/torchvision/datasets/folder.py", line 174, in default_loader
    return pil_loader(path)
  File "/usr/local/lib/python3.5/dist-packages/torchvision/datasets/folder.py", line 155, in pil_loader
    with open(path, 'rb') as f:
OSError: [Errno 5] Input/output error: '/mnt/nniblob/yugzhan/imagenet/all/val/n03761084/ILSVRC2012_val_00008253.JPEG'
```
I download the files mentioned in the error message, and there is nothing wrong with these files.
I think this error may be because azure blob cannot guarantee the correct transmission of the file requested each time. I think the correctness of the file should be guaranteed by azure blob driver/openpai. For example, when reading a file in an azure blob, the driver of the blob or openpai should keep trying until the file is successfully read, instead of handing it in the application process.
**Brief what process you are following**:

**How to reproduce it**:

**OpenPAI Environment**:
- OpenPAI version:
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Hardware (e.g. core number, memory size, storage size, GPU type etc.):
- Others:

**Anything else we need to know**:

**Comment by Binyang2014** [comment]
Can you provide your job config?

**Comment by zheng-ningxin** [comment]
Hi, one of the failed instance is at:
https://ne.openpai.org/job-detail.html?username=nizhen&jobName=large_mem_nizhen_0727_mobilenet_v2_activation_08

**Comment by Binyang2014** [comment]
We met this issue before. A workaround is package the imageNet dataset into a tarball, download it into the container, then extract and run.

We will try to figure the reason, I suspect it's a blobfuse issue
