### ISSUE TITLE
Cannot generate proper exit diagnostics when too much storage is used

### ISSUE THREAD

**Issue by hzy46** [microsoft/pai#4769]
`status.taskRoleStatuses[0].taskStatuses[0].attemptStatus.diagnostics` is  

`Pod failed: PodPattern matched: {\"reason\":\"Evicted\",\"message\":\"The node was low on resource: ephemeral-storage. Container app was using 154520Ki, which exceeds its request of 0. \"}"`

The rest-server will fail at:

```
TypeError: Cannot read property 'Symbol(Symbol.iterator)' of undefined
   at extractRuntimeOutput (/usr/src/app/src/utils/frameworkConverter.js:58:47)
   at generateExitDiagnostics (/usr/src/app/src/utils/frameworkConverter.js:120:29)
   at convertToJobAttempt (/usr/src/app/src/utils/frameworkConverter.js:233:27)
   at Promise.all.pgResult.map (/usr/src/app/src/models/v2/job-attempt.js:102:16)
   at Array.map (anonymous)
   at Object.list (/usr/src/app/src/models/v2/job-attempt.js:101:16)
   at anonymous
```

**Comment by fanyangCS** [comment]
relate to this issue: https://github.com/microsoft/pai/issues/4694

**Comment by fanyangCS** [comment]
@hzy46 , could you handle this bug?

**Comment by hzy46** [comment]
> @hzy46 , could you handle this bug?

I think @debuggy can handle this in the future, because he will refactor these codes. Reference item: `server history and detail page code refactor` in #4642
