### ISSUE TITLE
rest-server failed to start: cannot  connect to framework launcher

### ISSUE THREAD

**Issue by victorming** [microsoft/pai#4795]
rest-server failed to start: 
  /usr/src/app/src/models/v2/job/index.js:35
        throw new Error('cannot connect to framework launcher');

**OpenPAI Environment**: Ubuntu 16.04
- OpenPAI version: 0.14.0
- Cloud provider or hardware configuration: 
- OS (e.g. from /etc/os-release): Ubuntu 16.04
- Kernel (e.g. `uname -a`):
- Hardware (e.g. core number, memory size, storage size, GPU type etc.):
- Others:

**Comment by victorming** [comment]
k8s logs:

```
[HPM] Proxy created: /  -&gt;  Url {
  protocol: 'http:',
  slashes: true,
  auth: null,
  host: '192.168.101.241:8080',
  port: '8080',
  hostname: '192.168.101.241',
  hash: null,
  search: null,
  query: null,
  pathname: '/',
  path: '/',
  href: 'http://192.168.101.241:8080/' }
2020-08-07T09:19:39.752Z [INFO] config: {"env":"production","logLevel":"debug","serverPort":8080,"jwtSecret":"pai-secret"} 
2020-08-07T09:19:39.758Z [INFO] RESTful API server starts on port 8080 
/usr/src/app/src/models/v2/job/index.js:35
        throw new Error('cannot connect to framework launcher');
        ^
Error: cannot connect to framework launcher
    at unirest.get.timeout.end (/usr/src/app/src/models/v2/job/index.js:35:15)
    at Request.handleRequestResponse [as _callback] (/usr/src/app/node_modules/unirest/index.js:355:15)
    at self.callback (/usr/src/app/node_modules/unirest/node_modules/request/request.js:187:22)
    at emitOne (events.js:116:13)
    at Request.emit (events.js:211:7)
    at Request.onRequestError (/usr/src/app/node_modules/unirest/node_modules/request/request.js:813:8)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at Socket.socketErrorListener (_http_client.js:401:9)
    at emitOne (events.js:116:13)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! pai-rest-server@0.14.0 start: `node index.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the pai-rest-server@0.14.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-08-07T09_19_39_799Z-debug.log
Logs from 8/7/20 9:19 AM to 8/7/20 9:19 AM UTC

```

**Comment by victorming** [comment]
yarn-frameworklauncher pod yaml:

> {
  "kind": "DaemonSet",
  "apiVersion": "extensions/v1beta1",
  "metadata": {
    "name": "yarn-frameworklauncher-ds",
    "namespace": "default",
    "selfLink": "/apis/extensions/v1beta1/namespaces/default/daemonsets/yarn-frameworklauncher-ds",
    "uid": "e0a6e708-d889-11ea-ac4f-44a842479863",
    "resourceVersion": "1717439",
    "generation": 1,
    "creationTimestamp": "2020-08-07T08:42:07Z",
    "labels": {
      "app": "yarn-frameworklauncher"
    },
    "annotations": {
      "kubectl.kubernetes.io/last-applied-configuration": "{\"apiVersion\":\"apps/v1\",\"kind\":\"DaemonSet\",\"metadata\":{\"annotations\":{},\"name\":\"yarn-frameworklauncher-ds\",\"namespace\":\"default\"},\"spec\":{\"selector\":{\"matchLabels\":{\"app\":\"yarn-frameworklauncher\"}},\"template\":{\"metadata\":{\"labels\":{\"app\":\"yarn-frameworklauncher\"}},\"spec\":{\"affinity\":{\"nodeAffinity\":{\"requiredDuringSchedulingIgnoredDuringExecution\":{\"nodeSelectorTerms\":[{\"matchExpressions\":[{\"key\":\"pai-master\",\"operator\":\"In\",\"values\":[\"true\"]}]}]}}},\"containers\":[{\"env\":[{\"name\":\"RESOURCEMANAGER_ADDRESS\",\"value\":\"192.168.101.241\"},{\"name\":\"ZOOKEEPER_QUORUM\",\"value\":\"192.168.101.241:2181\"},{\"name\":\"HDFS_ADDRESS\",\"value\":\"192.168.101.241\"},{\"name\":\"LOGSERVER_ADDRESS\",\"value\":\"192.168.101.241\"},{\"name\":\"TIMELINE_SERVER_ADDRESS\",\"value\":\"192.168.101.241\"},{\"name\":\"GENERATE_CONFIG\",\"value\":\"frameworklauncher-generate-config.sh\"},{\"name\":\"FRAMEWORKLAUNCHER_VIP\",\"value\":\"192.168.101.241\"},{\"name\":\"FRAMEWORKLAUNCHER_PORT\",\"value\":\"9086\"},{\"name\":\"LAUNCHER_OPTS\",\"value\":\"-server -Xmx3072m -Djute.maxbuffer=49107800\"}],\"image\":\"docker.io/openpai/yarn-frameworklauncher:v0.14.0\",\"imagePullPolicy\":\"Always\",\"name\":\"yarn-frameworklauncher\",\"resources\":{\"limits\":{\"memory\":\"4Gi\"},\"requests\":{\"memory\":\"1Gi\"}},\"volumeMounts\":[{\"mountPath\":\"/hadoop-nm-configuration\",\"name\":\"hadoop-nm-config-volume\"},{\"mountPath\":\"/hadoop-dn-configuration\",\"name\":\"hadoop-dn-config-volume\"},{\"mountPath\":\"/yarn-frameworklauncher-configuration\",\"name\":\"yarn-frameworklauncher-config-volume\"},{\"mountPath\":\"/usr/local/launcher/logs\",\"name\":\"launcher-log\"},{\"mountPath\":\"/gpu-configuration\",\"name\":\"gpu-confg-volume\"}]}],\"hostNetwork\":true,\"hostPID\":false,\"imagePullSecrets\":[{\"name\":\"zs123456\"}],\"volumes\":[{\"hostPath\":{\"path\":\"/datastorage/launcherlogs\"},\"name\":\"launcher-log\"},{\"configMap\":{\"name\":\"hadoop-node-manager-configuration\"},\"name\":\"hadoop-nm-config-volume\"},{\"configMap\":{\"name\":\"hadoop-data-node-configuration\"},\"name\":\"hadoop-dn-config-volume\"},{\"configMap\":{\"name\":\"yarn-frameworklauncher-configmap\"},\"name\":\"yarn-frameworklauncher-config-volume\"},{\"configMap\":{\"name\":\"gpu-configuration\"},\"name\":\"gpu-confg-volume\"}]}}}}\n"
    }
  },
  "spec": {
    "selector": {
      "matchLabels": {
        "app": "yarn-frameworklauncher"
      }
    },
    "template": {
      "metadata": {
        "creationTimestamp": null,
        "labels": {
          "app": "yarn-frameworklauncher"
        }
      },
      "spec": {
        "volumes": [
          {
            "name": "launcher-log",
            "hostPath": {
              "path": "/datastorage/launcherlogs",
              "type": ""
            }
          },
          {
            "name": "hadoop-nm-config-volume",
            "configMap": {
              "name": "hadoop-node-manager-configuration",
              "defaultMode": 420
            }
          },
          {
            "name": "hadoop-dn-config-volume",
            "configMap": {
              "name": "hadoop-data-node-configuration",
              "defaultMode": 420
            }
          },
          {
            "name": "yarn-frameworklauncher-config-volume",
            "configMap": {
              "name": "yarn-frameworklauncher-configmap",
              "defaultMode": 420
            }
          },
          {
            "name": "gpu-confg-volume",
            "configMap": {
              "name": "gpu-configuration",
              "defaultMode": 420
            }
          }
        ],
        "containers": [
          {
            "name": "yarn-frameworklauncher",
            "image": "docker.io/openpai/yarn-frameworklauncher:v0.14.0",
            "env": [
              {
                "name": "RESOURCEMANAGER_ADDRESS",
                "value": "192.168.101.241"
              },
              {
                "name": "ZOOKEEPER_QUORUM",
                "value": "192.168.101.241:2181"
              },
              {
                "name": "HDFS_ADDRESS",
                "value": "192.168.101.241"
              },
              {
                "name": "LOGSERVER_ADDRESS",
                "value": "192.168.101.241"
              },
              {
                "name": "TIMELINE_SERVER_ADDRESS",
                "value": "192.168.101.241"
              },
              {
                "name": "GENERATE_CONFIG",
                "value": "frameworklauncher-generate-config.sh"
              },
              {
                "name": "FRAMEWORKLAUNCHER_VIP",
                "value": "192.168.101.241"
              },
              {
                "name": "FRAMEWORKLAUNCHER_PORT",
                "value": "9086"
              },
              {
                "name": "LAUNCHER_OPTS",
                "value": "-server -Xmx3072m -Djute.maxbuffer=49107800"
              }
            ],
            "resources": {
              "limits": {
                "memory": "4Gi"
              },
              "requests": {
                "memory": "1Gi"
              }
            },
            "volumeMounts": [
              {
                "name": "hadoop-nm-config-volume",
                "mountPath": "/hadoop-nm-configuration"
              },
              {
                "name": "hadoop-dn-config-volume",
                "mountPath": "/hadoop-dn-configuration"
              },
              {
                "name": "yarn-frameworklauncher-config-volume",
                "mountPath": "/yarn-frameworklauncher-configuration"
              },
              {
                "name": "launcher-log",
                "mountPath": "/usr/local/launcher/logs"
              },
              {
                "name": "gpu-confg-volume",
                "mountPath": "/gpu-configuration"
              }
            ],
            "terminationMessagePath": "/dev/termination-log",
            "terminationMessagePolicy": "File",
            "imagePullPolicy": "Always"
          }
        ],
        "restartPolicy": "Always",
        "terminationGracePeriodSeconds": 30,
        "dnsPolicy": "ClusterFirst",
        "hostNetwork": true,
        "securityContext": {},
        "imagePullSecrets": [
          {
            "name": "zs123456"
          }
        ],
        "affinity": {
          "nodeAffinity": {
            "requiredDuringSchedulingIgnoredDuringExecution": {
              "nodeSelectorTerms": [
                {
                  "matchExpressions": [
                    {
                      "key": "pai-master",
                      "operator": "In",
                      "values": [
                        "true"
                      ]
                    }
                  ]
                }
              ]
            }
          }
        },
        "schedulerName": "default-scheduler"
      }
    },
    "updateStrategy": {
      "type": "RollingUpdate",
      "rollingUpdate": {
        "maxUnavailable": 1
      }
    },
    "templateGeneration": 1,
    "revisionHistoryLimit": 10
  },
  "status": {
    "currentNumberScheduled": 1,
    "numberMisscheduled": 0,
    "desiredNumberScheduled": 1,
    "numberReady": 1,
    "observedGeneration": 1,
    "updatedNumberScheduled": 1,
    "numberAvailable": 1
  }
}

**Comment by victorming** [comment]
rest-server yaml:

> {
  "kind": "Pod",
  "apiVersion": "v1",
  "metadata": {
    "name": "rest-server-ds-pkw4r",
    "generateName": "rest-server-ds-",
    "namespace": "default",
    "selfLink": "/api/v1/namespaces/default/pods/rest-server-ds-pkw4r",
    "uid": "a0f83974-d88e-11ea-ac4f-44a842479863",
    "resourceVersion": "1717678",
    "creationTimestamp": "2020-08-07T09:16:08Z",
    "labels": {
      "app": "rest-server",
      "controller-revision-hash": "1921317823",
      "pod-template-generation": "1"
    },
    "ownerReferences": [
      {
        "apiVersion": "extensions/v1beta1",
        "kind": "DaemonSet",
        "name": "rest-server-ds",
        "uid": "a0ca6a15-d88e-11ea-ac4f-44a842479863",
        "controller": true,
        "blockOwnerDeletion": true
      }
    ]
  },
  "spec": {
    "volumes": [
      {
        "name": "pai-configuration-rest-server",
        "configMap": {
          "name": "pai-configuration",
          "defaultMode": 420
        }
      },
      {
        "name": "job-exit-spec-rest-server",
        "configMap": {
          "name": "job-exit-spec-configuration",
          "defaultMode": 420
        }
      },
      {
        "name": "group-configuration-rest-server",
        "configMap": {
          "name": "group-configuration",
          "defaultMode": 420
        }
      }
    ],
    "containers": [
      {
        "name": "rest-server",
        "image": "docker.io/openpai/rest-server:v0.14.0",
        "ports": [
          {
            "name": "rest-server",
            "hostPort": 9186,
            "containerPort": 8080,
            "protocol": "TCP"
          }
        ],
        "env": [
          {
            "name": "LAUNCHER_TYPE",
            "value": "yarn"
          },
          {
            "name": "LAUNCHER_WEBSERVICE_URI",
            "value": "http://192.168.101.241:9086"
          },
          {
            "name": "HDFS_URI",
            "value": "hdfs://192.168.101.241:9000"
          },
          {
            "name": "WEBHDFS_URI",
            "value": "http://192.168.101.241:5070"
          },
          {
            "name": "YARN_URI",
            "value": "http://192.168.101.241:8088"
          },
          {
            "name": "JWT_SECRET",
            "value": "pai-secret"
          },
          {
            "name": "WEBPORTAL_URL",
            "value": "192.168.101.241"
          },
          {
            "name": "AUTHN_METHOD",
            "value": "basic"
          },
          {
            "name": "DEFAULT_PAI_ADMIN_USERNAME",
            "value": "admin"
          },
          {
            "name": "DEFAULT_PAI_ADMIN_PASSWORD",
            "value": "adminok"
          },
          {
            "name": "K8S_APISERVER_URI",
            "value": "http://192.168.101.241:8080"
          },
          {
            "name": "AZ_RDMA",
            "value": "false"
          },
          {
            "name": "DEBUGGING_RESERVATION_SECONDS",
            "value": "604800"
          },
          {
            "name": "GITHUB_OWNER",
            "value": "Microsoft"
          },
          {
            "name": "GITHUB_REPOSITORY",
            "value": "pai"
          },
          {
            "name": "GITHUB_PATH",
            "value": "marketplace"
          }
        ],
        "resources": {
          "limits": {
            "memory": "512Mi"
          },
          "requests": {
            "memory": "512Mi"
          }
        },
        "volumeMounts": [
          {
            "name": "pai-configuration-rest-server",
            "mountPath": "/pai-cluster-config"
          },
          {
            "name": "group-configuration-rest-server",
            "mountPath": "/group-configuration"
          },
          {
            "name": "job-exit-spec-rest-server",
            "mountPath": "/job-exit-spec-configuration"
          }
        ],
        "terminationMessagePath": "/dev/termination-log",
        "terminationMessagePolicy": "File",
        "imagePullPolicy": "Always"
      }
    ],
    "restartPolicy": "Always",
    "terminationGracePeriodSeconds": 30,
    "dnsPolicy": "ClusterFirst",
    "nodeName": "192.168.101.241",
    "securityContext": {},
    "imagePullSecrets": [
      {
        "name": "zs123456"
      }
    ],
    "affinity": {
      "nodeAffinity": {
        "requiredDuringSchedulingIgnoredDuringExecution": {
          "nodeSelectorTerms": [
            {
              "matchExpressions": [
                {
                  "key": "pai-master",
                  "operator": "In",
                  "values": [
                    "true"
                  ]
                }
              ]
            }
          ]
        }
      }
    },
    "schedulerName": "default-scheduler",
    "tolerations": [
      {
        "key": "node.kubernetes.io/not-ready",
        "operator": "Exists",
        "effect": "NoExecute"
      },
      {
        "key": "node.kubernetes.io/unreachable",
        "operator": "Exists",
        "effect": "NoExecute"
      },
      {
        "key": "node.kubernetes.io/disk-pressure",
        "operator": "Exists",
        "effect": "NoSchedule"
      },
      {
        "key": "node.kubernetes.io/memory-pressure",
        "operator": "Exists",
        "effect": "NoSchedule"
      }
    ]
  },
  "status": {
    "phase": "Running",
    "conditions": [
      {
        "type": "Initialized",
        "status": "True",
        "lastProbeTime": null,
        "lastTransitionTime": "2020-08-07T09:16:08Z"
      },
      {
        "type": "Ready",
        "status": "False",
        "lastProbeTime": null,
        "lastTransitionTime": "2020-08-07T09:22:39Z",
        "reason": "ContainersNotReady",
        "message": "containers with unready status: [rest-server]"
      },
      {
        "type": "PodScheduled",
        "status": "True",
        "lastProbeTime": null,
        "lastTransitionTime": "2020-08-07T09:16:11Z"
      }
    ],
    "hostIP": "192.168.101.241",
    "podIP": "172.17.0.3",
    "startTime": "2020-08-07T09:16:08Z",
    "containerStatuses": [
      {
        "name": "rest-server",
        "state": {
          "waiting": {
            "reason": "CrashLoopBackOff",
            "message": "Back-off 5m0s restarting failed container=rest-server pod=rest-server-ds-pkw4r_default(a0f83974-d88e-11ea-ac4f-44a842479863)"
          }
        },
        "lastState": {
          "terminated": {
            "exitCode": 1,
            "reason": "Error",
            "startedAt": "2020-08-07T09:22:36Z",
            "finishedAt": "2020-08-07T09:22:37Z",
            "containerID": "docker://6e70db120c70c4fd94c3f232d0d9a05bd6994b1ae42bfe70d8ccf9c30ba944f4"
          }
        },
        "ready": false,
        "restartCount": 6,
        "image": "openpai/rest-server:v0.14.0",
        "imageID": "docker-pullable://openpai/rest-server@sha256:d566814d01fcb6aecc3534414041d889cc53d89c4ba41860682b63c147a0c182",
        "containerID": "docker://6e70db120c70c4fd94c3f232d0d9a05bd6994b1ae42bfe70d8ccf9c30ba944f4"
      }
    ],
    "qosClass": "Burstable"
  }
}

**Comment by victorming** [comment]
I checked the service of yarn-frameworklauncher using the command: curl 192.168.101.241:9086 and found no response echoed. And I also found the yarn-frameworklauncher service failed periodically with following logs:
  /usr/local/launcher /

> 2020-08-07 09:35:33,824 ERROR [main] com.microsoft.frameworklauncher.service.Service: Exception occurred in com.microsoft.frameworklauncher.service.Service. It should be transient. Will restart com.microsoft.frameworklauncher.service.Service inplace.
> org.apache.zookeeper.KeeperException$ConnectionLossException: KeeperErrorCode = ConnectionLoss for /Launcher
> 	at org.apache.zookeeper.KeeperException.create(KeeperException.java:102)
> 	at org.apache.zookeeper.KeeperException.create(KeeperException.java:54)
> 	at org.apache.zookeeper.ZooKeeper.exists(ZooKeeper.java:1111)
> 	at org.apache.curator.framework.imps.ExistsBuilderImpl$3.call(ExistsBuilderImpl.java:237)
> 	at org.apache.curator.framework.imps.ExistsBuilderImpl$3.call(ExistsBuilderImpl.java:226)
> 	at org.apache.curator.RetryLoop.callWithRetry(RetryLoop.java:109)
> 	at org.apache.curator.framework.imps.ExistsBuilderImpl.pathInForegroundStandard(ExistsBuilderImpl.java:223)
> 	at org.apache.curator.framework.imps.ExistsBuilderImpl.pathInForeground(ExistsBuilderImpl.java:216)
> 	at org.apache.curator.framework.imps.ExistsBuilderImpl.forPath(ExistsBuilderImpl.java:175)
> 	at org.apache.curator.framework.imps.ExistsBuilderImpl.forPath(ExistsBuilderImpl.java:32)
> 	at com.microsoft.frameworklauncher.zookeeperstore.ZooKeeperClient.exists(ZooKeeperClient.java:71)
> 	at com.microsoft.frameworklauncher.zookeeperstore.ZookeeperStore.setupZKStructure(ZookeeperStore.java:54)
> 	at com.microsoft.frameworklauncher.zookeeperstore.ZookeeperStore.&lt;init&gt;(ZookeeperStore.java:43)
> 	at com.microsoft.frameworklauncher.service.Service.initialize(Service.java:145)
> 	at com.microsoft.frameworklauncher.common.service.AbstractService.start(AbstractService.java:43)
> 	at com.microsoft.frameworklauncher.service.Bootstrap.main(Bootstrap.java:23)
> 2020-08-07 09:35:33,832 INFO [main] com.microsoft.frameworklauncher.service.Service: com.microsoft.frameworklauncher.service.Service stopped

**Comment by victorming** [comment]
It seems the zookeeper service malfunctioned. I removed the directory of /datastorage/zoodata and redeploy the zookeeper service. But the issue remains. Anybody can help?

**Comment by victorming** [comment]
I removed the directory /datastorage/zoodata on every node and restart the zookeeper service. Now the yarn-frameworklauncher service is OK and redeployed rest-server successfully.
