### ISSUE TITLE
fialed to start OpenPAI service

### ISSUE THREAD

**Issue by sumeng1024** [microsoft/pai#4972]
**Organization Name**:

**Short summary about the issue/question**:
when I run `python paictl.py service start-c ~/.kube/config `  in the dev-box container to start the OpenPAI service, I get the following error.
```shell
error: unable to recognize "priority-class.yaml": no matches for kind "PriorityClass" in version "scheduling.k8s.io/v1"
```
**Brief what process you are following**:

- Operating type: Initial deployment
- deployment process
```shell
# pull dev-box docker image
docker pull docker.io/openpai/dev-box:v1.2.0

# run dev-box
sudo docker run -itd \
        -e COLUMNS=$COLUMNS -e LINES=$LINES -e TERM=$TERM \
        -v /var/run/docker.sock:/var/run/docker.sock \
        -v /pathHadoop:/pathHadoop \
        -v /pathConfiguration:/cluster-configuration  \
        --pid=host \
        --privileged=true \
        --net=host \
        --name=dev-box \
        docker.io/openpai/dev-box:v1.2.0
        
# login dev-box
sudo docker exec -it dev-box /bin/bash

# the following commands are running in the container
cd /pai
git fetch --tags
git checkout v1.2.0

# edit quick-start.yaml
cd /pai/deployment/quick-start/  
cp quick-start-example.yaml quick-start.yaml  
vim quick-start.yaml

# generate config file
cd /pai  
python paictl.py config generate -i /pai/deployment/quick-start/quick-start.yaml -o ~/pai-config -f  

# edit layout.yaml

# deploy Kubernetes
cd pai
python paictl.py cluster k8s-bootup \
  -p ~/pai-config
  
# push config to Kubernetes
cd pai  
python paictl.py config push -p ~/pai-config/ -c ~/.kube/config

# start OpenPai service
python paictl.py service start -c ~/.kube/config
```

How to reproduce it**:

**OpenPAI Environment**:

- OpenPAI version: v1.2.0
- Cloud provider or hardware configuration: 
- OS (e.g. from /etc/os-release): ubuntu 16.04
- Kernel (e.g. `uname -a`): 4.15.0-118-generic
- Hardware (e.g. core number, memory size, storage size, GPU type etc.):
- Others:

  | Hostname | IP           | Vcore | Mem  | GPU        | Role           |
  | -------- | ------------ | ----- | ---- | ---------- | -------------- |
  | node01   | 172.16.10.11 | 32    | 128G | RTX 2080Ti | master,dev-box |
  | node02   | 172.16.10.12 | 32    | 128G | RTX 2080Ti | worker         |
  | node03   | 172.16.10.13 | 32    | 128G | RTX 2080Ti | worker         |
  | node04   | 172.16.10.14 | 32    | 128G | RTX 2080Ti | worker         |

**Anything else we need to know**:

Error log:

```shell
2020-06-29 08:04:25,065 [INFO] - deployment.paiLibrary.paiService.service_management_start : Begin to generate service rest-server's template file
2020-06-29 08:04:25,065 [INFO] - deployment.paiLibrary.paiService.service_template_generate : Begin to generate the template file in service rest-server's configuration.
2020-06-29 08:04:25,066 [INFO] - deployment.paiLibrary.paiService.service_template_generate : Create template mapper for service rest-server.
2020-06-29 08:04:25,066 [INFO] - deployment.paiLibrary.paiService.service_template_generate : Done. Template mapper for service rest-server is created.
2020-06-29 08:04:25,066 [INFO] - deployment.paiLibrary.paiService.service_template_generate : Generate the template file /pai/deployment/paiLibrary/paiService/../../../src/rest-server/deploy/rest-server.yaml.template.
2020-06-29 08:04:25,066 [INFO] - deployment.paiLibrary.paiService.service_template_generate : Save the generated file to /pai/deployment/paiLibrary/paiService/../../../src/rest-server/deploy/rest-server.yaml.
2020-06-29 08:04:25,173 [INFO] - deployment.paiLibrary.paiService.service_template_generate : Generate the template file /pai/deployment/paiLibrary/paiService/../../../src/rest-server/deploy/start.sh.template.
2020-06-29 08:04:25,173 [INFO] - deployment.paiLibrary.paiService.service_template_generate : Save the generated file to /pai/deployment/paiLibrary/paiService/../../../src/rest-server/deploy/start.sh.
2020-06-29 08:04:25,183 [INFO] - deployment.paiLibrary.paiService.service_template_generate : Generate the template file /pai/deployment/paiLibrary/paiService/../../../src/rest-server/deploy/configmap-create.sh.template.
2020-06-29 08:04:25,183 [INFO] - deployment.paiLibrary.paiService.service_template_generate : Save the generated file to /pai/deployment/paiLibrary/paiService/../../../src/rest-server/deploy/configmap-create.sh.
2020-06-29 08:04:25,189 [INFO] - deployment.paiLibrary.paiService.service_template_generate : Generate the template file /pai/deployment/paiLibrary/paiService/../../../src/rest-server/deploy/auth-configmap/oidc.yaml.template.
2020-06-29 08:04:25,189 [INFO] - deployment.paiLibrary.paiService.service_template_generate : Save the generated file to /pai/deployment/paiLibrary/paiService/../../../src/rest-server/deploy/auth-configmap/oidc.yaml.
2020-06-29 08:04:25,205 [INFO] - root : It is not a service deploy file! Only support ['DaemonSet', 'Deployment', 'StatefulSet', 'Pod']
2020-06-29 08:04:25,206 [INFO] - deployment.paiLibrary.paiService.service_template_generate : Generate the template file /pai/deployment/paiLibrary/paiService/../../../src/rest-server/deploy/group-configmap/group.yaml.template.
2020-06-29 08:04:25,206 [INFO] - deployment.paiLibrary.paiService.service_template_generate : Save the generated file to /pai/deployment/paiLibrary/paiService/../../../src/rest-server/deploy/group-configmap/group.yaml.
2020-06-29 08:04:25,232 [INFO] - root : It is not a service deploy file! Only support ['DaemonSet', 'Deployment', 'StatefulSet', 'Pod']
2020-06-29 08:04:25,232 [INFO] - deployment.paiLibrary.paiService.service_template_generate : Generate the template file /pai/deployment/paiLibrary/paiService/../../../src/rest-server/deploy/job-exit-spec-config/job-exit-spec.yaml.template.
2020-06-29 08:04:25,232 [INFO] - deployment.paiLibrary.paiService.service_template_generate : Save the generated file to /pai/deployment/paiLibrary/paiService/../../../src/rest-server/deploy/job-exit-spec-config/job-exit-spec.yaml.
2020-06-29 08:04:25,257 [INFO] - root : It is not a service deploy file! Only support ['DaemonSet', 'Deployment', 'StatefulSet', 'Pod']
2020-06-29 08:04:25,258 [INFO] - deployment.paiLibrary.paiService.service_template_generate : Generate the template file /pai/deployment/paiLibrary/paiService/../../../src/rest-server/deploy/k8s-job-exit-spec-config/k8s-job-exit-spec.yaml.template.
2020-06-29 08:04:25,258 [INFO] - deployment.paiLibrary.paiService.service_template_generate : Save the generated file to /pai/deployment/paiLibrary/paiService/../../../src/rest-server/deploy/k8s-job-exit-spec-config/k8s-job-exit-spec.yaml.
2020-06-29 08:04:25,565 [INFO] - root : It is not a service deploy file! Only support ['DaemonSet', 'Deployment', 'StatefulSet', 'Pod']
2020-06-29 08:04:25,566 [INFO] - deployment.paiLibrary.paiService.service_template_generate : The template file of service rest-server is generated.
2020-06-29 08:04:25,566 [INFO] - deployment.paiLibrary.paiService.service_management_start : Begin to start service: [ rest-server ]
2020-06-29 08:04:25,567 [INFO] - deployment.paiLibrary.paiService.service_management_start : Begin to execute service rest-server's start script.
W0629 08:04:25.671594   37367 helpers.go:535] --dry-run is deprecated and can be replaced with --dry-run=client.
configmap/group-configuration configured
W0629 08:04:25.867507   37415 helpers.go:535] --dry-run is deprecated and can be replaced with --dry-run=client.
configmap/k8s-job-exit-spec-configuration configured
2020-06-29 08:04:26,990 [INFO] - legacy_user_migrate.py:217 : Starts to migrate legacy user data from etcd to kubernetes secrets
2020-06-29 08:04:26,993 [INFO] - legacy_user_migrate.py:233 : Etcd data has already been transferred to k8s secret
2020-06-29 08:04:27,842 [INFO] - user_v2_migrate.py:287 : Legacy data has already been transferred from v1 to v2. Skip it.
error: unable to recognize "priority-class.yaml": no matches for kind "PriorityClass" in version "scheduling.k8s.io/v1"
2020-06-29 08:04:28,245 [ERROR] - deployment.paiLibrary.common.linux_shell : Failed to execute the start script of service rest-server
2020-06-29 08:04:28,246 [ERROR] - deployment.paiLibrary.paiService.service_management_start : Failed to start service rest-server
2020-06-29 08:04:28,247 [INFO] - deployment.paiLibrary.paiService.service_management_start : -----------------------------------------------------------
2020-06-29 08:04:28,247 [ERROR] - deployment.paiLibrary.paiService.service_management_start : Have retried 5 times, but service rest-server doesn't start. Please check it.
```

**Comment by hzy46** [comment]
There's an error : `error: unable to recognize "priority-class.yaml": no matches for kind "PriorityClass" in version "scheduling.k8s.io/v1"`.

Looks like your k8s doesn't support priority class. Could you provide the version of Kubernetes in your cluster?

**Comment by sumeng1024** [comment]
v1.9.9

**Comment by hzy46** [comment]
We recommend you to use kubespray 2.1.1 to deploy Kubernetes 1.14. v1.9.9 is too old.

**Comment by fanyangCS** [comment]
@hzy46, could we add a precheck for the required version?

**Comment by sumeng1024** [comment]
> We recommend you to use kubespray 2.1.1 to deploy Kubernetes 1.14. v1.9.9 is too old.

OK, I`ll try to install it manually. Should I install the Nvidia driver and nvidia-container-runtime on every node before deploying OpenPAI.

**Comment by hzy46** [comment]
Yes. You can check our document for requirements: https://openpai.readthedocs.io/en/latest/manual/cluster-admin/installation-guide.html

We provide a script `quick-start-kubespray.sh` for installing Kubernetes. But you can install manually if you prefer so.

**Comment by sumeng1024** [comment]
When I run `/bin/bash requirement.sh -m ~/master.csv -w ~/worker.csv -c ~/config` checking requirements, I get the following error:
```shell
TASK [requirement/worker : Remove unnecessary char in the end of the output] *************************************************************************************************************************************
ok: [gpu-cluster-node004] => (item=)
ok: [gpu-cluster-node004] => (item="nvidia")
ok: [gpu-cluster-node003] => (item=)
ok: [gpu-cluster-node003] => (item="nvidia")

TASK [requirement/worker : Get Default Runtime] ******************************************************************************************************************************************************************
skipping: [gpu-cluster-node004] => (item=) 
skipping: [gpu-cluster-node003] => (item=) 
ok: [gpu-cluster-node004] => (item=nvidia)
ok: [gpu-cluster-node003] => (item=nvidia)

TASK [requirement/worker : Check the default runtime is set correctly] *******************************************************************************************************************************************
ok: [gpu-cluster-node004]
ok: [gpu-cluster-node003]

TASK [requirement/worker : Worker machines' os is not ubuntu.] ***************************************************************************************************************************************************
skipping: [gpu-cluster-node004]
skipping: [gpu-cluster-node003]

PLAY [all,localhost] *********************************************************************************************************************************************************************************************

TASK [Gathering Facts] *******************************************************************************************************************************************************************************************
ok: [localhost]
ok: [gpu-cluster-node002]
ok: [gpu-cluster-node004]
ok: [gpu-cluster-node003]

TASK [display unmet requirements] ********************************************************************************************************************************************************************************
skipping: [gpu-cluster-node002]
skipping: [localhost]
fatal: [gpu-cluster-node004]: FAILED! => {"changed": false, "msg": "The following requirements are not met: The default runtime is not set correctly"}
fatal: [gpu-cluster-node003]: FAILED! => {"changed": false, "msg": "The following requirements are not met: The default runtime is not set correctly"}
	to retry, use: --limit @/home/openpai/pai/contrib/kubespray/environment-check.retry

PLAY RECAP *******************************************************************************************************************************************************************************************************
gpu-cluster-node002        : ok=16   changed=0    unreachable=0    failed=0   
gpu-cluster-node003        : ok=23   changed=0    unreachable=0    failed=1   
gpu-cluster-node004        : ok=23   changed=0    unreachable=0    failed=1   
localhost                  : ok=9    changed=0    unreachable=0    failed=0   

Failed: There are unmet requirements in your cluster, the installation will be very likely to fail.
```
This is my daemon file, it`s the same as the guide shows. I do not know where the problem is.
```shell
root@gpu-cluster-node003:~$ cat /etc/docker/daemon.json 
{
  "default-runtime": "nvidia",
  "runtimes": {
      "nvidia": {
          "path": "/usr/bin/nvidia-container-runtime",
          "runtimeArgs": []
      }
  }
}

```

**Comment by hzy46** [comment]
Maybe related to https://github.com/microsoft/pai/issues/4957 You can ignore the check.

I will take a look at this issue recently.

**Comment by hzy46** [comment]
> @hzy46, could we add a precheck for the required version?

Yes, we can add a kubernetes version check in service-boot.sh (e.g. after this line: https://github.com/microsoft/pai/blob/98fd56a70e27a913852075158e68fb5459bde5db/contrib/kubespray/script/service-boot.sh#L41).

**Comment by sumeng1024** [comment]
> Maybe related to #4957 . You can ignore the check.
> 
> I will take a look at this issue recently.

Sorry, I ignore the check but meet a new problem.
```shell
openpai@gpu-cluster-node001:~/pai/contrib/kubespray$ /bin/bash quick-start-service.sh -m ~/master.csv -w ~/worker.csv -c ~/config 
worker list file path: /home/openpai/worker.csv
master list file path: /home/openpai/master.csv
cluster config file path: /home/openpai/config
Branch Name v1.2.0
OpenPAI Image Tag v1.2.0
5c0b1455d656d39e585a5a0251611f679aa03d71a6b8fd9b6cc5f8e4fb1a728c
The connection to the server localhost:8080 was refused - did you specify the right host or port?
```

**Comment by hzy46** [comment]
Did you run `quick-start-kubespray.sh`? Looks like the k8s is not started.

**Comment by sumeng1024** [comment]
> > Maybe related to #4957 . You can ignore the check.
> > I will take a look at this issue recently.
> 
> Sorry, I ignore the check but meet a new problem.
> 
> ```shell
> openpai@gpu-cluster-node001:~/pai/contrib/kubespray$ /bin/bash quick-start-service.sh -m ~/master.csv -w ~/worker.csv -c ~/config 
> worker list file path: /home/openpai/worker.csv
> master list file path: /home/openpai/master.csv
> cluster config file path: /home/openpai/config
> Branch Name v1.2.0
> OpenPAI Image Tag v1.2.0
> 5c0b1455d656d39e585a5a0251611f679aa03d71a6b8fd9b6cc5f8e4fb1a728c
> The connection to the server localhost:8080 was refused - did you specify the right host or port?
> ```

I find that the port 8080 is only listening on 172.16.10.10. how to change it to 0.0.0.0
```shell
openpai@gpu-cluster-node001:~/pai/contrib/kubespray$ netstat -tnulp | grep 8080
(Not all processes could be identified, non-owned process info
 will not be shown, you would have to be root to see it all.)
tcp        0      0 172.16.10.10:8080        0.0.0.0:*               LISTEN      - 
```

**Comment by sumeng1024** [comment]
> Did you run `quick-start-kubespray.sh`? Looks like the k8s is not started.

Yes, I have ran it.

**Comment by sumeng1024** [comment]
> > Did you run `quick-start-kubespray.sh`? Looks like the k8s is not started.
> 
> Yes, I have ran it.

```shell
TASK [download : set_container_facts | Define path of image] *****************************************************************************************************************************************************
Thursday 15 October 2020  15:27:50 +0800 (0:00:00.151)       0:03:19.342 ****** 
ok: [gpu-cluster-node004]
ok: [gpu-cluster-node002]
ok: [gpu-cluster-node003]

TASK [download : download_container | Determine if image is in cache] ********************************************************************************************************************************************
Thursday 15 October 2020  15:27:51 +0800 (0:00:00.174)       0:03:19.516 ****** 

TASK [download : download_container | Set fact indicating if image is in cache] **********************************************************************************************************************************
Thursday 15 October 2020  15:27:51 +0800 (0:00:00.127)       0:03:19.644 ****** 

TASK [download : download_container | Upload image to node if it is cached] **************************************************************************************************************************************
Thursday 15 October 2020  15:27:51 +0800 (0:00:00.081)       0:03:19.725 ****** 

TASK [download : download_container | Load image into docker] ****************************************************************************************************************************************************
Thursday 15 October 2020  15:27:51 +0800 (0:00:00.102)       0:03:19.828 ****** 

TASK [download : download_container | Prepare container download] ************************************************************************************************************************************************
Thursday 15 October 2020  15:27:51 +0800 (0:00:00.126)       0:03:19.954 ****** 
included: /home/openpai/pai-deploy/kubespray/roles/download/tasks/check_pull_required.yml for gpu-cluster-node004, gpu-cluster-node002, gpu-cluster-node003

TASK [download : check_pull_required |  Generate a list of information about the images on a node] ***************************************************************************************************************
Thursday 15 October 2020  15:27:51 +0800 (0:00:00.201)       0:03:20.156 ****** 
ok: [gpu-cluster-node002 -> 172.16.10.11]
ok: [gpu-cluster-node004 -> 172.16.10.11]
fatal: [gpu-cluster-node003]: UNREACHABLE! => {"censored": "the output has been hidden due to the fact that 'no_log: true' was specified for this result", "changed": false}

NO MORE HOSTS LEFT ***********************************************************************************************************************************************************************************************
	to retry, use: --limit @/home/openpai/pai-deploy/kubespray/cluster.retry

PLAY RECAP *******************************************************************************************************************************************************************************************************
gpu-cluster-node002        : ok=152  changed=16   unreachable=0    failed=0   
gpu-cluster-node003        : ok=131  changed=14   unreachable=1    failed=0   
gpu-cluster-node004        : ok=149  changed=14   unreachable=0    failed=0   
localhost                  : ok=1    changed=0    unreachable=0    failed=0   
```

**Comment by sumeng1024** [comment]
I am so happy that I finally successfully deployed OpenPAI after reinstalling the system. I waited for almost an hour after running `/bin/bash quick-start-service.sh -m ~/master.csv -w ~/worker.csv -c ~/config`
```shell
OpenPAI is successfully deployed, please check the following information:
Kubernetes cluster config :     ~/pai-deploy/kube/config
OpenPAI cluster config    :     ~/pai-deploy/cluster-cfg
OpenPAI cluster ID        :     pai
Default username          :     admin
Default password          :     admin-password

You can go to http://172.16.10.11, then use the default username and password to log in.
```

**Comment by hzy46** [comment]
Congratulations!

**Comment by hzy46** [comment]
What causes the long running time in your opinion? I guess maybe it is due to the downloading time of our docker images.

**Comment by sumeng1024** [comment]
Yes, It costs too much time downloading the docker images.

**Comment by sumeng1024** [comment]
@hzy46 I just see 1 GPU but in fact, we have 2 GPUs in every node. how to change the GPU count? And I use different CPUs in the cluster, how to set it up?

**Comment by hzy46** [comment]
I'm not sure why pai generates wrong config for you. But you can refer to https://openpai.readthedocs.io/en/latest/manual/cluster-admin/how-to-set-up-virtual-clusters.html and https://github.com/microsoft/hivedscheduler/blob/master/doc/user-manual.md to set up proper resource for your virtual cluster.

**Comment by sumeng1024** [comment]
After modification of the configuration, I use `./paictl.py service stop -n rest-server hivedscheduler` to apply the settings but failed.
```shell
openpai@dev-box:~/pai$ ./paictl.py service stop -n rest-server hivedscheduler
Traceback (most recent call last):
  File "./paictl.py", line 29, in <module>
    from deployment.paiLibrary.common import file_handler
  File "/home/autox-it/pai/deployment/paiLibrary/common/file_handler.py", line 19, in <module>
    import yaml
ImportError: No module named yaml
```
And after installing yaml, I got the new error `ImportError: No module named jinja2`

**Comment by hzy46** [comment]
Did you use the paictl in a dev box container?

**Comment by hzy46** [comment]
See our doc: https://openpai.readthedocs.io/en/latest/manual/cluster-admin/basic-management-operations.html#pai-service-management-and-paictl

**Comment by sumeng1024** [comment]
> Did you use the paictl in a dev box container?

No, I run the command in the dev-box machine, no container is running on the host.

**Comment by hzy46** [comment]
I recommend you to leverage our dev box docker image to avoid environment-related problems.

**Comment by sumeng1024** [comment]
How to set up https access for OpenPAI? I want to access Kubernetes dashboard.

**Comment by hzy46** [comment]
You can refer to https://openpai.readthedocs.io/en/latest/manual/cluster-admin/how-to-manage-users-and-groups.html#pylon-prepare-your-certificate-for-https-self-sign-cert-as-an-example .

I'm refactoring the document of this part to let it become more clear.
