### ISSUE TITLE
Cordon node not working

### ISSUE THREAD

**Issue by Binyang2014** [microsoft/pai#5014]
Alert manager cordon node feature not working.
Error log is:
```
2020-10-26T09:29:36.959Z [ERROR]
meta = {
  "message": "Required parameter name was null or undefined when calling patchNode.",
  "stack": "Error: Required parameter name was null or undefined when calling patchNode.\n    at CoreV1Api.<anonymous> (/usr/src/app/node_modules/@kubernetes/client-node/dist/gen/api/coreV1Api.js:13556:23)\n    at Generator.next (<anonymous>)\n    at /usr/src/app/node_modules/tslib/tslib.js:115:75\n    at new Promise (<anonymous>)\n    at Object.__awaiter (/usr/src/app/node_modules/tslib/tslib.js:111:16)\n    at CoreV1Api.patchNode (/usr/src/app/node_modules/@kubernetes/client-node/dist/gen/api/coreV1Api.js:13540:24)\n    at /usr/src/app/controllers/node.js:39:10\n    at Array.forEach (<anonymous>)\n    at cordonNodes (/usr/src/app/controllers/node.js:31:19)\n    at Layer.handle [as handle_request] (/usr/src/app/node_modules/express/lib/router/layer.js:95:5)\n    at next (/usr/src/app/node_modules/express/lib/router/route.js:137:13)\n    at Route.dispatch (/usr/src/app/node_modules/express/lib/router/route.js:112:3)\n    at Layer.handle [as handle_request] (/usr/src/app/node_modules/express/lib/router/layer.js:95:5)\n    at /usr/src/app/node_modules/express/lib/router/index.js:281:22\n    at Function.process_params (/usr/src/app/node_modules/express/lib/router/index.js:335:12)\n    at next (/usr/src/app/node_modules/express/lib/router/index.js:275:10)"
}
(node:18) UnhandledPromiseRejectionWarning: Error [ERR_HTTP_HEADERS_SENT]: Cannot set headers after they are sent to the client
    at ServerResponse.setHeader (_http_outgoing.js:470:11)
    at ServerResponse.header (/usr/src/app/node_modules/express/lib/response.js:771:10)
    at ServerResponse.send (/usr/src/app/node_modules/express/lib/response.js:170:12)
    at ServerResponse.json (/usr/src/app/node_modules/express/lib/response.js:267:15)
    at k8sApi.patchNode.then (/usr/src/app/controllers/node.js:55:29)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:18) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:18) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

And API not retry after failed.

**Comment by Binyang2014** [comment]
Refer #5020
