### ISSUE TITLE
Failed to start service hivedscheduler-hs 

### ISSUE THREAD

**Issue by q1234wo567** [microsoft/pai#5062]
**Short summary about the issue/question**:
```
2020-11-09 00:33:25,919 [INFO] - deployment.paiLibrary.paiService.service_management_start : Begin to start service: [ hivedscheduler ]
2020-11-09 00:33:25,920 [INFO] - deployment.paiLibrary.paiService.service_management_start : Begin to execute service hivedscheduler's start script.
configmap/hivedscheduler-config created
serviceaccount/hivedscheduler-account created
clusterrolebinding.rbac.authorization.k8s.io/hivedscheduler-role-binding created
service/hivedscheduler-service created
statefulset.apps/hivedscheduler-hs created
statefulset.apps/hivedscheduler-ds-default created
hivedscheduler-hs is not ready yet. Please wait for a moment!
hivedscheduler-hs is not ready yet. Please wait for a moment!
hivedscheduler-hs is not ready yet. Please wait for a moment!
hivedscheduler-hs is not ready yet. Please wait for a moment!
hivedscheduler-hs is not ready yet. Please wait for a moment!
hivedscheduler-hs is not ready yet. Please wait for a moment!
hivedscheduler-hs is not ready yet. Please wait for a moment!
hivedscheduler-hs is not ready yet. Please wait for a moment!
hivedscheduler-hs is not ready yet. Please wait for a moment!
hivedscheduler-hs is not ready yet. Please wait for a moment!
hivedscheduler-hs is not ready yet. Please wait for a moment!
hivedscheduler-hs is not ready yet. Please wait for a moment!
```

**Brief what process you are following**: deploy Openpai on dev-box, running commend `echo -e "pai\n" | python paictl.py service start`

**How to reproduce it**:

**OpenPAI Environment**:
- OpenPAI version:V1.3.0
- OS (e.g. from /etc/os-release):Ubuntu 16.04 LTS
- Others:I'm going to deploy openpai in a single node, and i follow #4614

**Anything else we need to know**:
Hope these information helpful
kubectl get pods
```
root@zcy:/pai# kubectl get pods
NAME                               READY   STATUS             RESTARTS   AGE
database-controller-sts-0          4/4     Running            0          4m36s
frameworkcontroller-sts-0          1/1     Running            0          5m31s
hivedscheduler-ds-default-0        1/1     Running            0          3m59s
hivedscheduler-hs-0                0/1     CrashLoopBackOff   5          3m59s
internal-storage-create-ds-lvvx7   1/1     Running            0          5m20s
postgresql-ds-ckgf5                2/2     Running            0          4m58s
```
kubectl describe pod hivedscheduler-hs-0
```
root@zcy:/pai# kubectl describe pod hivedscheduler-hs-0
Name:         hivedscheduler-hs-0
Namespace:    default
Priority:     0
Node:         openpai-master-01/10.112.136.90
Start Time:   Mon, 09 Nov 2020 00:33:28 +0000
Labels:       app=hivedscheduler-hs
              controller-revision-hash=hivedscheduler-hs-d99dd5dcf
              statefulset.kubernetes.io/pod-name=hivedscheduler-hs-0
Annotations:  cni.projectcalico.org/podIP: 10.207.147.145/32
              cni.projectcalico.org/podIPs: 10.207.147.145/32
Status:       Running
IP:           10.207.147.145
IPs:
  IP:           10.207.147.145
Controlled By:  StatefulSet/hivedscheduler-hs
Containers:
  hivedscheduler:
    Container ID:  docker://801d78892934ce66c366aae3e932788066a77a45caf6410dd3d8c66811f51ca0
    Image:         hivedscheduler/hivedscheduler:v0.3.4
    Image ID:      docker-pullable://hivedscheduler/hivedscheduler@sha256:d2d58d04520ba579484a82de242ff73b6f5d31fb728fe100f8b6576a0381d3f9
    Port:          <none>
    Host Port:     <none>
    Command:
      bash
      -c
      cp /hivedscheduler-config/hivedscheduler.yaml . && ./start.sh
    State:          Waiting
      Reason:       CrashLoopBackOff
    Last State:     Terminated
      Reason:       Error
      Exit Code:    2
      Started:      Mon, 09 Nov 2020 00:36:31 +0000
      Finished:     Mon, 09 Nov 2020 00:36:31 +0000
    Ready:          False
    Restart Count:  5
    Environment:    <none>
    Mounts:
      /hivedscheduler-config from hivedscheduler-config (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from hivedscheduler-account-token-tp2z6 (ro)
Conditions:
  Type              Status
  Initialized       True
  Ready             False
  ContainersReady   False
  PodScheduled      True
Volumes:
  hivedscheduler-config:
    Type:      ConfigMap (a volume populated by a ConfigMap)
    Name:      hivedscheduler-config
    Optional:  false
  hivedscheduler-account-token-tp2z6:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  hivedscheduler-account-token-tp2z6
    Optional:    false
QoS Class:       BestEffort
Node-Selectors:  pai-master=true
Tolerations:     node.kubernetes.io/not-ready:NoExecute op=Exists for 300s
                 node.kubernetes.io/unreachable:NoExecute op=Exists for 300s
Events:
  Type     Reason     Age                     From               Message
  ----     ------     ----                    ----               -------
  Normal   Scheduled  4m32s                   default-scheduler  Successfully assigned default/hivedscheduler-hs-0 to openpai-master-01
  Normal   Pulled     2m59s (x5 over 4m29s)   kubelet            Container image "hivedscheduler/hivedscheduler:v0.3.4" already present on machine
  Normal   Created    2m58s (x5 over 4m29s)   kubelet            Created container hivedscheduler
  Normal   Started    2m58s (x5 over 4m28s)   kubelet            Started container hivedscheduler
  Warning  BackOff    2m57s (x10 over 4m26s)  kubelet            Back-off restarting failed container
```
kubectl logs hivedscheduler-hs-0
```
root@zcy:/pai# kubectl logs hivedscheduler-hs-0
I1109 00:36:31.516257       9 scheduler.go:123] Initializing hivedscheduler
I1109 00:36:31.517024       9 scheduler.go:126] With Config:
kubeApiServerAddress: ""
kubeConfigFilePath: ""
webServerAddress: :30096
forcePodBindThreshold: 3
waitingPodSchedulingBlockMilliSec: 50
physicalCluster:
  cellTypes:
    DT-NODE:
      childCellType: DT
      childCellNumber: 100000000
      isNodeLevel: true
    DT-NODE-POOL:
      childCellType: DT-NODE
      childCellNumber: 0
      isNodeLevel: false
  physicalCells:
  - cellType: DT-NODE-POOL
    cellAddress: "0"
    pinnedCellId: ""
virtualClusters:
  default:
    virtualCells:
    - cellNumber: 0
      cellType: DT-NODE-POOL.DT-NODE
I1109 00:36:31.517173       9 config.go:208] Watching config file: ./hivedscheduler.yaml
W1109 00:36:31.517212       9 client_config.go:549] Neither --kubeconfig nor --master was specified.  Using the inClusterConfig.  This might not work.
panic: runtime error: index out of range

goroutine 1 [running]:
github.com/microsoft/hivedscheduler/pkg/algorithm.newClusterView(0xc0003a3f20, 0xc0003d61b0, 0xc0000455d0, 0xc)
        /go/src/github.com/microsoft/hivedscheduler/pkg/algorithm/topology_aware_scheduler.go:166 +0x335
github.com/microsoft/hivedscheduler/pkg/algorithm.NewTopologyAwareScheduler(...)
        /go/src/github.com/microsoft/hivedscheduler/pkg/algorithm/topology_aware_scheduler.go:59
github.com/microsoft/hivedscheduler/pkg/algorithm.NewHivedAlgorithm(0xc00030adc0, 0x168cd80)
        /go/src/github.com/microsoft/hivedscheduler/pkg/algorithm/hived_algorithm.go:138 +0x587
github.com/microsoft/hivedscheduler/pkg/scheduler.NewHivedScheduler(0x11b5ef0)
        /go/src/github.com/microsoft/hivedscheduler/pkg/scheduler/scheduler.go:149 +0x350
main.main()
        /go/src/github.com/microsoft/hivedscheduler/cmd/hivedscheduler/main.go:35 +0x22

```

**Comment by abuccts** [comment]
```yaml
physicalCluster:
  cellTypes:
    DT-NODE:
      childCellType: DT
      childCellNumber: 100000000
      isNodeLevel: true
    DT-NODE-POOL:
      childCellType: DT-NODE
      childCellNumber: 0
      isNodeLevel: false
  physicalCells:
  - cellType: DT-NODE-POOL
    cellAddress: "0"
    pinnedCellId: ""
```

Could you use a valid configuration? You configured 0 child cell for `DT-NODE-POOL` but still specified a cell address.

**Comment by q1234wo567** [comment]
Thank you very much! @abuccts 
I successfully deploy openpai in a single node after modify layout.yaml
At first i set machine both master and worker:
```
machine-list:
    - hostname: openpai-master-01
      nodename: openpai-master-01
      hostip: 10.112.136.90
      machine-type: GENERIC-MASTER
      dashboard: "true"
      pai-master: "true"
      pai-worker: "true"
```
So i remove the last line, the file become:
```
machine-list:
    - hostname: openpai-master-01
      nodename: openpai-master-01
      hostip: 10.112.136.90
      machine-type: GENERIC-MASTER
      dashboard: "true"
      pai-master: "true"
```
It seems that the master node can't be master and worker at the same time?
If I encounter a new problem, I will reopen the issue
Thank you again!
