### ISSUE TITLE
jinja2.exceptions.TemplateSyntaxError: unexpected char '$' at 7836

### ISSUE THREAD

**Issue by guningbo** [microsoft/pai#5073]
**Organization Name**:
Hangzhou Innovation Institute, Beihang University

**Short summary about the issue/question

I successfully installed k8s, and when I install OpenPai service using this command: “/bin/bash quick-start-service.sh -m /home/paitest/pai-config/master.csv -w /home/paitest/pai-config/worker.csv -c /home/paitest/pai-config/config”，I get this error message appeared：
Traceback (most recent call last):
  File "/root/pai/contrib/kubespray/script/openpai-generator.py", line 365, in <module>
    main()
  File "/root/pai/contrib/kubespray/script/openpai-generator.py", line 360, in main
    map_table
  File "/root/pai/contrib/kubespray/script/openpai-generator.py", line 93, in generate_template_file
    generated_template = generate_from_template_dict(template, map_table)
  File "/root/pai/contrib/kubespray/script/openpai-generator.py", line 80, in generate_from_template_dict
    generated_file = jinja2.Template(template_data).render(
  File "/usr/local/lib/python3.5/dist-packages/jinja2/environment.py", line 1031, in __new__
    return env.from_string(source, template_class=cls)
  File "/usr/local/lib/python3.5/dist-packages/jinja2/environment.py", line 941, in from_string
    return cls.from_code(self, self.compile(source), globals, None)
  File "/usr/local/lib/python3.5/dist-packages/jinja2/environment.py", line 638, in compile
    self.handle_exception(source=source_hint)
  File "/usr/local/lib/python3.5/dist-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/usr/local/lib/python3.5/dist-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "<unknown>", line 208, in template
jinja2.exceptions.TemplateSyntaxError: unexpected char '$' at 7836。

**Brief what process you are following**:

**How to reproduce it**:

**OpenPAI Environment**:
- OpenPAI version: 1.3.0
- Cloud provider or hardware configuration: hardware
- OS (e.g. from /etc/os-release): ubuntu 1604
- Kernel (e.g. `uname -a`):
- Hardware (e.g. core number, memory size, storage size, GPU type etc.): 
- Others:

**Anything else we need to know**:
I did not have this problem when I installed the v1.2.1 version few days ago，and the v1.3.0 have this problem.
I I did some debugging work and found that the problem may be caused by #5067 ，but I am not sure

**Comment by guningbo** [comment]
I found the problem is caused by “ {{$labels.job_name}}” https://github.com/microsoft/pai/blob/6e80802df77c1b420feb55b59cdeb449a2d7b5df/contrib/kubespray/quick-start/services-configuration.yaml.template#L210.
I delete this part and this problem is skip,。But I don’t know if there will be other impacts, and I don’t know how to modify

**Comment by Binyang2014** [comment]
Reassigned to @suiguoxin

**Comment by suiguoxin** [comment]
> I found the problem is caused by “ {{$labels.job_name}}”
> 
> https://github.com/microsoft/pai/blob/6e80802df77c1b420feb55b59cdeb449a2d7b5df/contrib/kubespray/quick-start/services-configuration.yaml.template#L210
> 
> .
> I delete this part and this problem is skip。But I don’t know if there will be other impacts, and I don’t know how to modify

Hi, this part of code can be safely deleted without any impact. This problem is fixed in #5067 #5068, so you can simply checkout to branch pai-1.3.y to avoid this problem.
