### ISSUE TITLE
Nvidia-Device-Plugin configure failed

### ISSUE THREAD

**Issue by HaoLiuHust** [microsoft/pai#5358]
Version 1.3.0  
after run quick-start-kuberspray.sh succeed, then I run quick-start-service.sh,  it stuck with:
![image](https://user-images.githubusercontent.com/7233091/110322524-35011580-804e-11eb-9b6d-9c226e3860f8.png)

according to  
 ```
kubectl describe pod nvidia-device-plugin-daemonset-rznmm -n kube-system
```  
```
  Warning  FailedCreatePodSandBox  86s (x3439 over 12d)  kubelet, uface-gpu-server  (combined from similar events): Failed create pod sandbox: rpc error: code = Unknown desc = failed to set up sandbox container "0df2744b0b94bf34265cac275e08a2acfec406537f3fb126807dccdf7e6b3189" network for pod "nvidia-device-plugin-daemonset-rznmm": NetworkPlugin cni failed to set up pod "nvidia-device-plugin-daemonset-rznmm_kube-system" network: Get https://[10.192.0.1]:443/api/v1/namespaces/kube-system: dial tcp 10.192.0.1:443: i/o timeout

```
there was an timeout error, how to solve this problem?

**Comment by hzy46** [comment]
Hi @HaoLiuHust , looks like your nvidia device plugin cannot connect to k8s api server.

Please check the status of the api server. You can find the pod name of k8s api server by `kubectl get po  -n kube-system  | grep api`

**Comment by HaoLiuHust** [comment]
```
uniubi@uniubi-E500:~$ kubectl get po -n kube-system | grep api.
kube-apiserver-uniubi-alg053               1/1     Running             9          13d

```

**Comment by hzy46** [comment]
The api server has 9 restarts. Please check its log.

**Comment by hzy46** [comment]
Also, please start the nvidia device plugin. And try to connect to api server inside its containers.

**Comment by HaoLiuHust** [comment]
thanks, I have tried start the nvidia device plugin in the container, seem start succeed, how to connect to api server inside its containers?

**Comment by hzy46** [comment]
use `telnet 10.192.0.1 443` to try

**Comment by HaoLiuHust** [comment]
I have tried to rerun quick-start-kuberspray.sh and then quick-start-server.sh, there is a new issue:
```
starting nvidia device plugin to detect nvidia gpu resource
2021-03-09 08:03:39,434 [WARNING] - openpai-generator.py:110 : No pod can be dectected.
2021-03-09 08:03:39,434 [INFO] - openpai-generator.py:252 : Nvidia-Device-Plugin is not ready yet. Please wait for a moment!
2021-03-09 08:03:49,467 [WARNING] - openpai-generator.py:110 : No pod can be dectected.
2021-03-09 08:03:49,467 [INFO] - openpai-generator.py:252 : Nvidia-Device-Plugin is not ready yet. Please wait for a moment!
2021-03-09 08:03:59,508 [WARNING] - openpai-generator.py:110 : No pod can be dectected.
2021-03-09 08:03:59,509 [INFO] - openpai-generator.py:252 : Nvidia-Device-Plugin is not ready yet. Please wait for a moment!
2021-03-09 08:04:09,543 [WARNING] - openpai-generator.py:110 : No pod can be dectected.
```

**Comment by hzy46** [comment]
it's the same issue. please check the nvidia device plugin's state and find out why it is not ready

**Comment by HaoLiuHust** [comment]
I have start nvidia device plugin in the docker, and checked their status
```
uniubi@uniubi-E500:~/openpai/pai/contrib/kubespray$ kubectl get --namespace=kube-system pods | grep nvidia-device-plugin
nvidia-device-plugin-daemonset-grpzc       1/1     Running   0          2m28s
nvidia-device-plugin-daemonset-vtgq9       1/1     Running   0          2m28s

```
then, I run quick-start-service.sh again, 
```
uniubi@uniubi-E500:~/openpai/pai/contrib/kubespray$ /bin/bash quick-start-service.sh -m ~/openpai/master.csv -w ~/openpai/worker.csv -c ~/openpai/config.yaml 
worker list file path: /home/uniubi/openpai/worker.csv
master list file path: /home/uniubi/openpai/master.csv
cluster config file path: /home/uniubi/openpai/config.yaml
Branch Name v1.3.0
OpenPAI Image Tag v1.3.0
Local pai folder path: /home/uniubi/openpai/pai
docker: Error response from daemon: Conflict. The container name "/dev-box-quick-start" is already in use by container "2e0fbc4233fb13360c7c6cdc275cec82f9e22bcf581636b59cb6d027ab0441f6". You have to remove (or rename) that container to be able to reuse that name.
See 'docker run --help'.
NAME               STATUS   ROLES    AGE    VERSION
uface-gpu-server   Ready    <none>   112m   v1.15.11
uniubi-alg053      Ready    master   113m   v1.15.11
install pip3
branch name: v1.3.0
starting nvidia device plugin to detect nvidia gpu resource
2021-03-09 09:00:11,860 [INFO] - openpai-generator.py:218 : Ignore calculate pai daemon resource usage since qos-switch set to false
daemonset.extensions "nvidia-device-plugin-daemonset" deleted
Error from server (AlreadyExists): namespaces "pai-storage" already exists
Traceback (most recent call last):
  File "paictl.py", line 32, in <module>
    from deployment.checkCmd import CheckCmd
  File "/mnt/pai/deployment/checkCmd.py", line 1, in <module>
    from clusterObjectModel.cluster_object_model import cluster_object_model
ImportError: No module named 'clusterObjectModel'
Traceback (most recent call last):
  File "paictl.py", line 32, in <module>
    from deployment.checkCmd import CheckCmd
  File "/mnt/pai/deployment/checkCmd.py", line 1, in <module>
    from clusterObjectModel.cluster_object_model import cluster_object_model
ImportError: No module named 'clusterObjectModel'

```
```
uniubi@uniubi-E500:~/openpai/pai/contrib/kubespray$ kubectl get po -n kube-system | grep api.
kube-apiserver-uniubi-alg053               1/1     Running   0          105m

```

**Comment by hzy46** [comment]
`docker: Error response from daemon: Conflict. The container name "/dev-box-quick-start" is already in use by container "2e0fbc4233fb13360c7c6cdc275cec82f9e22bcf581636b59cb6d027ab0441f6". You have to remove (or rename) that container to be able to reuse that name.`

It is a legacy issue that we have already fixed, but it still exists in v1.3.0.

Please run `sudo docker stop dev-box-quick-start; sudo docker rm dev-box-quick-start` before every time you run `quick-start-service.sh`.

**Comment by HaoLiuHust** [comment]
if I add these 2 steps before quick-start-service.sh, I will encounter python related error, that's why I have to install python packages in the docker container and do not remove it after second run
```
debconf: unable to initialize frontend: Dialog
debconf: (No usable dialog-like program is installed, so the dialog based frontend cannot be used. at /usr/share/perl5/Debconf/FrontEnd/Dialog.pm line 76.)
debconf: falling back to frontend: Readline

Creating config file /etc/apt/apt.conf.d/20auto-upgrades with new version

Creating config file /etc/apt/apt.conf.d/50unattended-upgrades with new version
Processing triggers for libc-bin (2.23-0ubuntu10) ...
Processing triggers for dbus (1.10.6-1ubuntu3.6) ...
Processing triggers for systemd (229-4ubuntu21.15) ...
install pip3
Traceback (most recent call last):
  File "/usr/lib/python3.5/runpy.py", line 184, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/lib/python3/dist-packages/pip/__main__.py", line 19, in <module>
    sys.exit(pip.main())
  File "/usr/lib/python3/dist-packages/pip/__init__.py", line 207, in main
    cmd_name, cmd_args = parseopts(args)
  File "/usr/lib/python3/dist-packages/pip/__init__.py", line 147, in parseopts
    parser = create_main_parser()
  File "/usr/lib/python3/dist-packages/pip/__init__.py", line 120, in create_main_parser
    'formatter': UpdatingDefaultsHelpFormatter(),
  File "/usr/lib/python3/dist-packages/pip/baseparser.py", line 30, in __init__
    kwargs['width'] = get_terminal_size()[0] - 2
  File "/usr/lib/python3/dist-packages/pip/utils/__init__.py", line 480, in get_terminal_size
    return int(cr[1]), int(cr[0])
ValueError: invalid literal for int() with base 10: ''
Traceback (most recent call last):
  File "/usr/bin/pip3", line 11, in <module>
    sys.exit(main())
  File "/usr/lib/python3/dist-packages/pip/__init__.py", line 207, in main
    cmd_name, cmd_args = parseopts(args)
  File "/usr/lib/python3/dist-packages/pip/__init__.py", line 147, in parseopts
    parser = create_main_parser()
  File "/usr/lib/python3/dist-packages/pip/__init__.py", line 120, in create_main_parser
    'formatter': UpdatingDefaultsHelpFormatter(),
  File "/usr/lib/python3/dist-packages/pip/baseparser.py", line 30, in __init__
    kwargs['width'] = get_terminal_size()[0] - 2
  File "/usr/lib/python3/dist-packages/pip/utils/__init__.py", line 480, in get_terminal_size
    return int(cr[1]), int(cr[0])
ValueError: invalid literal for int() with base 10: ''
branch name: pai-1.3.y
starting nvidia device plugin to detect nvidia gpu resource
Traceback (most recent call last):
  File "/mnt/pai/contrib/kubespray/script/openpai-generator.py", line 13, in <module>
    import jinja2
ImportError: No module named 'jinja2'

```

**Comment by hzy46** [comment]
I don't suggest you to modify the python environment.

Looks like the `get_terminal_size` fails when install pip3. Can you check this? It should be related to your environment.

**Comment by HaoLiuHust** [comment]
master is ubuntu18.04 and worker is 16.04, is that the problem?

**Comment by hzy46** [comment]
> master is ubuntu18.04 and worker is 16.04, is that the problem?

it is ok. i think it is mainly related to your terminal environent

**Comment by HaoLiuHust** [comment]
Have some advice? the error happened in docker container, is my host terminal environment problem?

**Comment by fanyangCS** [comment]
please whether the network plugin has some issue.

**Comment by HaoLiuHust** [comment]
> please whether the network plugin has some issue.

after rerun quick-start-kubespary, network plugin problem has been solved, there some other issues in quick-start-service

**Comment by HaoLiuHust** [comment]
Upgraded to 1.4.0, this error disappeared, there one svn gitlab connect error when config service
