### ISSUE TITLE
GPU count is not right in dashboard

### ISSUE THREAD

**Issue by HaoLiuHust** [microsoft/pai#5364]
Version 1.4.0  
I have 8 gpu in work node, but only 1 displayed in dashboard, how to locate this issue?

**Comment by HaoLiuHust** [comment]
Issue time: 2021/3/9ä¸‹åˆ9:30:03
fatal:found gpu count changes in 10.1.9.55:9102

**Comment by HaoLiuHust** [comment]
#5217 I will try it first...

**Comment by HaoLiuHust** [comment]
I have modified layout.yaml in ~/pai-deploy/cluster-cfg, and then ``` ./paictl.py service stop -n cluster-configuration```, but not succeed
```root@uniubi-E500:/home/uniubi/openpai/pai# ./paictl.py service stop -n cluster-configuration
/usr/local/lib/python2.7/dist-packages/paramiko/transport.py:33: CryptographyDeprecationWarning: Python 2 is no longer supported by the Python core team. Support for it is now deprecated in cryptography, and will be removed in the next release.
  from cryptography.hazmat.backends import default_backend
Traceback (most recent call last):
  File "./paictl.py", line 101, in <module>
    main(sys.argv[1:])
  File "./paictl.py", line 93, in main
    parserd.handler(parserd)
  File "/home/uniubi/openpai/pai/deployment/serviceCmd.py", line 75, in service_stop
    service_management_stopper = service_management_stop.service_management_stop(args.kube_config_path, service_list)
  File "/home/uniubi/openpai/pai/deployment/paiLibrary/paiService/service_management_stop.py", line 36, in __init__
    self.cluster_object_model = service_management_configuration.get_cluster_object_model_from_k8s(kube_config_path)
  File "/home/uniubi/openpai/pai/deployment/paiLibrary/paiService/service_management_configuration.py", line 37, in get_cluster_object_model_from_k8s
    config_get_handler.run()
  File "/home/uniubi/openpai/pai/deployment/confStorage/download.py", line 82, in run
    self.check_cluster_id()
  File "/home/uniubi/openpai/pai/deployment/confStorage/download.py", line 50, in check_cluster_id
    cluster_id = conf_storage_util.get_cluster_id(self.KUBE_CONFIG_DEFAULT_LOCATION)
  File "/home/uniubi/openpai/pai/deployment/confStorage/conf_storage_util.py", line 81, in get_cluster_id
    resp = kubernetes_handler.get_configmap(PAI_KUBE_CONFIG_DEFAULT_LOCATION, "pai-cluster-id")
  File "/home/uniubi/openpai/pai/deployment/paiLibrary/common/kubernetes_handler.py", line 104, in get_configmap
    api_instance = get_kubernetes_corev1api(PAI_KUBE_CONFIG_PATH=PAI_KUBE_CONFIG_DEFAULT_LOCATION)
  File "/home/uniubi/openpai/pai/deployment/paiLibrary/common/kubernetes_handler.py", line 34, in get_kubernetes_corev1api
    config.load_kube_config(config_file=PAI_KUBE_CONFIG_PATH)
  File "/usr/local/lib/python2.7/dist-packages/kubernetes/config/kube_config.py", line 794, in load_kube_config
    persist_config=persist_config)
  File "/usr/local/lib/python2.7/dist-packages/kubernetes/config/kube_config.py", line 752, in _get_kube_config_loader
    'Invalid kube-config file. '
kubernetes.config.config_exception.ConfigException: Invalid kube-config file. No configuration found.
```

**Comment by HaoLiuHust** [comment]
@hzy46
