### ISSUE TITLE
Unable to copy my file to the host

### ISSUE THREAD

**Issue by RchalYang** [Microsoft/pai#551]
when I use the following command to copy my file to the host server, I got some "UndeclaredException".

D:\tools\pai-fs>python pai-fs.py -cp -r d:\code\GameAI hdfs://code/ruyang
d:/code/GameAI/.gitignore -> code/ruyang/GameAI/.gitignore
- Progress: Traceback (most recent call last):
  File "D:\tools\pai-fs\fsimpl\HadoopFs.py", line 232, in touch_file
    self.hdfs.create_file(fd.abspath, 0, overwrite=True)
  File "C:\Users\v-ruyang\AppData\Local\Continuum\anaconda3\lib\site-packages\pywebhdfs\webhdfs.py", line 106, in create_file
    init_response.status_code, init_response.content)
  File "C:\Users\v-ruyang\AppData\Local\Continuum\anaconda3\lib\site-packages\pywebhdfs\webhdfs.py", line 722, in _raise_pywebhdfs_exception
    raise errors.PyWebHdfsException(msg=message)
pywebhdfs.errors.PyWebHdfsException: b'{"RemoteException":{"exception":"UndeclaredThrowableException","javaClassName":"java.lang.reflect.UndeclaredThrowableException","message":null}}'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "pai-fs.py", line 447, in <module>
    exitCode=cp_command(cmdLineArgs.myArgs, cmdLineArgs.recursive, cmdLineArgs.force)
  File "pai-fs.py", line 243, in cp_command
    srcFileSystem.cp_file(currentFile, dstRootFileDescriptor, dstFileSystem, force)
  File "D:\tools\pai-fs\fsimpl\BaseFs.py", line 284, in cp_file
    self.remote_cp_file(src, dst, dstFs)
  File "D:\tools\pai-fs\fsimpl\BaseFs.py", line 208, in remote_cp_file
    dstFs.touch_file(dst)
  File "D:\tools\pai-fs\fsimpl\HadoopFs.py", line 241, in touch_file
    raise Errors.FsException("An exception happened during HDFS create file: {0}, exc={1}".format(fd.abspath, e))
fsimpl.Errors.FsException: An exception happened during HDFS create file: code/ruyang/GameAI/.gitignore, exc=b'{"RemoteException":{"exception":"UndeclaredThrowableException","javaClassName":"java.lang.reflect.UndeclaredThrowableException","message":null}}'

I've created the parent directory and it's empty.
Or Is there anyone that I should send email to?

**Comment by abuccts** [comment]
Hi @RchalYang , have you configured `pai-fs` using `pai-fs --config host=ip port=50070 user=...` before as mentioned in [readme](https://github.com/Microsoft/pai/tree/master/pai-fs#usage)?

**Comment by RchalYang** [comment]
@abuccts We've fixed this problem. There is something wrong with the WebHDFS deployment. Thanks for replying.
