### ISSUE TITLE
Jobs cannot start due to PLATFORM_FAILURE

### ISSUE THREAD

**Issue by siaimes** [microsoft/pai#5519]
**Organization Name**:

**Short summary about the issue/question**: Jobs cannot start due to PLATFORM_FAILURE

**Brief what process you are following**:
Just submit the jobs as usual. Then failed with `PLATFORM_FAILURE`.
Exit Diagnositics:
```
[Exit Trigger Info]

ExitTriggerMessage: FailedTaskCount 1 has reached MinFailedTaskCount 1 in the TaskRole
ExitTriggerTaskRole: taskrole
ExitTriggerTaskIndex: 0

--------------------------------------------------------------------------------

[Exit Spec]

code: 1
phrase: PAIRuntimeExitAbnormally
issuer: PAI_RUNTIME
causer: PAI_RUNTIME
type: PLATFORM_FAILURE
stage: UNKNOWN
behavior: UNKNOWN
reaction: RETRY_TO_MAX
reason: 'PAI Runtime exit abnormally with undefined exitcode, it may have bugs'
repro:
  - PAI Runtime exits with exitcode 1
solution:
  - Contact PAI Dev to fix PAI Runtime bugs


--------------------------------------------------------------------------------

[Exit Diagnostics]

Pod failed: PodPattern unmatched:
containers:
  - name: init
    reason: Error
    message: >
      m framework.json

      + CHILD_PROCESS=PLUGIN_INITIALIZER

      + python /usr/local/pai/init.d/initializer.py
      /usr/local/pai/runtime.d/job_config.yaml
      /usr/local/pai/secrets/secrets.yaml
      /usr/local/pai/user-extension-secrets/userExtensionSecrets.yaml
      /usr/local/pai/token-secrets/token /usr/local/pai/plugins
      /usr/local/pai/runtime.d taskrole

      2021-06-06 09:43:22,673 - INFO - initializer.py:235 - loading yaml from
      /usr/local/pai/runtime.d/job_config.yaml

      2021-06-06 09:43:22,680 - INFO - initializer.py:173 - Starting to prepare
      plugin ssh

      2021-06-06 09:43:22,759 - INFO - initializer.py:52 - 2021-06-06
      09:43:22,758 - INFO - init.py:118 - Ssh runtime plugin perpared

      2021-06-06 09:43:22,765 - INFO - initializer.py:173 - Starting to prepare
      plugin teamwise_storage

      2021-06-06 09:43:23,078 - INFO - initializer.py:52 - This plugin is
      deprecated, will ignore this plugin

      + CHILD_PROCESS=PORT_CONFLICT_CHECKER

      + python /usr/local/pai/init.d/port.py
      /usr/local/pai/runtime.d/runtime_env.sh

      2021-06-06 09:43:23,161 - INFO - port.py:71 - runtime env from
      /usr/local/pai/runtime.d/runtime_env.sh

      Traceback (most recent call last):
        File "/usr/local/pai/init.d/port.py", line 81, in <module>
          main()
        File "/usr/local/pai/init.d/port.py", line 76, in main
          check_port_list_env(matches.group(1))
        File "/usr/local/pai/init.d/port.py", line 59, in check_port_list_env
          check_port(int(each))
        File "/usr/local/pai/init.d/port.py", line 44, in check_port
          ret = sock.connect_ex(('localhost', portno))
      socket.gaierror: [Errno -2] Name does not resolve

      + exit_handler

      + EXIT_CODE=1

      + '[[' 1 -eq 0 ]]

      + echo 'start execute exit handler'

      start execute exit handler

      + echo 'child process is PORT_CONFLICT_CHECKER, exit code is 1'

      child process is PORT_CONFLICT_CHECKER, exit code is 1

      + '[[' PORT_CONFLICT_CHECKER '=' FRAMEWORK_BARRIER ]]

      + '[[' PORT_CONFLICT_CHECKER '=' PORT_CONFLICT_CHECKER ]]

      + '[[' 1 -eq 10 ]]

      + '[[' PORT_CONFLICT_CHECKER '=' DOCKER_IMAGE_CHECKER ]]

      + echo 'Unknown exit code, platform error'

      Unknown exit code, platform error

      + exit 1
    code: 1
  - name: app
    code: 0
```

barrier.log
```
I0606 09:43:22.550655      14 barrier.go:211] Initializing frameworkbarrier
I0606 09:43:22.550763      14 barrier.go:214] With Config: 
kubeApiServerAddress: ""
kubeConfigFilePath: ""
frameworkNamespace: default
frameworkName: 979108637ba7a69e0cab6f52ddeacb19
barrierCheckIntervalSec: 10
barrierCheckTimeoutSec: 600
W0606 09:43:22.550780      14 client_config.go:549] Neither --kubeconfig nor --master was specified.  Using the inClusterConfig.  This might not work.
I0606 09:43:22.551656      14 barrier.go:227] Running frameworkbarrier
I0606 09:43:22.561792      14 barrier.go:322] BarrierPassed: 1/1 Tasks are ready with not nil PodIP.
I0606 09:43:22.561802      14 barrier.go:267] BarrierSucceeded: All Tasks are ready with not nil PodIP.
I0606 09:43:22.562893      14 barrier.go:350] Succeeded to dump the Framework object to local file: ./framework.json
I0606 09:43:22.562942      14 barrier.go:451] Succeeded to generate the injector script to local file: ./injector.sh
I0606 09:43:22.562963      14 barrier.go:459] ExitCode: 0: Exit with success.
```

init.log
```
+ CHILD_PROCESS=UNKNOWN
+ trap exit_handler EXIT
+ PAI_WORK_DIR=/usr/local/pai
+ PAI_CONFIG_DIR=/usr/local/pai-config
+ PAI_INIT_DIR=/usr/local/pai/init.d
+ PAI_RUNTIME_DIR=/usr/local/pai/runtime.d
+ PAI_LOG_DIR=/usr/local/pai/logs/6c17d723-6524-4856-a3e0-3f126f677981
+ PAI_SECRET_DIR=/usr/local/pai/secrets
+ PAI_USER_EXTENSION_SECRET_DIR=/usr/local/pai/user-extension-secrets
+ PAI_TOKEN_SECRET_DIR=/usr/local/pai/token-secrets
+ chmod a+rw /usr/local/pai/logs/6c17d723-6524-4856-a3e0-3f126f677981
+ find /usr/local/pai/logs/6c17d723-6524-4856-a3e0-3f126f677981 -maxdepth 1 -type f '!' -name init.log
+ LOG_FILES=
+ '[[' '!' -z  ]]
+ find /usr/local/pai -maxdepth 1 -mindepth 1 '!' -name logs -exec rm -rf '{}' ';'
rm: can't remove '/usr/local/pai/user-extension-secrets/..data': Read-only file system
rm: can't remove '/usr/local/pai/user-extension-secrets/userExtensionSecrets.yaml': Read-only file system
rm: can't remove '/usr/local/pai/user-extension-secrets/..2021_06_06_09_43_19.217927308/userExtensionSecrets.yaml': Read-only file system
+ mv ./__init__.py ./common ./init ./init.d ./package_cache ./plugins ./requirements.txt ./runtime ./runtime.d /usr/local/pai
+ cd /usr/local/pai
+ '[[' true '=' true ]]
+ CHILD_PROCESS=FRAMEWORK_BARRIER
+ echo 'frameworkbarrier start'
frameworkbarrier start
+ '[[' -f /var/run/secrets/kubernetes.io/serviceaccount/token ]]
+ unset KUBE_APISERVER_ADDRESS
+ /usr/local/pai/init.d/frameworkbarrier
+ tee /usr/local/pai/logs/6c17d723-6524-4856-a3e0-3f126f677981/barrier.log
I0606 09:43:22.550655      14 barrier.go:211] Initializing frameworkbarrier
I0606 09:43:22.550763      14 barrier.go:214] With Config: 
kubeApiServerAddress: ""
kubeConfigFilePath: ""
frameworkNamespace: default
frameworkName: 979108637ba7a69e0cab6f52ddeacb19
barrierCheckIntervalSec: 10
barrierCheckTimeoutSec: 600
W0606 09:43:22.550780      14 client_config.go:549] Neither --kubeconfig nor --master was specified.  Using the inClusterConfig.  This might not work.
I0606 09:43:22.551656      14 barrier.go:227] Running frameworkbarrier
I0606 09:43:22.561792      14 barrier.go:322] BarrierPassed: 1/1 Tasks are ready with not nil PodIP.
I0606 09:43:22.561802      14 barrier.go:267] BarrierSucceeded: All Tasks are ready with not nil PodIP.
I0606 09:43:22.562893      14 barrier.go:350] Succeeded to dump the Framework object to local file: ./framework.json
I0606 09:43:22.562942      14 barrier.go:451] Succeeded to generate the injector script to local file: ./injector.sh
I0606 09:43:22.562963      14 barrier.go:459] ExitCode: 0: Exit with success.
+ CHILD_PROCESS=ERROR_SPEC
+ cp /usr/local/pai-config/runtime-exit-spec.yaml /usr/local/pai/runtime.d
+ CHILD_PROCESS=ENV_GENERATOR
+ python /usr/local/pai/init.d/framework_parser.py genenv framework.json
2021-06-06 09:43:22,595 - INFO - framework_parser.py:196 - loading json from framework.json
2021-06-06 09:43:22,596 - INFO - framework_parser.py:107 - task roles: {'taskrole': {'number': 1, 'ports': {'schedulePortStart': 15000, 'schedulePortEnd': 40000, 'ports': {'ssh': {'count': 1}, 'http': {'count': 1}}}}}
+ CHILD_PROCESS=CONFIG_GENERATOR
+ python /usr/local/pai/init.d/framework_parser.py genconf framework.json
2021-06-06 09:43:22,628 - INFO - framework_parser.py:196 - loading json from framework.json
+ CHILD_PROCESS=PLUGIN_INITIALIZER
+ python /usr/local/pai/init.d/initializer.py /usr/local/pai/runtime.d/job_config.yaml /usr/local/pai/secrets/secrets.yaml /usr/local/pai/user-extension-secrets/userExtensionSecrets.yaml /usr/local/pai/token-secrets/token /usr/local/pai/plugins /usr/local/pai/runtime.d taskrole
2021-06-06 09:43:22,673 - INFO - initializer.py:235 - loading yaml from /usr/local/pai/runtime.d/job_config.yaml
2021-06-06 09:43:22,680 - INFO - initializer.py:173 - Starting to prepare plugin ssh
2021-06-06 09:43:22,759 - INFO - initializer.py:52 - 2021-06-06 09:43:22,758 - INFO - init.py:118 - Ssh runtime plugin perpared
2021-06-06 09:43:22,765 - INFO - initializer.py:173 - Starting to prepare plugin teamwise_storage
2021-06-06 09:43:23,078 - INFO - initializer.py:52 - This plugin is deprecated, will ignore this plugin
+ CHILD_PROCESS=PORT_CONFLICT_CHECKER
+ python /usr/local/pai/init.d/port.py /usr/local/pai/runtime.d/runtime_env.sh
2021-06-06 09:43:23,161 - INFO - port.py:71 - runtime env from /usr/local/pai/runtime.d/runtime_env.sh
Traceback (most recent call last):
  File "/usr/local/pai/init.d/port.py", line 81, in <module>
    main()
  File "/usr/local/pai/init.d/port.py", line 76, in main
    check_port_list_env(matches.group(1))
  File "/usr/local/pai/init.d/port.py", line 59, in check_port_list_env
    check_port(int(each))
  File "/usr/local/pai/init.d/port.py", line 44, in check_port
    ret = sock.connect_ex(('localhost', portno))
socket.gaierror: [Errno -2] Name does not resolve
+ exit_handler
+ EXIT_CODE=1
+ '[[' 1 -eq 0 ]]
+ echo 'start execute exit handler'
start execute exit handler
+ echo 'child process is PORT_CONFLICT_CHECKER, exit code is 1'
child process is PORT_CONFLICT_CHECKER, exit code is 1
+ '[[' PORT_CONFLICT_CHECKER '=' FRAMEWORK_BARRIER ]]
+ '[[' PORT_CONFLICT_CHECKER '=' PORT_CONFLICT_CHECKER ]]
+ '[[' 1 -eq 10 ]]
+ '[[' PORT_CONFLICT_CHECKER '=' DOCKER_IMAGE_CHECKER ]]
+ echo 'Unknown exit code, platform error'
Unknown exit code, platform error
+ exit 1
```

**How to reproduce it**:

**OpenPAI Environment**: 
- OpenPAI version: v1.6.0
- Cloud provider or hardware configuration: NA
- OS (e.g. from /etc/os-release):  Ubuntu 18.04.5 LTS (Bionic Beaver)
- Kernel (e.g. `uname -a`): 4.15.0-144-generic
- Hardware (e.g. core number, memory size, storage size, GPU type etc.):
- Others:

**Anything else we need to know**:

**Comment by siaimes** [comment]
I found the problem, my /etc/hosts file is damaged.

**Comment by poetryben88** [comment]
@siaimes   I have similar error ， please  how did you solved your problem?
[@](https://github.com/microsoft/pai/issues/5659)

**Comment by siaimes** [comment]
@poetryben88  Repair your `/etc/hosts` and `/etc/resolv.conf` of this node.

**Comment by siaimes** [comment]
@poetryben88 

Your error is this:
```Failed to get Framework object from ApiServer: Unauthorized```

My error is this:
```
socket.gaierror: [Errno -2] Name does not resolve
```

Do not the same!

**Comment by poetryben88** [comment]
@siaimes   thanks  ,  anyway!  Maybe  help me a lot.
