### ISSUE TITLE
Problems about rest-server

### ISSUE THREAD

**Issue by wangxianglang** [microsoft/pai#5670]
**Organization Name**:

**Short summary about the issue/question**:
I try to restart the `rest-server` service but there's something wrong with it.
Here's the log of the failed `rest-server` container:

> pai-rest-server@1.8.0 start /usr/src/app
> node index.js
`
(node:26) UnhandledPromiseRejectionWarning: Error: launcher config error
ValidationError: child "alertManagerUrl" fails because ["alertManagerUrl" is required]
    at Object.<anonymous> (/usr/src/app/src/config/launcher.js:146:11)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/usr/src/app/src/controllers/internal/tail-log.js:24:24)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
(node:26) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:26) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
`

I try to restart the master machine, but it doesn't work.

**OpenPAI Environment**:
- OpenPAI version: v1.8.0
- OS (e.g. from /etc/os-release): Ubuntu20.04

**Comment by HaoLiuHust** [comment]
how do you solved problem?
