### ISSUE TITLE
when restart rest-server,  UnhandledPromiseRejectionWarning: Error: launcher config error

### ISSUE THREAD

**Issue by HaoLiuHust** [microsoft/pai#5733]
**Organization Name**:

**Short summary about the issue/question**:
when restart rest-server, this error happend: 
(node:25) UnhandledPromiseRejectionWarning: Error: launcher config error
ValidationError: child "alertManagerUrl" fails because ["alertManagerUrl" is required]
    at Object.<anonymous> (/usr/src/app/src/config/launcher.js:146:11)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/usr/src/app/src/controllers/internal/tail-log.js:24:24)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
(node:25) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:25) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Brief what process you are following**:

**How to reproduce it**:

**OpenPAI Environment**: linux 16.04
- OpenPAI version: v1.8.0
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Hardware (e.g. core number, memory size, storage size, GPU type etc.):
- Others:

**Anything else we need to know**:

**Comment by HaoLiuHust** [comment]
seems because dev_box version is not compatibal with pai version
