### ISSUE TITLE
Help, rest server error.

### ISSUE THREAD

**Issue by lifubang** [Microsoft/pai#679]
```
root@iZ2ze75xet9v7jhynivwhcZ:~# docker logs k8s_rest-server_rest-server-ds-zq7g7_default_c6e5d8cc-6a3d-11e8-81ea-00163e0aec56_6

> pai-rest-server@0.1.0 start /usr/src/app
> node index.js

2018-06-07T10:37:01.283Z [INFO] config: {"env":"production","logLevel":"debug","serverPort":8080,"jwtSecret":"your_jwt_secret"} 
2018-06-07T10:37:01.286Z [INFO] launcher config: {"hdfsUri":"hdfs://iz2ze75xet9v7jhynivwhcz:9000","webhdfsUri":"http://iz2ze75xet9v7jhynivwhcz:50070","webserviceUri":"http://iz2ze75xet9v7jhynivwhcz:9086","webserviceRequestHeaders":{"Accept":"application/json","Content-Type":"application/json"},"jobRootDir":"./frameworklauncher","jobDirCleanUpIntervalSecond":7200,"jobConfigFileName":"JobConfig.json","frameworkDescriptionFilename":"FrameworkDescription.json"} 
2018-06-07T10:37:01.293Z [INFO] RESTful API server starts on port 8080 
/usr/src/app/src/config/launcher.js:122
      throw new Error('cannot connect to framework launcher');
      ^

Error: cannot connect to framework launcher
    at unirest.get.timeout.end (/usr/src/app/src/config/launcher.js:122:13)
    at Request.handleRequestResponse [as _callback] (/usr/src/app/node_modules/unirest/index.js:355:15)
    at self.callback (/usr/src/app/node_modules/unirest/node_modules/request/request.js:187:22)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:188:7)
    at Request.onRequestError (/usr/src/app/node_modules/unirest/node_modules/request/request.js:813:8)
    at emitOne (events.js:96:13)
    at ClientRequest.emit (events.js:188:7)
    at Socket.socketErrorListener (_http_client.js:314:9)
    at emitOne (events.js:96:13)

npm ERR! Linux 4.4.0-105-generic
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
npm ERR! node v6.14.2
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! pai-rest-server@0.1.0 start: `node index.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the pai-rest-server@0.1.0 start script 'node index.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the pai-rest-server package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node index.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs pai-rest-server
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls pai-rest-server
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /usr/src/app/npm-debug.log
```

![s_x3m22h5118 j 4a2e l](https://user-images.githubusercontent.com/783424/41094992-ae5c8d86-6a82-11e8-857b-6e6c949a52ce.png)

**Comment by fanyangCS** [comment]
Please check the configuration file to make sure rest-server is configured to connect to the right IP:Port of frameworklauncher

**Comment by lifubang** [comment]
which yaml to config frameworklauncher?
The urls in launcher config can be assessed successfully.
"hdfsUri":"hdfs://iz2ze75xet9v7jhynivwhcz:9000","webhdfsUri":"http://iz2ze75xet9v7jhynivwhcz:50070","webserviceUri":"http://iz2ze75xet9v7jhynivwhcz:9086","webserviceRequestHeaders":{"Accept":"application/json","Content-Type":"application/json"},"jobRootDir":"./frameworklauncher","jobDirCleanUpIntervalSecond":7200,"jobConfigFileName":"JobConfig.json","frameworkDescriptionFilename":"FrameworkDescription.json"}

**Comment by fanyangCS** [comment]
"iz2ze75xet9v7jhynivwhcz". please use an IP address, instead of a DNS name. It is unclear whether the dns can be resolved within a docker instance.

**Comment by ydye** [comment]
You could find launcher's address in the generated file of this [template](https://github.com/Microsoft/pai/blob/master/pai-management/bootstrap/rest-server/rest-server.yaml.template#L41)
You can check whether laucnher's ip address is parsed correctly.

**Comment by lifubang** [comment]
@fanyangCS But if I use ip address, it raise some errors in deploy process:
root@iZ2ze7lqgecgbz7737w78xZ:/pai/pai-management# ./deploy.py -d -p /cluster-configuration
Login Succeeded
2018-06-12 09:07:24,776 [INFO] - __main__ : docker registry login successfully
configmap "host-configuration" created
configmap "docker-credentials" created
configmap "gpu-configuration" created
secret "dockerforpai" created
daemonset.extensions "drivers-one-shot" created
/usr/local/lib/python2.7/dist-packages/requests/__init__.py:80: RequestsDependencyWarning: urllib3 (1.23) or chardet (3.0.4) doesn't match a supported version!
  RequestsDependencyWarning)
No GPU machine in your cluster
Error from server (NotFound): nodes "172.17.254.53" not found
Error from server (NotFound): nodes "172.17.254.53" not found
Error from server (NotFound): nodes "172.17.254.48" not found
Error from server (NotFound): nodes "172.17.254.48" not found
Error from server (NotFound): nodes "172.17.255.10" not found
Error from server (NotFound): nodes "172.17.255.10" not found
Error from server (NotFound): nodes "172.17.255.10" not found
Error from server (NotFound): nodes "172.17.255.10" not found
Error from server (NotFound): nodes "172.17.254.244" not found
Error from server (NotFound): nodes "172.17.254.244" not found

**Comment by lifubang** [comment]
I setup a dns server, and tell k8s with ConfigMap. and my clusterip is 10.96.0.10.
//kubernetes-configuration.yaml
```
kubernetes:
  # Find the namesever in  /etc/resolv.conf
  cluster-dns: 10.96.0.10
```
and:
```
root@iz2ze7lqgecgbz7737w78xz:~# nslookup iz2ze0b89inkcpmathnhskz.acmcoder.mmttnn 10.96.0.10
Server:		10.96.0.10
Address:	10.96.0.10#53

Name:	iz2ze0b89inkcpmathnhskz.acmcoder.mmttnn
Address: 172.17.254.244
```

But when deploy with: ./deploy.py -d -p /cluster-configuration, it displays:
hadoop-data-node is not ready yet. Please wait for a moment!

The pod's log is:
```
java.net.UnknownHostException: iz2ze0b89inkcpmathnhskz.acmcoder.mmttnn: iz2ze0b89inkcpmathnhskz.acmcoder.mmttnn: Name or service not known
	at java.net.InetAddress.getLocalHost(InetAddress.java:1505)
	at org.apache.hadoop.security.SecurityUtil.getLocalHostName(SecurityUtil.java:190)
	at org.apache.hadoop.security.SecurityUtil.login(SecurityUtil.java:210)
	at org.apache.hadoop.hdfs.server.datanode.DataNode.instantiateDataNode(DataNode.java:2255)
	at org.apache.hadoop.hdfs.server.datanode.DataNode.createDataNode(DataNode.java:2304)
	at org.apache.hadoop.hdfs.server.datanode.DataNode.secureMain(DataNode.java:2481)
	at org.apache.hadoop.hdfs.server.datanode.DataNode.main(DataNode.java:2505)
Caused by: java.net.UnknownHostException: iz2ze0b89inkcpmathnhskz.acmcoder.mmttnn: Name or service not known
	at java.net.Inet4AddressImpl.lookupAllHostAddr(Native Method)
	at java.net.InetAddress$2.lookupAllHostAddr(InetAddress.java:928)
	at java.net.InetAddress.getAddressesFromNameService(InetAddress.java:1323)
	at java.net.InetAddress.getLocalHost(InetAddress.java:1500)
	... 6 more
18/06/12 09:48:14 INFO util.ExitUtil: Exiting with status 1
18/06/12 09:48:14 INFO datanode.DataNode: SHUTDOWN_MSG: 
/************************************************************
SHUTDOWN_MSG: Shutting down DataNode at java.net.UnknownHostException: iz2ze0b89inkcpmathnhskz.acmcoder.mmttnn: iz2ze0b89inkcpmathnhskz.acmcoder.mmttnn: Name or service not known
************************************************************/
```

**Comment by victorming** [comment]
you should start yarn-frameworklauncher before start rest-server
