### ISSUE TITLE
some pods' status keep ContainerCreating when deploying

### ISSUE THREAD

**Issue by wm10240** [Microsoft/pai#694]
####  ./deploy.py -d -p /cluster-configuration

```
Login Succeeded
2018-06-09 09:45:04,986 [INFO] - __main__ : docker registry login successfully
configmap "host-configuration" created
configmap "docker-credentials" created
configmap "gpu-configuration" created
secret "novumind" created
node "192.168.1.56" labeled
node "192.168.1.55" labeled
daemonset.extensions "drivers-one-shot" created
drivers-one-shot is not ready yet. Please wait for a moment!
drivers-one-shot is ready!
error: 'hdfsrole' already has a value (master), and --overwrite is false
error: 'yarnrole' already has a value (master), and --overwrite is false
error: 'hdfsrole' already has a value (worker), and --overwrite is false
error: 'yarnrole' already has a value (worker), and --overwrite is false
configmap "hadoop-configuration" created
daemonset.extensions "zookeeper-ds" created
zookeeper is not ready yet. Please wait for a moment!
zookeeper is ready!
daemonset.extensions "hadoop-name-node-ds" created
hadoop-name-node is not ready yet. Please wait for a moment!
hadoop-name-node is ready!
daemonset.extensions "hadoop-data-node-ds" created
hadoop-data-node is not ready yet. Please wait for a moment!
hadoop-data-node is ready!
daemonset.extensions "hadoop-resource-manager-ds" created
hadoop-resource-manager is not ready yet. Please wait for a moment!
hadoop-resource-manager is ready!
daemonset.extensions "hadoop-node-manager-ds" created
hadoop-node-manager is not ready yet. Please wait for a moment!
hadoop-node-manager is ready!
daemonset.extensions "hadoop-jobhistory-service" created
hadoop-jobhistory-service is not ready yet. Please wait for a moment!
hadoop-jobhistory-service is ready!
job.batch "batch-job-hadoop" created
configmap "frameworklauncher-configmap" created
daemonset.extensions "frameworklauncher-ds" created
daemonset.extensions "rest-server-ds" created
daemonset.extensions "webportal-ds" created
error: 'node-exporter' already has a value (true), and --overwrite is false
error: 'node-exporter' already has a value (true), and --overwrite is false
configmap "prometheus-configmap" created
daemonset.extensions "node-exporter" created
deployment.extensions "prometheus-deployment" created
configmap "grafana-configuration" created
deployment.extensions "grafana" created
deployment.extensions "end-to-end-test-deployment" created
daemonset.extensions "pylon-ds" created
```

####  kubectl get pods

```
NAME                                          READY     STATUS              RESTARTS   AGE
batch-job-hadoop-4mrld                        0/1       Completed           0          7m
drivers-one-shot-cd6gs                        1/1       Running             0          8m
drivers-one-shot-tvs7f                        1/1       Running             0          8m
end-to-end-test-deployment-5bb64f7567-hvs7f   0/1       ContainerCreating   0          7m
etcd-server-192.168.1.56                      1/1       Running             0          1h
frameworklauncher-ds-mcgrg                    1/1       Running             0          7m
grafana-5f948f4cd4-2fvcp                      1/1       Running             0          7m
hadoop-data-node-ds-h7ctt                     1/1       Running             0          8m
hadoop-jobhistory-service-nzh7c               1/1       Running             0          7m
hadoop-name-node-ds-kxsth                     1/1       Running             0          8m
hadoop-node-manager-ds-tm7md                  1/1       Running             0          7m
hadoop-resource-manager-ds-z5v49              1/1       Running             0          8m
node-exporter-6lnxt                           2/2       Running             0          7m
node-exporter-l7kn7                           2/2       Running             0          7m
prometheus-deployment-565c654c7b-ckvs9        1/1       Running             0          7m
pylon-ds-c672z                                0/1       ContainerCreating   0          7m
rest-server-ds-n7qcq                          0/1       ContainerCreating   0          7m
webportal-ds-knnz5                            0/1       ContainerCreating   0          7m
zookeeper-ds-qgsw6                            1/1       Running             0          8m
```

the pods  ContainerCreating all have same errors like following , and the container in the nodes never been created, so  more errors can't be found.

#### kubectl describe pods webportal-ds-knnz5

```
.......
.......

Events:
  Type     Reason                  Age               From                   Message
  ----     ------                  ----              ----                   -------
  Warning  FailedCreatePodSandBox  8m (x13 over 8m)  kubelet, 192.168.1.56  Failed create pod sandbox.
  Normal   SandboxChanged          3m (x94 over 8m)  kubelet, 192.168.1.56  Pod sandbox changed, it will be killed and re-created.
```

I try many time, and have the same error,  anyone can give me a idea or help？ ths

**Comment by wm10240** [comment]
when I try run "docker run", the errors like:
```
# docker run -ti */pylon:latest
2018/06/10 08:09:31 [emerg] 9#0: invalid number of arguments in "set" directive in /etc/nginx/nginx.conf:166
nginx: [emerg] invalid number of arguments in "set" directive in /etc/nginx/nginx.conf:166
```
```
# docker run -ti  */rest-server:latest

> pai-rest-server@0.1.0 start /usr/src/app
> node index.js

/usr/src/app/src/config/index.js:59
  throw new Error(`config error\n${error}`);
  ^

Error: config error
ValidationError: child "jwtSecret" fails because ["jwtSecret" is required]
    at Object.<anonymous> (/usr/src/app/src/config/index.js:59:9)
    at Module._compile (module.js:577:32)
    at Object.Module._extensions..js (module.js:586:10)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)
    at Function.Module._load (module.js:445:3)
    at Module.require (module.js:504:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/src/app/src/server.js:25:16)
    at Module._compile (module.js:577:32)

npm ERR! Linux 4.4.0-87-generic
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
npm ERR! node v6.14.2
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! pai-rest-server@0.1.0 start: `node index.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the pai-rest-server@0.1.0 start script 'node index.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the pai-rest-server package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node index.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs pai-rest-server
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls pai-rest-server
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /usr/src/app/npm-debug.log
```

**Comment by ydye** [comment]
@hwuu

**Comment by abuccts** [comment]
@wm10240 , have you configured jwt secrect at [service-configuration.yaml](https://github.com/Microsoft/pai/blob/master/cluster-configuration/services-configuration.yaml#L90)?

**Comment by hwuu** [comment]
@wm10240 Containers of PAI modules, such as Pylon, restserver, etc., requires additional environment variables set by the `-e` parameter of `docker run` command. Directly executing `docker run -ti <module-img>` will definitely fail. You could see the `env` section in `./pai-management/bootstrap/<module>/<module>.yaml` for specific environment variables for each module.

By the way, could you tell us why you need to run docker by hand?

**Comment by jangojam** [comment]
i have the same problem, how to resolve it ？

**Comment by fanyangCS** [comment]
this is usually because of docker-pulling taking extra long time. you can wait for a while to see if the problem can go away. Please keep us updated if this solves the problem.
