### ISSUE TITLE
zookeeper service error

### ISSUE THREAD

**Issue by kenqxcheng** [Microsoft/pai#844]
Traceback (most recent call last):
  File "/usr/local/host-configure.py", line 90, in &lt;module&gt;
    main()
  File "/usr/local/host-configure.py", line 84, in main
    target_file_latest = generate_from_template(target_file_origin, cluster_config, hostname)
  File "/usr/local/host-configure.py", line 50, in generate_from_template
    "host_config": cluster_config[ hostname ],
KeyError: 'pai_master'
Traceback (most recent call last):
  File "/usr/local/host-configure.py", line 90, in &lt;module&gt;
    main()
  File "/usr/local/host-configure.py", line 84, in main
    target_file_latest = generate_from_template(target_file_origin, cluster_config, hostname)
  File "/usr/local/host-configure.py", line 50, in generate_from_template
    "host_config": cluster_config[ hostname ],
KeyError: 'pai_master'
ZooKeeper JMX enabled by default
Using config: /etc/zookeeper/conf/zoo.cfg
2018-07-11 01:12:08,786 - INFO  [main:QuorumPeerConfig@103] - Reading configuration from: /etc/zookeeper/conf/zoo.cfg
2018-07-11 01:12:08,791 - ERROR [main:QuorumPeerMain@85] - Invalid config, exiting abnormally
org.apache.zookeeper.server.quorum.QuorumPeerConfig$ConfigException: Error processing /etc/zookeeper/conf/zoo.cfg
	at org.apache.zookeeper.server.quorum.QuorumPeerConfig.parse(QuorumPeerConfig.java:123)
	at org.apache.zookeeper.server.quorum.QuorumPeerMain.initializeAndRun(QuorumPeerMain.java:101)
	at org.apache.zookeeper.server.quorum.QuorumPeerMain.main(QuorumPeerMain.java:78)
Caused by: java.lang.NumberFormatException: For input string: "{{cluster_config["
	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
	at java.lang.Long.parseLong(Long.java:589)
	at java.lang.Long.parseLong(Long.java:631)
	at org.apache.zookeeper.server.quorum.QuorumPeerConfig.parseProperties(QuorumPeerConfig.java:181)
Invalid config, exiting abnormally
	at org.apache.zookeeper.server.quorum.QuorumPeerConfig.parse(QuorumPeerConfig.java:119)
	... 2 more

**Comment by ydye** [comment]
Hi,

This line in configuration: https://github.com/Microsoft/pai/blob/master/cluster-configuration/cluster-configuration.yaml#L53

Please ssh to the target host, and run the command following to get your hostname.
```
echo `hostname`
```

Always, the similar problem is caused by this.


From your log:
```
target_file_latest = generate_from_template(target_file_origin, cluster_config, hostname)
File "/usr/local/host-configure.py", line 50, in generate_from_template
"host_config": cluster_config[ hostname ],
KeyError: 'pai_master'
```
I assume you set the hostname of the machine as `pai_master`, but I think the target host has a different hostname.

**Comment by kenqxcheng** [comment]
Thanks! The problem is solved.
